### PR TITLE
Avoid double key lookup for setting new key

### PR DESCRIPTION
**Pull request by lucasmoura**
In order to add a new key to both __objects and __functions dicts on jsinterp.py, it is
necessary to first verify if a key was present and if not, create the key and
assign it to a value.

However, this can be done with a single step using dict setdefault method.

### CODE REVIEW

**Comment by dstftw** [comment]
Can you check with flake8 and squash?

**Comment by lucasmoura** [comment]
oh sorry for that, I will fix the warnings right away

**Comment by lucasmoura** [comment]
@dstftw Done

**Comment by dstftw** [comment]
Cherry-picked in 7c05097633138459e9bdf7e10738e021b04689a7, thanks.

**Pull request closed without merging**
