### PR TITLE
Strip only args urls

### PR DESCRIPTION
**Pull request by FooBarQuaxx**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Avoid striping urls read from batch files as they are already striped.

### CODE REVIEW

**Comment by yan12125** [comment]
What this patch is aiming to solve?

**Comment by FooBarQuaxx** [comment]
Performance I guess. No need to double strip already striped urls coming from batch files. I know it's not something major, just a small contribution to OSS.

**Comment by yan12125** [comment]
> as they are already striped.

Sorry I didn't see this line. It's not true - there may be trailing spaces in batch files.

**Comment by FooBarQuaxx** [comment]
```
def read_batch_urls(batch_fd):
    def fixup(url):
        if not isinstance(url, compat_str):
            url = url.decode('utf-8', 'replace')
        BOM_UTF8 = '\xef\xbb\xbf'
        if url.startswith(BOM_UTF8):
            url = url[len(BOM_UTF8):]
-->      url = url.strip()
        if url.startswith(('#', ';', ']')):
            return False
        return url

    with contextlib.closing(batch_fd) as fd:
        return [url for url in map(fixup, fd) if url]
```

Please correct me if I am wrong.

**Comment by yan12125** [comment]
Seems reasonable, thanks!

**Comment by yan12125** [comment]
That looks good. Could you add a comment for why there's no need to strip ```batch_urls``` here?

**Comment by FooBarQuaxx** [comment]
I will.

**Comment by yan12125** [comment]
Thanks!

**Pull request merged**
