### PR TITLE
[BlenderCloud] Add new extractor (fixes issue #13282)

### PR DESCRIPTION
**Pull request by parmjitv**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Added a new extractor for the Blender Cloud platform [https://cloud.blender.org/] - issue #13282.

This site provides a variety of training videos for the Blender 3D creation suite.

Please note this extractor will ignore any subscriber-only videos - these require a Blender ID token and enrolment in the Blender Cloud Membership program, which AFAIK is a paid subscription.

Cheers and thank you!

Parmjit V.

### CODE REVIEW

**Comment by parmjitv** [comment]
Does this PR require any corrections?  Please let me know and I will be happy to update as needed.  Thanks!

**Comment by parmjitv** [comment]
Does this PR require any corrections?  Thank you!

**Comment by parmjitv** [comment]
@dstftw - Can you please review at your convenience?  I would like to have this PR resolved before I move on to the next issue, if at all possible.  Thanks!

**Comment by dstftw** [comment]
Lots of code duplication.

**Comment by parmjitv** [comment]
@dstftw - I have refactored the extractor to address the code duplication, please review at your convenience.  Cheers!

**Comment by parmjitv** [comment]
Closing due to inactivity.

**Pull request closed without merging**
