### PR TITLE
[jukebox] remove extractor and handle it using generic extractor

### PR DESCRIPTION
**Pull request by remitamine**

### CODE REVIEW

**Comment by dstftw** [comment]
Ultimedia does not work with these changes:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.ultimedia.com/default/index/videogeneric/id/s8uk0r']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.09.28
[debug] Git HEAD: c254f75
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-74386-g542562e, ffprobe N-74386-g542562e, rtmpdump 2.4
[debug] Proxy map: {}
[generic] s8uk0r: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s8uk0r: Downloading webpage
[generic] s8uk0r: Extracting information
ERROR: Unsupported URL: https://www.ultimedia.com/default/index/videogeneric/id/s8uk0r
Traceback (most recent call last):
  File "C:\Dev\git\youtube-dl\master\youtube_dl\extractor\generic.py", line 1241, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Dev\git\youtube-dl\master\youtube_dl\utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\python\python266\lib\xml\etree\ElementTree.py", line 963, in XML
    parser.feed(text)
  File "C:\python\python266\lib\xml\etree\ElementTree.py", line 1245, in feed
    self._parser.Parse(data, 0)
ExpatError: duplicate attribute: line 7, column 98
Traceback (most recent call last):
  File "C:\Dev\git\youtube-dl\master\youtube_dl\YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "C:\Dev\git\youtube-dl\master\youtube_dl\extractor\common.py", line 288, in extract
    return self._real_extract(url)
  File "C:\Dev\git\youtube-dl\master\youtube_dl\extractor\generic.py", line 1842, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.ultimedia.com/default/index/videogeneric/id/s8uk0r
```

**Comment by remitamine** [comment]
it works for me.
```
python2 __main__.py -F https://www.ultimedia.com/default/index/videogeneric/id/s8uk0r
[generic] s8uk0r: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s8uk0r: Downloading webpage
[generic] s8uk0r: Extracting information
[Ultimedia] s8uk0r: Downloading JSON metadata
[info] Available formats for s8uk0r:
format code  extension  resolution note
flv_def      flv        unknown    
mp4_def      mp4        unknown    (best)
```

**Comment by dstftw** [comment]
Nevermind, didn't merge it well. Still it should handle `https://www.ultimedia.com/default/index/videogeneric/id/s8uk0r` directly as it contains a video id right in URL.

**Comment by remitamine** [comment]
i didn't include them because they can handled indirectely by the generic extractor.
if it's necessary i will add a base extractor and create two extractors for normal urls and for embeds.

**Comment by dstftw** [comment]
There is no need in base class. Just covering both patterns in `_VALID_URL` should suffice.

**Comment by remitamine** [comment]
there is a small difference between them but it can be handled.

**Comment by dstftw** [comment]
Actually dropping `&topic=%s` worked well for me.

**Comment by remitamine** [comment]
with the same topic and different topic you get different results.
see the difference between:
http://www.ultimedia.com/deliver/video?video=xvpfp8
http://www.ultimedia.com/deliver/video?video=xvpfp8&topic=musique

the id should be changed.
i think about adding g for generic and m for musique

**Comment by remitamine** [comment]
> i will add a base extractor and create two extractors for normal urls and for embeds.

i can't get a good regex that will support both of them without a problems with extracting the id.

**Comment by remitamine** [comment]
i add some code to handle ultimedia videos directly.

**Pull request merged**
