### PR TITLE
[NowTV]: Add support for URLs containing "/jahr/" (for example series…

### PR DESCRIPTION
**Pull request by kripton**
… "Zuhause im Glück")

Including a test of course :)

### CODE REVIEW

**Comment by dstftw** [comment]
Just extend `NowTVIE`'s `_VALID_URL`. There is no need in separate extractor.

**Comment by kripton** [comment]
Ok, I'll try to put it all in one regex and commit to the same branch

**Comment by kripton** [comment]
Okay, I did the changes (back) in several commits and them squashed them together to one not to mangle the project's history. Should be ready to be merged I hope.

**Comment by dstftw** [comment]
This break matching of any URL that does not contain `/list/...`.
```
..F.............
======================================================================
FAIL: test_no_duplicates (__main__.TestAllURLsMatching)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_all_urls.py", line 93, in test_no_duplicates
    self.assertTrue(ie.suitable(url), '%s should match URL %r' % (type(ie).__name__, url))
AssertionError: NowTVIE should match URL u'http://www.nowtv.de/rtl/bauer-sucht-frau/die-neuen-bauern-und-eine-hochzeit/player'

----------------------------------------------------------------------
Ran 16 tests in 5.750s

FAILED (failures=1)
```

**Pull request closed without merging**
