### PR TITLE
[nowtv] rtlnow has been moved to nowtv.de

### PR DESCRIPTION
**Pull request by akirk**
Also fixes the broken `rtmpdump` downloads by using `HLS`

### CODE REVIEW

**Comment by dstftw** [comment]
Thanks.

**Comment by akirk** [comment]
Excuse me, did you intentionally close the pull request without merging?

**Comment by akirk** [comment]
Oh I see you did it without GitHub noticing, sorry for the roundtrip.

**Comment by dstftw** [comment]
Not sure why GitHub did not notice this but probably due to the original commit 5d0a33eebcae821ac5d1124043a5ad77a58fa291 (when I actually pulled your branch) replaced by 20135a0725ae376e4ed1e64c5c9f9c821f7f77f7 (have you `push --force`'ed it?).

**Comment by akirk** [comment]
Yeah I did an interactive rebase to squash my commits into one. That was probably it. Sorry for the confusion.

**Pull request closed without merging**
