### PR TITLE
Parallel downloads and youtube playlist regex fix

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I have added a feature to download multiple videos at same time, which will help in downloading a playlist faster. Please review the diff and merge. Comments/suggestions are welcome.

### CODE REVIEW

**Comment by TRox1972** [comment]
Should this be closed? The file in question does no longer exist.

**Comment by yan12125** [comment]
The parallel part is still useful, and I guess it's not difficult to rebase.

**Comment by ChillarAnand** [comment]
Any updates on this?

**Comment by yan12125** [comment]
The original author ("Ravi") of this PR has left Github, so I'm going to close this. Feel free to open a new PR with an implementation written from scratch or based on Ravi's work.

**Pull request closed without merging**
