### PR TITLE
[vimeo] Add support for extracting licenses

### LINKED ISSUE #8726: Feature request: Add video license to output dict of Vimeo videos
(Related ticket for YouTube: #8725)
There is no mentioning of video license in output dict of Vimeo videos:

```
>>> dl.extract_info('https://vimeo.com/157316669', download=False).keys()
WARNING: Parameter outtmpl is bytes, but should be a unicode string. Put  from __future__ import unicode_literals  at the top of your code file or consider switching to Python 3.x.
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.6 - Linux-3.19.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[vimeo] 157316669: Downloading webpage
[vimeo] 157316669: Extracting information
[vimeo] 157316669: Downloading webpage
[vimeo] 157316669: Downloading JSON metadata
[vimeo] 157316669: Downloading m3u8 information
[u'display_id', u'upload_date', u'protocol', u'description', u'extractor', u'requested_subtitles', u'format', u'tbr', u'height', u'like_count', u'uploader', u'duration', u'format_id', u'id', u'subtitles', u'view_count', u'playlist', u'thumbnails', u'fps', u'title', u'url', u'extractor_key', u'http_headers', u'ext', u'uploader_id', u'width', u'comment_count', u'playlist_index', u'webpage_url', u'formats', u'thumbnail', u'webpage_url_basename']
```

In a browser, the license is shown in the popup of "more" link beside the uploader.

Why is this needed? It is usually necessary to know the license in order to comply with the terms (see [downstream bug](https://github.com/Toollabs/video2commons/issues/6)).

### PR DESCRIPTION
**Pull request by legoktm**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This will extract the URL to the relevant Creative Commons license, if
the video is licensed using one of those. Otherwise it'll be `None`
since vimeo does not specify a license.

Fixes #8726

I wasn't really able to run the tests, they were spewing random http/url errors that seemed unrelated to my change. Also, my patch currently is returning a license URL rather than a human readable license name, is that acceptable?

### CODE REVIEW

**Comment by legoktm** [comment]
From my reading of `self._search_regex` it looks like the default parameter takes precedent over fatal?

**Comment by shizeeg** [comment]
@legoktm https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L643 Fatal is true by default.

**Comment by dstftw** [comment]
`default` and `fatal` have different purposes:
- `default` should be used when missing value is okay and you provide a hardcoded default fallback (either `None` or another value) and [`fatal` is not considered](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L669-L672) in this case.
- `fatal` is used when missing value is not okay but not that match to break the extraction. Warning is emitted in this case.

Whether one should be used or not is defined by a source:
- If meta field is always present in a source and you can't field any counter example then use `fatal`. If warning starts to appear for this meta field some time later it clear that most likely the source has changed and the regex should be updated.
- If meta field is not always present in a source `default` with `None` should be used.

**Comment by legoktm** [comment]
Thanks for explaining @dstftw. Vimeo only adds the license info if it's CC or PD, there's nothing copyrighted videos. So it seems like `default` is correct in this case, since the field isn't always there.

**Pull request closed without merging**
