### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Azulan**
Add explanation and workaround FAQ for YouTube SSL certificate error on Windows OS.

### CODE REVIEW

**Comment by yan12125** [comment]
"Google Internet Authority G2" (serial number 02:3A:83) is not a root CA, but "GeoTrust Global CA" (serial number 02:34:56) is. Users should check GeoTrust Global CA instead of downloading Google's certificates.

**Comment by Azulan** [comment]
@yan12125 But it is Google's cert that was expired.

**Comment by yan12125** [comment]
That's strange. When Python tries to connect to ```www.youtube.com:443```, youtube.com returns a certificate chain with 3 items: *.google.com (with *.youtube.com in subject alternative names), Google Internet Authority G2 and GeoTrust Global CA. Normal devices have only valid GeoTrust Global CA, so the whole certificate chain is trusted. Have you installed Google Internet Authority G2 certificate before?

**Comment by yan12125** [comment]
By https://github.com/rg3/youtube-dl/issues/7309#issuecomment-167414048, I think it's better to suggest users to remove expired Google Internet Authority G2 certificates.

**Comment by Azulan** [comment]
@yan12125 Perhaps, but do you really want non-technical users trying to poke around in the cert store and tell them to delete something? Mistakes could be disastrous. The offered solution is far simpler and less risky, I think.

**Comment by PotcFdk** [comment]
@Azulan Poking around in the cert store without knowing what you're doing is always a bad idea. If you add the wrong cert (note: it's not easy to tell what's a "good" and what's a "bad" certificate - even if you're technically competent), it could lead to all sorts of disasters.  
The one expired Google Internet Authority G2 certificate that I mentioned [here](https://github.com/rg3/youtube-dl/issues/7309#issuecomment-167414048) expired in April 2015, but I don't remember having experienced these issues that long ago. Thus, I'm not sure whether something added these useless certificates to the system recently or if previous versions of youtube-dl/python/whatever just did things in a different way.

**Comment by yan12125** [comment]
@Azulan your concern is possible. It would be better to have detailed instructions and warnings in boldface rather than a simple sentence "remove the expired Google Internet Authority G2 in certmgr.msc". You can add the steps to a file in [docs/](https://github.com/rg3/youtube-dl/tree/master/docs) as it might be too long to put all the things in FAQ. Of course users have rights to trust the downloaded certificate based on others' opinions, but it's inproper to suggest a wrong solution in ```README.md```.

**Pull request closed without merging**
