### PR TITLE
[Letv] Fix extraction

### LINKED ISSUE #6192: Letv Incomplete download
Recent usage of youtube-dl with letv.com causes problems where the video is incompletely fetched. For example, using it on the following video:
<pre>
youtube-dl -f 350 http://www.letv.com/ptv/vplay/1839416.html
</pre>
will download a 24 MB file. But originally, the lowest resolution (at 350) should be 79 MB. The same goes for other resolutions. The video notably stops at around the 10 minute mark, even though the entire video should be much longer.

It may be that the videos by Letv are now split up like Youku and Tudou. The flvcd site, though, suggests this is not the case.

### PR DESCRIPTION
**Pull request by yan12125**
This is an enhancement of #6376. This patch also fixes #6192 and #7144.

```compat_urllib_request_DataHandler``` is ported from [cpython hg rev 1733b3bd46db](https://hg.python.org/cpython/file/1733b3bd46db/Lib/urllib/request.py#l1599).

Cc @jaimeMF

### CODE REVIEW

**Comment by jaimeMF** [comment]
Everything seem to work, just two comments:
*  I would clean up the commit message from: https://github.com/yan12125/youtube-dl/commit/0a740fdbc07f763ef727c0cfad8801b7ee1b77e4, it references a few things that are not used anymore (function_pool and "Support preprocessing of m3u8 manifests").
* It seems that mime types are usually in lower-case, is there some reason to use `application/x-mpegURL`?

**Comment by yan12125** [comment]
I took the MIME type from Apple's doc [Deploying HTTP Live Streaming](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/DeployingHTTPLiveStreaming/DeployingHTTPLiveStreaming.html), and according to section 5.1 "
Syntax of the Content-Type Header Field" of [RFC2045](https://www.ietf.org/rfc/rfc2045.txt), upper-case english letters are allowed in the ```Content-Type``` field.

**Comment by yan12125** [comment]
Commit messages modified via ```rebase```. Thanks for pointing that out.

**Comment by jaimeMF** [comment]
IANA uses `application/vnd.apple.mpegurl`: https://www.iana.org/assignments/media-types/application/vnd.apple.mpegurl, https://www.iana.org/assignments/media-types/media-types.xhtml#application (this is what python's mimetypes module follows), at least vimeo also uses that mimetype for m3u8 manifest. If that's the most common we could use that instead, but it's not really important.

**Comment by yan12125** [comment]
Thanks. Updated as I think following Python's implementation is better.

**Comment by jaimeMF** [comment]
Unless someone disagrees with using `data:*`urls, I think you can merge it. Nice work.

**Comment by dstftw** [comment]
LGTM.

**Comment by yan12125** [comment]
Merged.

**Pull request merged**
