### PR TITLE
[20min.ch] Add new extractor (closes #5977)

### LINKED ISSUE #5977: please support 20min video (Swiss government sponsored and ad supported "news paper")
Please support 20min video

https://en.wikipedia.org/wiki/20_Minuten

> 20 Minuten (English: 20 Minutes) is a German-language free daily newspaper in Switzerland.

```
> youtube-dl http://www.20min.ch/schweiz/news/story/19176036                                                                                                                    
[generic] 19176036: Requesting header                                                                                                                                                             
WARNING: Falling back on generic information extractor.                                                                                                                                           
[generic] 19176036: Downloading webpage                                                                                                                                                           
ERROR: Unable to download webpage: HTTP Error 502: No data received from server or forwarder (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using 
the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                                           

> youtube-dl http://www.20min.ch/videotv/?vid=431707&cid=2                                                                                                                      
[1] 40904                                                                                                                                                                                         
> [generic] ?vid=431707: Requesting header                                                                                                                                      
WARNING: Falling back on generic information extractor.                                                                                                                                           
[generic] ?vid=431707: Downloading webpage                                                                                                                                                        
[generic] ?vid=431707: Extracting information                                                                                                                                                     
ERROR: Unsupported URL: http://www.20min.ch/videotv/?vid=431707                                                                                                                                   
                                                                                                                                                                                                  
[1]+  Exit 1                  youtube-dl http://www.20min.ch/videotv/?vid=431707                                                                                                                                                 
```

### PR DESCRIPTION
**Pull request by pingtux**
[20min.ch] Add new extractor (closes #5977)

### CODE REVIEW

**Comment by dstftw** [comment]
This most common pattern is not recognized: http://www.20min.ch/videotv/?vid=425123&cid=2.

**Comment by pingtux** [comment]
@dstftw Works now

**Comment by dstftw** [comment]
Cherry-picked, thanks.
Do you want to be credited as one of the authors of youtube-dl? If so under what name?

**Comment by pingtux** [comment]
Thank you.
> Do you want to be credited as one of the authors of youtube-dl? If so under what name?
No, thanks.

**Pull request closed without merging**
