### PR TITLE
[nbc] remove unavailable tests

### PR DESCRIPTION
**Pull request by remitamine**
this pages are not available anymore:
http://www.nbc.com/the-tonight-show/episodes/176:
```
Thank you, 404 Error, for being our website's way of saying, "We know you're looking for something, but we couldn't find anything, so here's nothing."
```
http://www.nbcnews.com/feature/dateline-full-episodes/full-episode-family-business-n285156
```
This page is unavailable.
```

### CODE REVIEW

**Comment by yan12125** [comment]
Usually a ```'skip': '(reason)',``` line is added instead of removing the whole test case. We try to retain the test case orders. (test_NBC_1, test_NBC_2, etc.)

**Comment by remitamine** [comment]
i just want to understand:
- what is the benefit of keeping broken urls in the tests?
- why trying to retain the test case orders if its generated automaticaly?

https://github.com/rg3/youtube-dl/blob/master/test/test_download.py#L221

**Comment by yan12125** [comment]
Sometimes test names are referred in issues/pull requests or commit messages.

**Comment by remitamine** [comment]
i will close this pull request and an other pull request to skip this test or just if you can add it directly

**Pull request closed without merging**
