### PR TITLE
[doc] coding conventions: add hint to linter

### PR DESCRIPTION
**Pull request by mk-pmb**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This patch makes it easier for potential new contributors to discover that we actually do have (and should use) a linter.

### CODE REVIEW

**Comment by dstftw** [comment]
Current wording is clear enough about what and should do and how.

**Comment by mk-pmb** [comment]
> Current wording is clear enough about what and should do and how.

Your opinion surprises me. It might be clear enough indeed, but not really accessible. Why should you care about UX in this case? Because some amount of your time and your effort was wasted.

How?
In your comment to #14388 you had to tell me "flake8.", meaning that indeed we do have a linter. I assume you also had to perform some kind of check in order to discover that I had not linted.

Why?
Yesterday the checbox in the issue lead me to the coding conventions. I read them, and couldn't find any sign of a linter in that chapter. I couldn't believe a project like this would do without, so I searched the text of the page for the word "lint". No match. I thus assumed we wouldn't use a linter here, and thus submitted my PR without linting.

**Comment by dstftw** [comment]
For this particular code I didn't run flake8. It's pretty obvious even after a brief look that the code does not meet PEP 8.
The same checkbox leads to the tutorial (it goes even before mentioning coding conventions) that describes everything needed step by step. You've searched for "lint" other may have searched for "pyflakes", "checker", "flake" or whatever they used to call it. This does not mean all these keywords should be mentioned. There are also many other specific aspects apart from code style that may also be referred differently and it's pointless to include all possible buzzwords for them. All you have to do is to read everything that is linked in template carefully.

**Comment by mk-pmb** [comment]
I see. Thanks for explaining.

**Pull request closed without merging**
