### PR TITLE
Fix NBC extractor

### PR DESCRIPTION
**Pull request by josejuan05**
Edit: Realized my bug was separate from OP in #18202; Created a separate Issue.

See Issue <s>#18202</s>#18236

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

NBC extractor is failing on some videos, as seen in Issue <s>#18202</s>#18236. Proposed change fixes problem.

### CODE REVIEW

**Comment by remitamine** [comment]
this does not fix anything, it requests the same URL twice.

**Comment by josejuan05** [comment]
This is an incorrect assessment. The URL in request['links']['self'] is not the same URL that was initially requested. See #18236. The bug is transient but predictable. In my case, it seems to occur for new episodes of Saturday Night Live on the NBC.com website the morning after the episode initially airs. It has occurred consistently for me for the past 3 weeks: If I try in the morning it will fail with the error output as given in the linked bug report. The patch given here fixes it. By the afternoon something on the NBC.com backend has been changed and youtube-dl works without the patch.

Maybe the more correct solution is to change the initial request to api.nbc.com. I don't know. But this patch consistently fixes a consistent problem.

**Comment by remitamine** [comment]
> Maybe the more correct solution is to change the initial request to api.nbc.com.

yes, from the output you have posted in https://github.com/rg3/youtube-dl/issues/18236#issuecomment-443537052, the request adds `page%5Bnumber%5D=1` to the api URL query, so if adding this to the iapi request(without making the api request twice) fixes the problem you explaining and does not effect downloading other videos, then i would accept the change even thought i can't reproduce the problem locally.

**Comment by tych0** [comment]
Hi, I can confirm that this patch fixes this issue for me; any chance we can re-open and merge it?

**Pull request closed without merging**
