### PR TITLE
Update pluralsight.py

### PR DESCRIPTION
**Pull request by CollinChaffin**
Regex it completely broken.  Pluralsight now changed both the order of their URL params, but also from WWW to APP subdomain.  Rewrote the regex making the sections optional to account for changing order but I am admittedly not the regex guru that some are, so by all means if anyone wants to optimize my regex feel free!  :)

### CODE REVIEW

**Comment by dstftw** [comment]
It does not change anything:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://app.pluralsight.com/training/player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-i
ntroduction&clip=0&mode=live']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.11.19
[debug] Git HEAD: 72e45e3
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
[generic] player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live: Downloading webpage
[generic] player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live: Extracting information
[debug] Invoking downloader on u'https://app.pluralsight.com/training/player?course=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-intro
duction&clip=0&mode=live'
[download] Pluralsight Player-playercourse=angularjs-get-started&author=scott-allen&name=angularjs-get-started-m1-introduction&clip=0&mode=live.unknown_video ha
s already been downloaded
[download] 100% of 74.05KiB
```
And yes, after this patch regex is completely broken.

**Comment by CollinChaffin** [comment]
Is that because it says "already downloaded? I just re-tested my regex on 2 testers and it parses correctly I have multiple courses open and use those URLs to test.

**Comment by CollinChaffin** [comment]
Oh your URL is missing author......which I am not sure is being caught by the regex.

**Comment by CollinChaffin** [comment]
Why does the generic show it parsing a URL with "author" yet the command line args show you using a URL without AUTHOR?  Can you test using a URL with author quick?

**Comment by dstftw** [comment]
It's because it does not match the URL.
>Rewrote the regex making the sections optional to account for changing order 

Grouping does not affect changing order at all, so this is noop.

**Comment by dstftw** [comment]
Both show URL **with** author.

**Comment by CollinChaffin** [comment]
Ok then what is your regex proposal?  Like I said, when you make the groups optional the order then is not important.  I am not the author of this LOL I jumped in because the author isn't fixing it are you a major author is there a reason given I have identified the URL changes that you cannot help propose a fix?

They simply changed their URL subdomain from www to app.pluralsight and changed the order of their URL params - that's it.  Now we just need to fix one regex line.  
I said I'm not a regex expert but the change they made is really easy to identify against the broken line of code.  Let me re-test the regex again quick I'm sure we can figure it out I must have missed something.

**Pull request closed without merging**
