### PR TITLE
[options] Accept quoted string across multiple lines (#9940)

### PR DESCRIPTION
**Pull request by jaimeMF**
I think there shouldn't be any downside for passing the whole file to shlex, but if there are, please tell me.

### CODE REVIEW

**Comment by yan12125** [comment]
Maybe better to add an multiline examples to ```test_compat_shlex_split()```.

**Comment by jaimeMF** [comment]
> Maybe better to add an multiline examples to test_compat_shlex_split().

Added a test in https://github.com/rg3/youtube-dl/pull/9945/commits/3a7e7ed55c3b6d0babde5740aa3a0c1979d16339.

**Comment by dstftw** [comment]
Cherry-picked, thanks.

**Comment by keybounce** [comment]
Thank you

**Pull request closed without merging**
