### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by megaminxwin**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

since i can't code for beans i figured i should help out somehow

--min-sleep-interval and --sleep-interval do the same thing, but --min-sleep-interval was not documented, so i added it and updated --max-sleep-interval's description

### CODE REVIEW

**Comment by dstftw** [comment]
1. This file is autogenerated.
2. `--min-sleep-interval` is [aliased to `--sleep-interval`](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/options.py#L528) and documented as `--sleep-interval` as it appeared first.

**Comment by megaminxwin** [comment]
Well, fair enough I guess, but why have two options that do the exact same thing? Just curious before I delete the branch.

**Comment by dstftw** [comment]
Read 2.

**Comment by megaminxwin** [comment]
...yes I gathered that, but why? Why have both of them in there? Only one is really necessary, and if only one is documented then what's the point?

**Comment by dstftw** [comment]
Because it logical to have min counterpart for symmetry.

**Pull request closed without merging**
