### PR TITLE
[CONTRIBUTING.md] Fix broken link

### PR DESCRIPTION
**Pull request by josephfrazier**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The link text was moved from README.md to CONTRIBUTING.md, but the
target wasn't updated.

### CODE REVIEW

**Comment by Starsam80** [comment]
That link isn't broken? Have you even tried clicking on it?

**Comment by josephfrazier** [comment]
No worries, it was your comment that led me to realize I botched both the commit message and PR title, as well as not noticing that the link should go to README.md. Everything should be fixed now.

**Comment by josephfrazier** [comment]
Oh, now I see that [CONTRIBUTING.md is generated programmatically](https://github.com/rg3/youtube-dl/pull/2984#issuecomment-66789271) in the [Makefile](https://github.com/rg3/youtube-dl/blob/0aacd2deb1075e0d4d4b8b23b9a65b3967a1d658/Makefile#L59-L60), which explains all the duplication. I guess [devscripts/make_contributing.py](https://github.com/rg3/youtube-dl/blob/0aacd2deb1075e0d4d4b8b23b9a65b3967a1d658/devscripts/make_contributing.py) needs to be tweaked instead? Either than or just remove the CONTRIBUTING.md stuff from README.md \*shrugs\*

**Comment by yan12125** [comment]
Detecting links is difficult. Instead, you can fix corresponding parts in ```README.md```

**Comment by yan12125** [comment]
Thanks! Now it's working

**Pull request merged**
