### PR TITLE
[youtube] More explicit player config JSON extraction (fixes #7468)

### LINKED ISSUE #7468: ValueError when downloading a video from YouTube
Downloading [this video](https://www.youtube.com/watch?v=Ms7iBXnlUO8) seems to fail:

```
$ PYTHONPATH=`pwd`  ./bin/youtube-dl --verbose --list-formats 'https://www.youtube.com/watch?v=Ms7iBXnlUO8'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://www.youtube.com/watch?v=Ms7iBXnlUO8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Git HEAD: fcd817a
[debug] Python version 2.7.9 - Linux-3.19.0-33-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ms7iBXnlUO8: Downloading webpage
Traceback (most recent call last):
  File "./bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/home/lukas/work/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/home/lukas/work/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/lukas/work/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/lukas/work/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/home/lukas/work/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/home/lukas/work/youtube-dl/youtube_dl/extractor/youtube.py", line 1080, in _real_extract
    ytplayer_config = json.loads(json_code)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 6498 (char 6497)
```

### PR DESCRIPTION
**Pull request by lalinsky**
Fixed downloads for these videos:

 - https://www.youtube.com/watch?v=Ms7iBXnlUO8
 - https://www.youtube.com/watch?v=lsguqyKfVQg

### CODE REVIEW

**Comment by dstftw** [comment]
This does not fix the actual problem. If this is intentional YouTube measure against downloading (I can't find another reasonable explanation for that) they'll just changed it to `info: {}});ytplayer}, n);}};(function(w, startTick` and it will be broken again. Instead we should correctly process quoted strings obviously not with regexes since it will cause lots of backtracking.

**Comment by dstftw** [comment]
If you suggest this as temporary "solution" then preserve both regexes keeping `;ytplayer`-one first (e.g. with `_search_regex`).

**Comment by lalinsky** [comment]
This is all user content, it's not intentional from YouTube. The last video I posted to the issue has `"{dark walk}; Loki/AC/Dishonored; collab w/Elflover21"` as the title and the `};` part confuses the regex. Obviously it would be great to have a proper JS parser, but this seems like a simple enough fix. I'm sure this kind of problem exists on many places in youtube-dl, which tries to extract JSON from HTML using regexes and it was always fixed by adding a more specific regex.

**Comment by lalinsky** [comment]
Ok, I'll switch the code to `_search_regex` and add a fallback to the original one.

**Comment by lalinsky** [comment]
Done. There was one more instance of this, so I made a new function for the extraction. Please have a look.

**Comment by dstftw** [comment]
`_search_regex` already supports list of patterns.

**Comment by lalinsky** [comment]
Oh, I didn't know that. Will change.

**Comment by dstftw** [comment]
Thanks.

**Comment by RomanStone** [comment]
Found link to this page in "src" code while trying to do `ytplayer.config` extract in php

Please let me suggest another method, 
it's written in php because I don't know how to "code" in python, but I like youtube-dl,
and want to help.

```
<?php
$VideoID = 'aj9coPGuFkM';
$file = file_get_contents('https://www.youtube.com/watch?v=' . $VideoID);


$pattern1 = '/ytplayer\.config\s*=\s*\{(.+?)\}.*/';
preg_match($pattern1, $file, $matches1);

if(!empty($matches1[0]) && strpos($matches1[0], '}') !== false) {

  //don't need it now
  $matches1 = preg_replace("/ytplayer\.config\s*=\s*/", '', $matches1[0]);
  if(!empty($matches1)) {

    // explode by ending bracket
    $js_array = explode('}', $matches1);
    unset($matches1);

    $b = '';
    foreach($js_array as $str) {
      // and reasemble sequentially
      $b .= $str . '}';
      // try to decode any string
      $out = json_decode($b, true);
      if(!empty($out)) {
        // ok found something, turn it back to json;
        $ytplayer_config = json_encode(array('ytplayer.config' => $out));
        unset($b); unset($js_array); unset($out);
        break;
      }
    }
  }
}


// Do something
if(!empty($ytplayer_config)) {
  print_r($ytplayer_config);
} else {
  echo "Failed to extract ytplayer_config";
}
?>

```

Not really nice way to extract, but it's work


Php-sandbox
http://sandbox.onlinephpfunctions.com/code/fec6f56d8d4d7d3938941ca767acfb1c428751e5

**Comment by yan12125** [comment]
@RomanStone Seems your code is what youtube-dl used in the past, which has caused problems for some videos.

**Comment by remitamine** [comment]
i think, `https://www.youtube.com/watch?v=video_id&spf=navigate` can be used as another fallback to extract ytplayer config.

**Pull request merged**
