### PR TITLE
Added --metadata option, allows the user to specify key/value pairs for encoding metadata.

### PR DESCRIPTION
**Pull request by vayalil**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ x] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by vayalil** [comment]
Added --metadata option, which allows the user to specify key/value pairs for encoding metadata, separated by equal sign. Example: --metadata "album = Movie Title artist = Various artists year = "2010"'. Also tries to capture artist information from the file description, if otherwise not available'

**Comment by vayalil** [comment]
Verified with flake8, no errors.

**Comment by dstftw** [comment]
1. Have you even tried to check your changes? It does not work since it's not wired into the code.
2. It must not do anything apart from taking user provided metadata. No extraction from description, etc.
3. Core tests are broken.
4. Duplicate of #6064.

**Comment by vayalil** [comment]
1. Sorry, it will work if you used --add-metadata option as well. Since this --metadata is just providing additional metadatas, so I thought it would be better in that way. 
2. Same as above, it will extract 'artist's name from the file description. More option should be added if required
4. But it is not still added to the main.

**Pull request closed without merging**
