### PR TITLE
Always decode the Location header

### LINKED ISSUE #9588: UnicodeWarning on Python 2 with non-ASCII URLs in HTTP redirection
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Description of your *issue*, suggested solution and other information

Originally reported at https://github.com/rg3/youtube-dl/commit/efbed08dc20c530fe428256e4dcbea4dc4423d0d#commitcomment-17573052.

On Python 2, ```Location``` header is a bytes-like object, while ```escape_url``` always return a unicode object. As a result, an ```UnicodeWarning``` may occur:
```
$ python2 -W error youtube_dl/__main__.py -vF http://lifenews.ru/news/98736
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'http://lifenews.ru/news/98736']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Git HEAD: 78d3b3e
[debug] Python version 2.7.11 - Linux-4.5.1-1-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[lifenews] 98736: Downloading page
Traceback (most recent call last):
  File "youtube_dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/__init__.py", line 421, in main
    _real_main(argv)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/__init__.py", line 411, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1736, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/lifenews.py", line 84, in _real_extract
    video_id, 'Downloading page')
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 501, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 408, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/utils.py", line 865, in http_response
    if location != location_escaped:
UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
```

### PR DESCRIPTION
**Pull request by yan12125**
Fixes #9588

@dstftw How about this? I guess using ```utf-8``` is ok as it's already done on Python 3.

### CODE REVIEW

**Comment by dstftw** [comment]
If I recall it correctly by default headers are bytestrings in python 2 that's why I leaved them undecoded. Honestly I don't remember whether unicode headers cause any problems in python 2 or not.

**Comment by yan12125** [comment]
> by default headers are bytestrings in python 2

You're right, and I encode ```Location``` back to bytes on Python 2.

**Comment by dstftw** [comment]
LGTM.

**Comment by yan12125** [comment]
Thanks for the feedback. Rebased and pushed to master.

**Pull request closed without merging**
