### PR TITLE
Change the mkv warning into an info

### PR DESCRIPTION
**Pull request by maxnordlund**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

Because there are so many issues with this warning, and that it works just
fine, this turns the warning about merging into an mkv to an informational
message.

It is also about not crying wolf when there is nothing to worry about.

### CODE REVIEW

**Comment by dstftw** [comment]
As info message it will be never noticed and there will be even more confusion about merging to mkv.

**Comment by maxnordlund** [comment]
So instead you prefer to cry wolf and teach the users to ignore warnings? That doesn't sound right to me.

**Comment by maxnordlund** [comment]
To make it clearer what I mean by crying wolf, let me explain it a bit more.

The users of this tools should be, at least a bit, familiar with the command line. As such they are most like used to warnings being a strong indication that something gone wrong. But merging the two files, which the user has requested, into one file format or another is business as usual. So by continuously emitting warnings when there is nothing wrong you teach the user to ignore _all_ warnings.

Therefore this change into an info, so that the user still sees that the file will be an mkv, but without the blinding effect.

**Comment by maxnordlund** [comment]
https://github.com/rg3/youtube-dl/issues?utf8=%E2%9C%93&q=is%3Aissue%20Requested%20formats%20are%20incompatible%20for%20merge%20and%20will%20be%20merged%20into%20mkv%20

47 hits, with a fair amount being confused because of the warning and immediately closed. Just saying that this is more confusing then the info. Please humor me for a moment, where can I find the users confused over mkv files?

**Comment by maxnordlund** [comment]
I'm trying to help, you know. What does @yan12125 say?

**Comment by yan12125** [comment]
For me two formats merge into a third one is reasonable, so there's no need to issue a warning. However I'm highly biased as I know how containers and codecs work. I don't know how others think and what's their reaction in face of MKV files.

By the way, the number 47 is inaccurate. Most issues there are not about this warning.

**Comment by maxnordlund** [comment]
Yeah, the inside of mkv vs mp4 for example is very different. But as a user I just want to watch a video, and as longs as my video player understands that format it doesn't matter. Personally I use VLC, which I think is fairly common, and it can definitely play the mkvs produced by youtube-dl.

The number is from the search query, and yes not all of those mention it explicitly as a problem. But I saw at least three that was confused and had their issues immediately closed.

**Comment by yan12125** [comment]
> as longs as my video player understands that format it doesn't matter

It's a good point. Nevertheless consensus needed.

**Pull request closed without merging**
