### PR TITLE
[WDR] add support for elefantenseite (closes #5731)

### LINKED ISSUE #5731: WDR Elefantenseite not supported
Hi all,

I wanted to download some videos from the german [Elefantenseite](http://www.wdrmaus.de/elefantenseite/), a subsite of the already supported [WDR Maus](http://www.wdrmaus.de/).

There are many single video site like [this one](http://www.wdrmaus.de/elefantenseite/#/anke_singt_auf_der_mauer_auf_der_lauer) and youtube-dl is not able to download the video. Output as follows:

```
$ youtube-dl --verbose http://www.wdrmaus.de/elefantenseite/#/anke_singt_auf_der_mauer_auf_der_lauer
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.wdrmaus.de/elefantenseite/#/anke_singt_auf_der_mauer_auf_der_lauer']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.3
[debug] Proxy map: {}
[WDRMaus] elefantenseite: Downloading webpage
ERROR: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wdr.py", line 240, in _real_extract
    r'<a href="\?startVideo=1&amp;([^"]+)"', webpage, 'parameters')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Is there an easy fix for this issue? If I can be of any further help, please let me know.

Thanks, cheers

Dennis

### PR DESCRIPTION
**Pull request by Boris-de**
The "Elefantenseite" is a special subpage on wdrmaus.de which is
entirely done in flash. But the streaming-infrastructure is the same as
on the other wdr pages, so just the way to get the jsonp url to the
metadata is different.
The site uses the url-anchor to lookup the video metadata in a full
table of content.

### CODE REVIEW

**Comment by s-timm** [comment]
Thanks for your effort! Great work! :-)

**Comment by yan12125** [comment]
@Boris-de Could you rebase this PR to current git master?

**Comment by Boris-de** [comment]
Of course, I'll have a look at it this evening.

**Comment by Boris-de** [comment]
@yan12125 PR is now rebased on top of current master. All tests still worked for me

**Comment by s-timm** [comment]
Any news on this? I tried to download a video from the elefantenseite today and it didn't work:

```
C:\Users\Timm\Downloads>youtube-dl.exe http://www.wdrmaus.de/elefantenseite/#/lieder_metcalf_bus_nr9  --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.wdrmaus.de/elefantenseite/#/lieder_metcalf_bus_nr9', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.07.11
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-80066-g566be4f, ffprobe N-80066-g566be4f, rtmpdump 2.3
[debug] Proxy map: {}
[generic] lieder_metcalf_bus_nr9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lieder_metcalf_bus_nr9: Downloading webpage
[generic] lieder_metcalf_bus_nr9: Extracting information
ERROR: Unsupported URL: http://www.wdrmaus.de/elefantenseite/#/lieder_metcalf_bus_nr9
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\YoutubeDL.py", line 681, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\extractor\generic.py", line 2282, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.wdrmaus.de/elefantenseite/#/lieder_metcalf_bus_nr9
```

**Comment by Boris-de** [comment]
I just rebased the PR on top of the current master to fix the conflicts introduced by the recent refactorings.

**Comment by sleske** [comment]
I just re-tested this code, and it still does not work. At least the URL regex is no longer correct: Video URLs for Elefantenseite no longer use a slash after the hash sign: The test URL used in this PR, http://www.wdrmaus.de/elefantenseite/#/tanja_und_andre_becherknete , now redirects to http://www.wdrmaus.de/elefantenseite/#tanja_und_andre_becherknete .

I submitted a new PR, #14598, which adds support for the current version of the Elefantenseite. I think this PR can be closed as obsolete.

**Comment by Boris-de** [comment]
withdrawn in favour of @sleske's PR #14598

**Pull request closed without merging**
