### PR TITLE
[Vimeo] Change test urls to https.

### PR DESCRIPTION
**Pull request by stepshal**
## Please follow the guide below
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _pull request_ (like that [x])
- Use _Preview_ tab to see how your _pull request_ will actually look like

---
### Before submitting a _pull request_ make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
### What is the purpose of your _pull request_?
- [x] Bug fix
- [ ] New extractor
- [ ] New feature

---
### Description of your _pull request_ and other information

Explanation of your _pull request_ in arbitrary form goes here. Please make sure the description explains the purpose and effect of your _pull request_ and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by dstftw** [comment]
Run tests before making PRs.

**Comment by stepshal** [comment]
@dstftw removed `UserIE` change.

**Comment by dstftw** [comment]
>Run tests before making PRs.

**Comment by stepshal** [comment]
@dstftw Sorry, done.

**Comment by dstftw** [comment]
You are trying to fudge the test to the code without figuring out the actual problem. That's not our way.

**Comment by stepshal** [comment]
@dstftw 
Problem with test url `'http://vimeo.com/moogaloop.swf?clip_id=2539741`
And `_VALID_URL = r'https://vimeo\.com/(?!(?:[0-9]+|watchlater)(?:$|[?#/]))(?P<name>[^/]+)(?:/videos|[#?]|$)'`
When i try to change `http` to `https` in test url, or change `https` to `https?` in second, this error show up:
```
======================================================================
FAIL: test_no_duplicates (__main__.TestAllURLsMatching)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_all_urls.py", line 98, in test_no_duplicates
    '%s should not match URL %r . That URL belongs to %s.' % (type(ie).__name__, url, tc['name']))
AssertionError: True is not false : VimeoUserIE should not match URL 'https://vimeo.com/moogaloop.swf?clip_id=2539741' . That URL belongs to Vimeo.
```

**Comment by dstftw** [comment]
I'm well aware of the problem. You should fix this initial problem not fudge the test to pass.

**Comment by stepshal** [comment]
@dstftw I removed changes to support http, because vimeo have only https now. Maybe delete question mark from `https?:`?

**Pull request closed without merging**
