### PR TITLE
[Fusion] Add new extractor

### PR DESCRIPTION
**Pull request by TRox1972**

### CODE REVIEW

**Comment by dstftw** [comment]
Do not use tabs.

**Comment by TRox1972** [comment]
@dstftw Sorry about that. New editor. Does it look good now?

**Comment by dstftw** [comment]
Squash commits.

**Comment by TRox1972** [comment]
@dstftw Squashed commits

**Comment by dstftw** [comment]
Cherry-picked in bb08101ec4a8728677ee23466608ab6aa65cbb4f, thanks.

**Pull request closed without merging**
