### PR TITLE
Youku bugfix  Download the longest video in minimum parts instead of downloading  too many segments of one video

### PR DESCRIPTION
**Pull request by Celthi**
What this pr has done:
1 Download the longest video in minimum parts instead of download the too many segments of one video.

2 Change the mp4ph3 value to 0. Last time I was wrong. And rearrange their order to look nice.

3 check the code with flake8.

### CODE REVIEW

**Comment by Celthi** [comment]
@yan12125

**Comment by yan12125** [comment]
I've done some cleanup in f133fd326bf691db389acd8871b5fc7c6d4bc978 and dbb7d7e26cfba1cb8c9f78164757f594a2a50fd1. Please adapt your modifications to the current version. Also, commit messages should be prefixed with ```[youku] ``` (note there's a space after the right bracket), like the two commits above.

**Comment by Celthi** [comment]
I have used these two method to download the videos. The difference between them is that one is low resolution with fewer parts( one parts in lots of cases), and the other is high resolution with more than one parts(3-4 minutes in every parts). Downloading the high resolution version is the preferable choice for most people.  So I will cancelled this pull request. Next time I will conform to adding [youku] (with a space). Thank you for the review.

**Comment by yan12125** [comment]
Sorry I may be misleading, but what I hope is a pull request with ```[youku] ``` commits only based on the latest commit. Feel free to do ```git push --force``` to the ```Celthi:youku_bugfix``` branch.

**Comment by Celthi** [comment]
I thought you remind me to rebase my code on your codes. So I resolve the conflicts.

**Comment by Celthi** [comment]
This pull request is not necessary, because it downloads the low resolution. So rejected it.

**Comment by yan12125** [comment]
Alright. Still thanks for providing ideas!

**Pull request closed without merging**
