### PR TITLE
[europa] Add new extractor for the European Commission video service.

### LINKED ISSUE #6528: Support for ec.europa.eu
* __URL:__ http://ec.europa.eu/avservices/video/player.cfm?ref=I107758
* __Error:__ Unsupported URL: http://ec.europa.eu/avservices/video/player.cfm?ref=I107758
* __Platform:__ openSUSE 13.1, x86_64, XFCE
* __Version:__ 2015.08.09
* __Video player:__ Custom?

```
sven@linux-etoq:~/archive> youtube-dl -v http://ec.europa.eu/avservices/video/player.cfm?ref=I107758
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://ec.europa.eu/avservices/video/player.cfm?ref=I107758']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.6 - Linux-3.11.10-29-desktop-x86_64-with-SuSE-13.1-x86_64
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] player: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player: Downloading webpage
[generic] player: Extracting information
ERROR: Unsupported URL: http://ec.europa.eu/avservices/video/player.cfm?ref=I107758
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1211, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 23, column 108
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 286, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://ec.europa.eu/avservices/video/player.cfm?ref=I107758
```

### PR DESCRIPTION
**Pull request by mcepl**
The test URL for download is

http://ec.europa.eu/avservices/video/player.cfm?ref=I107758

Fixes #6528 and #6538

### CODE REVIEW

**Comment by dstftw** [comment]
What's the point of this? It's identical to #6538.

**Comment by mcepl** [comment]
This code is actually correct then, I just tested it wrong. And tests for this particular extractor are passing.

**Comment by mcepl** [comment]
> What's the point of this? It's identical to #6538.

Yes, except it is rebased to the current master.

**Comment by dstftw** [comment]
Duplicate of #6538.

**Pull request closed without merging**
