### PR TITLE
Added UNLICENSE file

### PR DESCRIPTION
**Pull request by TRox1972**
It's recommended by http://unlicense.org to create an UNLICENSE fie with the 'license' so it'll be easier for people to find public domain projects like this one.

### CODE REVIEW

**Comment by dstftw** [comment]
It's already [created](https://github.com/rg3/youtube-dl/blob/master/LICENSE).

**Comment by TRox1972** [comment]
Yes, but it's called 'LICENSE', but public domain isn't really a license. Creating a new file called 'UNLICENSE' would maybe make it easier for people searching for public domain software projects.

**Comment by dstftw** [comment]
>make it easier for people searching for public domain software projects

How's that? Searching by license text works much better than search for filename.

**Comment by TRox1972** [comment]
From their website

> You would traditionally put the above statement into a file named COPYING or LICENSE. However, to explicitly distance yourself from the whole concept of copyright licensing, we recommend that you put your unlicensing statement in a file named UNLICENSE. Doing so also means that your project can more easily be found on e.g. GitHub or Bitbucket, enabling others to reuse your code in their own unencumbered public domain projects.

**Comment by yan12125** [comment]
> make it easier for people searching for public domain software projects

Well, I guess most people here was trying to find a video downloader but not to find a public domain project.

**Pull request closed without merging**
