### PR TITLE
fix bilibili extraction (closes #15171)

### LINKED ISSUE #15171: Error(403)on bilibili
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Hello,i try to use youtube-dl ver12.31 to download a bilibili video but i get a 403 error

youtube-dl -F http://www.bilibili.com/video/av17843872/
[BiliBili] 17843872: Downloading webpage
[BiliBili] 17843872: Downloading video info page
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

### PR DESCRIPTION
**Pull request by steebchen**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

Fix #15171 by sending http referer

### CODE REVIEW

**Comment by yan12125** [comment]
Not working fine:
```
$ python -m youtube_dl -v http://www.bilibili.com/video/av17843872/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.bilibili.com/video/av17843872/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Git HEAD: 0a5b1295b
[debug] Python version 3.6.4 (CPython) - Linux-4.9.36-x86_64-linode85-x86_64-with-arch
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 17843872: Downloading webpage
[BiliBili] 17843872: Downloading video info page
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://tx.acgvideo.com/09/17/29131709/29131709-1-16.mp4?txTime=1515328748&platform=pc&txSecret=e6ad3fbe74a0f18d8b4e6b64ce9fbe62&oi=2892522013&rate=1000&hfb=b99ffc3c5c68f00a33123bb25f882d5b'
ERROR: unable to download video data: HTTP Error 466: 
Traceback (most recent call last):
  File "/home/yen/Projects/youtube-dl/youtube_dl/YoutubeDL.py", line 1895, in process_info
    success = dl(filename, info_dict)
  File "/home/yen/Projects/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in dl
    return fd.download(name, info)
  File "/home/yen/Projects/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/home/yen/Projects/youtube-dl/youtube_dl/downloader/http.py", line 286, in real_download
    establish_connection()
  File "/home/yen/Projects/youtube-dl/youtube_dl/downloader/http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/yen/Projects/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 466: 
```

**Comment by steebchen** [comment]
Strange, the link works for me..

**Comment by yan12125** [comment]
Tried it again with another IP and it works fine. Merged - better work for some people than work for nobody.

**Comment by pilife** [comment]
this bug 466 is still existed in [youtube-dl version 2018.01.27] @yan12125 . But in my mac it  is work, and the the same version in centos, it failed.

**Comment by pilife** [comment]
When I compare the log, I found that the url extracted to download for the same video is different.

**Comment by yan12125** [comment]
> this bug 466 is still existed in [youtube-dl version 2018.01.27] @yan12125

Yes, so #15171 is still open. Please move on there for further discussions!

> this bug 466 is still existed in [youtube-dl version 2018.01.27] @yan12125

Mind sharing your findings in #15171?

**Pull request merged**
