### PR TITLE
Python2: compat_urllib_parse_unquote crashfix and use in generic to fix utf8 mangling

### PR DESCRIPTION
**Pull request by atomicdryad**
On python 2:

1: generic scrambles all utf8 encoded strings with compat_urllib_parse.unquote
   compat_urllib_parse_unquote correctly decodes the utf8, but:

2: compat_urllib_parse_unquote crashes if any 2 characters after % is not valid
   hex (which is an issue { "almost": "100%" } of the pages I've tested.

This pr makes compat_urllib_parse_unquote only decode valid hex, and makes
   generic use it instead of the broken urllib builtin

Demonstration of issue below; 

youtube-dl -f18 -o '%(playlist_title)s-%(title)s.%(ext)s' \
  https://gist.githubusercontent.com/atomicdryad/fcb97465e6060fc519e1/raw/61c14c1e3a4985471dcf56c281d24d7e781a4e0e/tsunami.html

as is: scrambled page title / playlist title

    [generic] tsunami: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] tsunami: Downloading webpage
    [generic] tsunami: Extracting information
    [download] Downloading playlist: æ´¥æ³¢
    [generic] playlist æ´¥æ³¢: Collected 1 video ids (downloading 1 of them)
    [download] Downloading video 1 of 1
    [youtube] sBkMLYUyUZg: Downloading webpage
    [youtube] sBkMLYUyUZg: Downloading video info webpage
    [youtube] sBkMLYUyUZg: Extracting video information
    [youtube] sBkMLYUyUZg: Downloading DASH manifest
    [youtube] sBkMLYUyUZg: Downloading DASH manifest
    [download] Destination: æ´¥æ³¢-TSUNAMI.mp4

with current compat_urllib_parse_unquote:

    [generic] tsunami: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] tsunami: Downloading webpage
    [generic] tsunami: Extracting information
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl", line 7, in <module>
        execfile(__file__)
      File "/md23/youtube-dl/bin/youtube-dl", line 6, in <module>
        youtube_dl.main()
      File "/md23/get/youtube-dl/youtube_dl/__init__.py", line 415, in main
        _real_main(argv)
      File "/md23/get/youtube-dl/youtube_dl/__init__.py", line 405, in _real_main
        retcode = ydl.download(all_urls)
      File "/md23/get/youtube-dl/youtube_dl/YoutubeDL.py", line 1507, in download
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
      File "/md23/get/youtube-dl/youtube_dl/YoutubeDL.py", line 657, in extract_info
        ie_result = ie.extract(url)
      File "/md23/get/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
        return self._real_extract(url)
      File "/md23/get/youtube-dl/youtube_dl/extractor/generic.py", line 1168, in _real_extract
        webpage = compat_urllib_parse_unquote(webpage)
      File "/md23/get/youtube-dl/youtube_dl/compat.py", line 99, in compat_urllib_parse_unquote
        pct_sequence += item[:2].decode('hex')
      File "/usr/lib/python2.6/encodings/hex_codec.py", line 42, in hex_decode
        output = binascii.a2b_hex(input)
    TypeError: Non-hexadecimal digit found

with corrected compat_urllib_parse_unquote

    [generic] tsunami: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] tsunami: Downloading webpage
    [generic] tsunami: Extracting information
    [download] Downloading playlist: 津波
    [generic] playlist 津波: Collected 1 video ids (downloading 1 of them)
    [download] Downloading video 1 of 1
    [youtube] sBkMLYUyUZg: Downloading webpage
    [youtube] sBkMLYUyUZg: Downloading video info webpage
    [youtube] sBkMLYUyUZg: Extracting video information
    [youtube] sBkMLYUyUZg: Downloading DASH manifest
    [youtube] sBkMLYUyUZg: Downloading DASH manifest
    [download] Destination: 津波-TSUNAMI.mp4

### CODE REVIEW

**Comment by dstftw** [comment]
Can you name an example when `compat_urllib_parse.unquote` (note dot instead of last underscore) fails? `compat_urllib_parse_unquote` has been introduced long time ago in 40b35b4 probably to workaround python 2.5 issues support for which has been dropped quite some time now. If so it can be dropped completely in favor to `compat_urllib_parse.unquote` that is used most throughout the codebase.
Could somebody shed some light on that?

**Comment by atomicdryad** [comment]
This was meant as a simple bugfix and it does work perfectly...however I decided to run bigger tests, and...yeah with or without this change the existing function is slow: 

And by slow I mean 3+ minutes to unescape a 1 mb word list, vs a second for the python3 function and the backport I'm about to commit :-O

By tests do you mean urls, or regression tests like below?

    100000 lines

    ______________________
    Test: c7fbcce95b1afd5bcbfe1a4c2d142e9b  enc-clean.txt
    Expected: 3a151daf547b00023fb41113e58ae91c  -

    0:00.28 [python3 urllib.parse.unquote] :: 103% RSSmax 97024 
    3a151daf547b00023fb41113e58ae91c  -
    __

    0:00.32 [a.py (python3 backport)] :: 98% RSSmax 80160 
    3a151daf547b00023fb41113e58ae91c  -
    __

    3:18.35 [YoutubeDL.compat.compat_urllib_parse_unquote] :: 100% RSSmax 72336 
    3a151daf547b00023fb41113e58ae91c  -

    ______________________
    Test: 394c564fb36878c49d3e8898d2182286  enc-badutf.txt
    Expected: bf45f51c1e978d8aa14370833017c12a  - (orig) bf45f51c1e978d8aa14370833017c12a  - (perl decode)

    0:01.01 [python3 urllib.parse.unquote] :: 30% RSSmax 97136 
    db322ec169e38bb134a2a9968dbd0c94  -
    __

    0:00.93 [a.py (python3 backport)] :: 34% RSSmax 80272 
    db322ec169e38bb134a2a9968dbd0c94  -
    __

    3:18.47 [YoutubeDL.compat.compat_urllib_parse_unquote] :: 99% RSSmax 74448 
    db322ec169e38bb134a2a9968dbd0c94  -

**Comment by atomicdryad** [comment]
Note 'expected' md5sum is off because unquote fitzes with more than just the quoted parts, as opposed to

def decode(str):
    return re.sub(r'%([a-fA-F0-9]{2})', lambda m: m.group(1).decode('hex'),  str)

**Comment by dstftw** [comment]
Tests similar to [these](https://github.com/rg3/youtube-dl/blob/master/test/test_utils.py#L216-L230) would be enough.

**Comment by dstftw** [comment]
Merged with some modifications. Thanks.
Do you want to be credited as one of the authors of youtube-dl? If so under what name?

**Pull request merged**
