### PR TITLE
[downloader/hls] Ask ffmpeg to quit when interrupting youtube-dl with 'Ctrl+C' (#8252)

### PR DESCRIPTION
**Pull request by jaimeMF**
Otherwise the mp4 file can't be played.

### CODE REVIEW

**Comment by yan12125** [comment]
Maybe only do that for live streams? For non-live m3u8 streams, sending 'q' before completion gives incomplete ```.mp4``` files.

**Comment by jaimeMF** [comment]
> Maybe only do that for live streams? For non-live m3u8 streams, sending 'q' before completion gives incomplete ```.mp4``` files.

But it's still named as `<something>.mp4.part`, so I don't think it's a bad thing.

**Comment by yan12125** [comment]
Oh I was wrong. Everything looks good. Go ahead and merge it.

**Comment by jaimeMF** [comment]
Cherry picked in 9d90e7de03c20b8365ffbcbb17cad58cbfbe35a5.

**Comment by dstftw** [comment]
This introduced a misleading error message on Ctrl+C, now it's `ERROR: unable to download video` instead of expected `ERROR: Interrupted by user`.
```
[hitbox:live] musify: Downloading JSON metadata
[hitbox:live] musify: Downloading metadata JSON
[download] Destination: Musify - 24_7 Music and Gaming Stream Friendly 2016-01-21 23_13-musify.mp4
ffmpeg version 2.1.3 Copyright (c) 2000-2013 the FFmpeg developers
  built on Jan 21 2014 19:01:46 with gcc 4.8.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --ena
ble-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libsp
eex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavp
ack --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
[hls,applehttp @ 000000000270b220] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'http://edge.hls.gcdn.co/hls/musify/index.m3u8?st=pvEB8E3pO_aTJtLm5-Y6pA;ci=CLTZMTqvhySBBwb2Nn66bg':
  Duration: 00:00:00.14, start: 280.638667, bitrate: 22 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 319 kb/s
Output #0, mp4, to 'file:Musify - 24_7 Music and Gaming Stream Friendly 2016-01-21 23_13-musify.mp4.part':
  Metadata:
    encoder         : Lavf55.19.104
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31, 30 fps, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 319 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  239 fps= 61 q=-1.0 Lsize=     897kB time=00:00:08.02 bitrate= 916.3kbits/s
video:575kB audio:313kB subtitle:0 global headers:0kB muxing overhead 0.974678%
Received signal 2: terminating.
ERROR: unable to download video
```

**Comment by jaimeMF** [comment]
That's strange, it show the correct message for me:
```
$ youtube-dl --ignore-config 'http://www.hitbox.tv/musify' -v --prefer-ffmpeg  -

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--ignore-config', 'http://www.hitbox.tv/musify', '-v', '--prefer-ffmpeg', '-f', '[protocol^=m3u8]']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Git HEAD: 032f232
[debug] Python version 3.5.1 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg git-2016-01-16-d7c75a5, ffprobe git-2016-01-16-d7c75a5, rtmpdump 2.4
[debug] Proxy map: {}
[hitbox:live] musify: Downloading JSON metadata
[hitbox:live] musify: Downloading metadata JSON
[debug] Invoking downloader on 'http://edge.hls.gcdn.co/hls/musify/index.m3u8?st=IKCZFqvg4Qac167cDjNUnA;ci=LUJsf983siwm8n8QX8nzCg'
[download] Destination: Musify - 24_7 Music and Gaming Stream Friendly 2016-01-22 14_31-musify.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
' -i 'http://edge.hls.gcdn.co/hls/musify/index.m3u8?st=IKCZFqvg4Qac167cDjNUnA;ci=LUJsf983siwm8n8QX8nzCg' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:Musify - 24_7 Music and Gaming Stream Friendly 2016-01-22 14_31-musify.mp4.part'
ffmpeg version git-2016-01-16-d7c75a5 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=~/homebrew/Cellar/ffmpeg/HEAD --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-librtmp --enable-vda
  libavutil      55. 13.100 / 55. 13.100
  libavcodec     57. 22.100 / 57. 22.100
  libavformat    57. 21.101 / 57. 21.101
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 25.100 /  6. 25.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://edge.hls.gcdn.co/hls/musify/index.m3u8?st=IKCZFqvg4Qac167cDjNUnA;ci=LUJsf983siwm8n8QX8nzCg':
  Duration: N/A, start: 5808.639000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 319 kb/s
[mp4 @ 0x7f993c006800] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x7f993c006800] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:Musify - 24_7 Music and Gaming Stream Friendly 2016-01-22 14_31-musify.mp4.part':
  Metadata:
    encoder         : Lavf57.21.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 319 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
^Cframe=  217 fps= 52 q=-1.0 Lsize=    2846kB time=00:00:07.26 bitrate=3210.8kbits/s speed=1.75x
video:2559kB audio:277kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.345917%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```
Can you post the `--verbose` output? (Feel free to open a new issue).

**Comment by dstftw** [comment]
@jaimeMF #8300.

**Pull request closed without merging**
