### PR TITLE
Rename CONTRIBUTING.md to url_extractor_wiki.md

### PR DESCRIPTION
**Pull request by siddht1**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by yan12125** [comment]
Why?

**Comment by yan12125** [comment]
CONTRIBUTING.md is a special filename [recognized by Github](https://help.github.com/articles/setting-guidelines-for-repository-contributors/), and AUTHORS follows [GNU convention](https://www.gnu.org/prep/maintain/html_node/Recording-Contributors.html). Could you explain those changes?

**Comment by siddht1** [comment]
it gives a wrong info , instead of contributing  it should be either developer_extractor_guide or url_extractor_wiki

contributing may actually consists of the developers i.e https://github.com/rg3/youtube-dl/blob/master/AUTHORS

authors , should be for the main coders.

**Comment by yan12125** [comment]
> it gives a wrong info , instead of contributing it should be either developer_extractor_guide or url_extractor_wiki

That file consists of two parts. First tips to report bugs, and second guidelines to write codes. Those are the two common ways to contribute

> authors , should be for the main coders.

No. "author" means those who write codes. In this repo the convention is those who have done non-trivial changes

**Comment by siddht1** [comment]
i know it, it should have actually have the part already present in readme.md
i.e  parts of developing code of  readme.md , should actually be CONTRIBUTING.md  , having youtube_dl  coding convention in all platforms and guide.

authors is more suited as developers, even your authors doesnt specify who contributed for which module and what part he/she is in this project

**Comment by siddht1** [comment]
should i also fetch the new CONTRIBUTING.md  that i belive

**Comment by yan12125** [comment]
> authors is more suited as developers, even your authors doesnt specify who contributed for which module and what part he/she is in this project

Well, as it's a small project, there are no things like "modules". Lots of people have touched almost every part in youtube-dl

**Comment by siddht1** [comment]
well i didnt do anything .  you are collaborator , developer and have definitely contributed from a particular point of time.

**Comment by siddht1** [comment]
well your first was   
 Fix 2 bugs in youtube_dl/extractor/sohu.py


also , https://github.com/rg3/youtube-dl/pull/11239   proves that I`m correct to an extent

**Comment by siddht1** [comment]
this were first meant for https://github.com/rg3/youtube-dl/issues/11234

**Comment by siddht1** [comment]
me  : `authors , should be for the main coders.`
you : `No. "author" means those who write codes. In this repo the convention is those who have done non-trivial changes`

we both are saying the same thing , by the way http://rg3.name/201408141628.html   has the actual  devs and their status

**Comment by yan12125** [comment]
> also , #11239 proves that I`m correct to an extent

Not sure what you mean. #11239 is just a technical issue

IMO there's no need to maintain another list of authors or developers as there are already quite a few excellent ones

**Pull request closed without merging**
