### PR TITLE
[extractor/common] fix dash formats sorting

### PR DESCRIPTION
**Pull request by remitamine**

### CODE REVIEW

**Comment by dstftw** [comment]
What is the rationale?

**Comment by remitamine** [comment]
every time we add an extractor that use dash format they sorted as better quality than other video formats(http, rtmp ,hls, f4m) because most of the time dash formats has more information than other formats.
so this is a general solution for sorting dash formats instead of dealing with dash sorting in every extractor that uses them.

**Comment by remitamine** [comment]
may some examples will show why this is needed.
```
youtube-dl -F https://www.facebook.com/video.php?v=957955867617029
[facebook] 957955867617029: Downloading webpage
[info] Available formats for 957955867617029:
format code                      extension  resolution note
progressive_sd_src               mp4        unknown    
progressive_sd_src_no_ratelimit  mp4        unknown    
1028350597225365ad               mp4        audio only DASH audio   21k , mp4a.40.29 (44100Hz)
177035425985288vd                mp4        240x426    DASH video  155k , avc1.4d401e, video only
474346612748657v                 mp4        360x640    DASH video  331k , avc1.64001f, video only (best)
```
```
youtube-dl -F http://plays.tv/video/569aa4145e8de99951
[PlaysTV] 569aa4145e8de99951: Downloading webpage
[PlaysTV] 569aa4145e8de99951: Downloading MPD manifest
[info] Available formats for 569aa4145e8de99951:
format code       extension  resolution note
http-360          mp4        360p       
http-480          mp4        480p       
http-720          mp4        720p       
http-720h         mp4        720p       
http-1080h        mp4        1080p      
DASH-AUDIO-192k   mp4        audio only DASH audio  196k , mp4a.40.2 (48000Hz)
DASH-VIDEO-360    mp4        640x360    DASH video  659k , avc1.64001e, 30fps, video only
DASH-VIDEO-480    mp4        852x480    DASH video  869k , avc1.64001f, 30fps, video only
DASH-VIDEO-720    mp4        1280x720   DASH video 2211k , avc1.64001f, 30fps, video only
DASH-VIDEO-720H   mp4        1280x720   DASH video 4151k , avc1.640020, 31fps, video only
DASH-VIDEO-1080H  mp4        1920x1080  DASH video 5938k , avc1.64002a, 31fps, video only (best)
```
the best is a dash video because dash formats have more metadata.
this will happen every time we add an extractor that has dash formats unless we handle it generally.

**Comment by dstftw** [comment]
I guess this can be merged.
For general sorting improvement we may also tweak the behavior of `_sort_formats` so that it will try metadata available across most of the formats first. For example, if 5 of out 10 have tbr and all of them have height, height can be considered first when sorting. This will allow to achieve plausible sorting for such cases but not 5 formats with tbr on top.

**Comment by remitamine** [comment]
> For general sorting improvement we may also tweak the behavior of _sort_formats so that it will try metadata available across most of the formats first.

this is a good idea, it will improve sorting for a lot of extractors.
and may be prefer width and height before the tbr, i remember that i read a comment by @yan12125  about difference of bitrate between mp4 and webm.

**Comment by yan12125** [comment]
> and may be prefer width and height before the tbr, i remember that i read a comment by @yan12125 about difference of bitrate between mp4 and webm.

I guess you're talking about https://github.com/rg3/youtube-dl/issues/6018#issuecomment-114008839. @haasn also mentioned something similar in #5242. @dstftw has a pull request #8125 targetting this problem.

**Pull request merged**
