### PR TITLE
Dropping support for Python 3.2 and 3.3

### LINKED ISSUE #9751: Drop Python 3.2 support
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.11.3**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

The latest pip has dropped Python 3.2 support (pypa/pip#3156) . As a result, I can't install pip:

```
$ python3.2 ~/tmp/get-pip.py --user
/tmp/tmpyhlooe/pip.zip/pip/_vendor/pkg_resources/__init__.py:80: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
Traceback (most recent call last):
  File "/home/yen/tmp/get-pip.py", line 19177, in <module>
    main()
  File "/home/yen/tmp/get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "/home/yen/tmp/get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpyhlooe/pip.zip/pip/__init__.py", line 16, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/download.py", line 36, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/utils/ui.py", line 15, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
```

Reasons for dropping:

* According to dstufft, requests by Python 3.2 clients account for less than 0.5% traffic on pypi.org
* pip does not support Python 3.2. I need pip to install nose and PyCrypto (for #8201)
* Although Ubuntu 12.04 LTS (EOL on April 2017) still ships Python 3.2, users can use Python 2.7

A last bit: re on Python 3.2 is broken.
```
$ python3.2 test/test_all_urls.py  
..F.............
======================================================================
FAIL: test_no_duplicates (__main__.TestAllURLsMatching)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_all_urls.py", line 93, in test_no_duplicates
    self.assertTrue(ie.suitable(url), '%s should match URL %r' % (type(ie).__name__, url))
AssertionError: False is not true : UnicodeBOMIE should match URL '\ufeffhttp://www.youtube.com/watch?v=BaW_jenozKc'

----------------------------------------------------------------------
Ran 16 tests in 1.708s

FAILED (failures=1)

$ python3.2
Python 3.2.6 (default, May 23 2016, 01:08:02) 
[GCC 6.1.1 20160501] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.match(r'\ufeff', '\ufeff')
>>> 
```

### PR DESCRIPTION
**Pull request by yan12125**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

There are no code changes for now. Python 3.2-specific handling can be removed later. The primary advantage is shorter testing time on Travis CI.

Closes #9751.

Checking:
* Python 3.2: only Ubuntu 12.04 ships 3.2.3 [1], and it reaches EOL on 2017-04 [2]
* Python 3.3: no major distributions/operating systems ships 3.3.x as the default ```python3``` interpreter [1].
* Python 3.4: supported unstream to 2019-03-16 [3]

[1] https://repology.org/metapackage/python3/versions
[2] http://distrowatch.com/table.php?distribution=ubuntu
[3] https://docs.python.org/devguide/#status-of-python-branches

### CODE REVIEW

**Comment by remitamine** [comment]
this commit 2cc7fcd338e8690a5c211b95fb9e0dcdc5d98ef5 can be reverted.

**Comment by hugovk** [comment]
The most obvious benefit to developer workflow is it frees up a couple of slots on the CI. 

A second is that it allows modern Python code to be written without concern for obsolete versions.

**Comment by dstftw** [comment]
>The most obvious benefit to developer workflow is it frees up a couple of slots on the CI.

It's nothing in terms of development and writing code. Core rests run in about 1 minute.

>A second is that it allows modern Python code to be written without concern for obsolete versions.

Does not apply here while 2.6 and older 2.7 are supported.

**Comment by hugovk** [comment]
And download tests run in about 20 minutes!

I propose dropping EOL 2.6 as well. That would save about an hour of CI time.

Here are pip download statistics for youtube-dl from PyPI:

```
python_version percent download_count
-------------- ------- --------------
2.7            41.8%           44,680
3.5            35.2%           37,637
3.6            19.6%           20,957
3.4            2.8%             3,025
2.6            0.3%               356
3.7            0.1%               110
3.3            0.1%                54
3.2            0.0%                 1
```

**Comment by dstftw** [comment]
Download tests are not considered important. Moreover when one changes some extractor he should run only concrete extractors not all. Thus again no real benefit.

**Comment by h1z1** [comment]
Python 2.6 is most certainly still alive and used by many.  Red Hat (and CentOS), for example.

```
$ rpm -qR youtube-dl
/usr/bin/python2.6  
config(youtube-dl) = 2017.12.10-1.el6
python(abi) = 2.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
$
```

**Comment by rautamiekka** [comment]
Ubuntu uses 2.6 as default until 18.04 LTS where it's replaced by 3.x.

14.04 LTS is due 2019-04 and 16.04 LTS 2021-04.

**Comment by yan12125** [comment]
There's currently no plan to drop Python 2.6 before 2020. This pull request is about 3.2 and 3.3.

> Ubuntu uses 2.6 as default until 18.04 LTS where it's replaced by 3.x.

@rautamiekka: could you give more details about this? (e.g. Ubuntu maintenance timeline) From Ubuntu's package repository, [14.04 comes with 2.7.5](https://packages.ubuntu.com/trusty/python) and [16.04 ships 2.7.11](https://packages.ubuntu.com/xenial/python).

**Comment by hugovk** [comment]
@rautamiekka Ubuntu 16.04 LTS (Xenial Xerus) comes with Python 3.5:

> # Python 3
>
> Python2 is not installed anymore by default on the server, cloud and the touch images, long live Python3! Python3 itself has been upgraded to the 3.5 series.
>
> If you have your own programs based on Python 2, fear not! Python 2 will continue to be available (as the python package) for the foreseeable future. However, to best support future versions of Ubuntu you should consider porting your code to Python 3. Python/3 has some advice and resources on this.



https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#Python_3

**Comment by hugovk** [comment]
Here's updated pip installs for youtube-dl from PyPI for last month, showing an even smaller share for 3.2 and 3.3 than in October:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   43.4% |         51,815 |
| 3.5            |   27.2% |         32,512 |
| 3.6            |   26.4% |         31,496 |
| 3.4            |    2.5% |          3,042 |
| 2.6            |    0.3% |            362 |
| 3.7            |    0.2% |            191 |
| 3.3            |    0.0% |             40 |
| 3.2            |    0.0% |              8 |

Source: `pypinfo --start-date -53 --end-date -23 --percent --pip --markdown youtube-dl pyversion`

**Comment by yan12125** [comment]
I rebased this branch, yet there's a new use case for Python 3.2: #15394.

**Comment by yan12125** [comment]
Alright. There's still no consensus between major developers, so I won't work on this anymore in near future.

**Comment by canamcy** [comment]
Blackberry 10 ships 3.2. I have two phones I keep ytdl updated.

**Comment by yan12125** [comment]
@canamcy: Many thanks for the info! Now there's a strong reason for keeping 3.2 support.

**Comment by vaskas** [comment]
We have been shipping youtube-dl in our little Termux-like UNIX distro (https://github.com/BerryFarm/berrymuch) for Blackberry 10 (which is still bound to Python 3.2) and have a few very happy users. Thanks for keeping the support.

**Pull request closed without merging**
