### PR TITLE
Changing 'guys' to 'people'

### PR DESCRIPTION
**Pull request by JackDanger**
Tiny doc change here!

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

Folks at Ubuntu aren't all male so calling them 'guys' is a little odd. This updates the README to change the word 'guys' to 'people'.

### CODE REVIEW

**Comment by dstftw** [comment]
Isn't `guys` gender neutral?

**Comment by JackDanger** [comment]
> Isn't guys gender neutral?

It *sometimes* is, which means it can be tricky. Most of the time it won't cause a problem but sometimes a woman will read it and feel left out. Avoiding using it when it's not necessary is a great way to prevent that moment of a woman thinking "Oh, I guess this isn't a place for me. I'll go somewhere else."  It's a little thing but I figure if it's easy to fix, maybe it's worth it?

**Comment by Hrxn** [comment]
> Isn't guys gender neutral?

Yes, it is..

Exception: *people* desperately looking to be offended.

**Comment by JackDanger** [comment]
> Exception: people desperately looking to be offended.

@Hrxn I'm sure you're a good person and you don't mean to be rude or hurtful. If you'd like to talk about this in person I'd be happy to do a Google Hangout and we can discuss it. I'd love to hear your perspective.

**Comment by Hrxn** [comment]
This is a joke, right?

**Comment by JackDanger** [comment]
@Hrxn Absolutely not. I think using gender-inclusive language is a real issue and you think it's not. We could respectfully talk it through like two humans who work in the same industry and will likely run into each other from time to time in the software community. That's a more mature response than just yelling insults at each other, yeah?

**Pull request merged**
