### PR TITLE
Add missing blank lines after class or function definition.

### PR DESCRIPTION
**Pull request by stepshal**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by dstftw** [comment]
It does not fix anything. What's the point?

**Comment by stepshal** [comment]
@dstftw pep8

**Comment by dstftw** [comment]
Latest flake8 has no complaints.

**Comment by yan12125** [comment]
It was proposed by GvR in https://github.com/PyCQA/pycodestyle/issues/400 and later implemented in https://github.com/PyCQA/pycodestyle/pull/536. This check is not included in the latest release of pycodestyle (2.0.0) yet. Personally I prefer to wait for pycodestyle 2.1 before applying this rule in youtube-dl, [which should](https://github.com/PyCQA/pycodestyle/milestone/13) [happen soon](https://github.com/PyCQA/pycodestyle/issues/573).

**Comment by stepshal** [comment]
@yan12125 @dstftw It's happened. pycodestyle 2.1.0 is in flake8.

**Comment by yan12125** [comment]
The latest flake8 (3.0.4) was not compatible with pycodestyle 2.1.0 yet (https://gitlab.com/pycqa/flake8/issues/246). The fix is landed in flake8 git-master. Debian has applied the upstream fix, too, while Arch Linux uses a wrong patch (https://bugs.archlinux.org/task/51756). I'll fix it when Arch Linux applies the correct patch.

**Pull request closed without merging**
