### PR TITLE
[openload] fixed #9706

### LINKED ISSUE #9706: openload.co hotlinking detection
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://openload.co/f/kUEfGclsU9o
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://openload.co/f/kUEfGclsU9o']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.5.1 - Linux-4.5.4-gnu-1-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] kUEfGclsU9o: Downloading webpage
[debug] Invoking downloader on 'https://openload.co/stream/famBaQI9BRQ~1465252297~2602:306::~t47S-POR?mime=true'
[download] Destination: skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4
[download] 100% of 31.86MiB in 05:26
```

---

### Description of your *issue*, suggested solution and other information

openload.co no longer seeks to allow hotlinking and will redirect you to videos of pigeons instead of the video inputted to youtube-dl. This occurs on the latest version. Happens on both links like https://openload.co/f/kUEfGclsU9o and https://openload.co/embed/kUEfGclsU9o. I'm not familiar with the way the download link is returned, but it seems a solution would involve changing the method of requesting or returning the link.

### PR DESCRIPTION
**Pull request by N1k145**
This sould fix the issue #9706

### CODE REVIEW

**Comment by N1k145** [comment]
no longer fixed they changed the code again

**Comment by sudovijay** [comment]
they didn't i quess it just both the links return pegion. even the player show pegions :bird:

**Comment by N1k145** [comment]
Have you tried it right now ? 
My Code was working for a few hours, then they changed something, when you look into the Sourcecode of the website you can guess what they changed.
I think they saw my code and changed some little thing so it's not longer working. There where no extractor for 10 days and the theoretical solution that was described in the issue still worked and no they are changeing a little bit out of the blue.

**Comment by sudovijay** [comment]
nope they didn't change anything in the code.  the script still extracting links it just pegions on both the links ! we i quess we've to wait for some time. its something with there server as i did tried through VPN and pegions there too !

**Comment by N1k145** [comment]
Thy duplicatet the equation that defines with is the correct link in the first decrypet block, my code handels just the unencypted one, after I published it they added another equation in the first decrypet block witch overrides the first one, so that's the one witch describes the correct link or at least was it like that about 2 hour ago when I tried my fix for that witch i havend published jet.

**Comment by MaeJhem** [comment]
So this is the reason why my script stopped working. lol why?

**Comment by yan12125** [comment]
Openload has changed their website and the old approach in youtube-dl gets out-dated. There's still no reliable way to download videos for the new openload.

**Comment by sudovijay** [comment]
lol all i see pigeons now :penguin:   may be they implemented ip based protection.. who knows nvm!

**Comment by keybounce** [comment]
Yea, this just affected me today as well.

```
keybounceMBP:test michael$ youtube-dl -v 'https://openload.co/f/JWAkNCWMqt8/63814-Guardians.of.the.Galaxy.S01E01.Road.to.Kn
owhere.720p.WEB-DL.x264.AAC_1457284529.mp4'
[debug] System config: []
[debug] User config: [u'--no-mtime', u'-o', u'%(title)s.%(ext)s', u'-f', u'best[ext=mp4][height=480]/bestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/best[ext=mp4][height>360][height<=480]/bestvideo[ext=mp4][height>360][height<=480]+bestaudio/best[height>360][height<=480]/bestvideo[height>360][height<=480]+bestaudio/best[ext=mp4][height>=280][height<=360]/best[height<=480]/worst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4']
[debug] Command-line args: [u'-v', u'https://openload.co/f/JWAkNCWMqt8/63814-Guardians.of.the.Galaxy.S01E01.Road.to.Knowhere.720p.WEB-DL.x264.AAC_1457284529.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.03.1
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] JWAkNCWMqt8: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/openload.py", line 112, in _real_extract
    r'return\s+"(https?://[^"]+)"', decoded, 'video URL')
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 646, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

keybounceMBP:test michael$ 
```

**Pull request closed without merging**
