### PR TITLE
"MiTele" May not have a title

### PR DESCRIPTION
**Pull request by DarkZeros**
Example episode:
http://www.mitele.es/programas-tv/cuarto-milenio/temporada-6/programa-226/

Has no title, and trying to download just gives a crash error. The error
is not there because something actually failed, but just because the
video has no title. Setting it to NO_TITLE default makes it work
properly, and only points out that it is missing in a download list.

### CODE REVIEW

**Comment by dstftw** [comment]
Title can be constructed from
```
				<h1>
					<span>Cuarto Milenio</span>
					<span>Temporada 6</span>
					<span>Programa 226</span>
				</h1>
```
Also add a test.

**Comment by DarkZeros** [comment]
Ok, I am not a Python programmer, but let me guess it out and update this commit with a proper test.

What do you mean by:

>                 <h1>
>                     <span>Cuarto Milenio</span>
>                     <span>Temporada 6</span>
>                     <span>Programa 226</span>
>                 </h1>

?

**Comment by dstftw** [comment]
This is the excerpt from HTML source near the original title that is missing for this video.
To add a test rename `_TEST` to `_TESTS` and wrap in a list (see any other extractor).

**Comment by DarkZeros** [comment]
Updated with a test and a proper default value.
Hope this changes are OK, I tested them myself.

It is very easy to develop here!
I may add another site that is not supported now that I know how.

**Comment by dstftw** [comment]
I would prefer extracting it from place I've pointed out. Also squash commits when done.

**Pull request closed without merging**
