### PR TITLE
[extractor/external:ffmpegfd] Add FFmpegFD(fixes #622)

### LINKED ISSUE #622: Download range
Hi,

Is there any way to implement a download range? To download starting from 1m 30 to 1m 50?

Thanks

### PR DESCRIPTION
**Pull request by remitamine**
replace old downloaders with a unified ffmpeg downloader:
- replace old HlsFD and RtspFD(based on mplayer and mpv)
- add basic support for download range

### CODE REVIEW

**Comment by dstftw** [comment]
Fails to run when no ffmpeg in `PATH`:
```
> py34yt http://www.twitch.tv/riotgames/v/6528877?t=5m10s -v
Traceback (most recent call last):
  File "C:\python\python343\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python\python343\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Dev\git\youtube-dl\master\youtube_dl\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Dev\git\youtube-dl\master\youtube_dl\__init__.py", line 411, in main
    _real_main(argv)
  File "C:\Dev\git\youtube-dl\master\youtube_dl\__init__.py", line 57, in _real_main
    parser, opts, args = parseOpts(argv)
  File "C:\Dev\git\youtube-dl\master\youtube_dl\options.py", line 427, in parseOpts
    'Currently supports %s' % ','.join(list_external_downloaders()))
  File "C:\Dev\git\youtube-dl\master\youtube_dl\downloader\external.py", line 212, in list_external_downloaders
    return sorted(_BY_NAME.keys())
TypeError: unorderable types: str() < NoneType()
```

**Comment by remitamine** [comment]
i think this should fix the problem:
```diff
diff --git a/youtube_dl/downloader/external.py b/youtube_dl/downloader/external.py
index 13a91b4..bb43677 100644
--- a/youtube_dl/downloader/external.py
+++ b/youtube_dl/downloader/external.py
@@ -147,10 +147,6 @@ class FFmpegFD(ExternalFD):
     def supports(cls, info_dict):
         return info_dict['protocol'] in ('http', 'https', 'ftp', 'ftps', 'm3u8', 'rtsp', 'rtmp', 'mms')
 
-    @classmethod
-    def get_basename(cls):
-        return FFmpegPostProcessor().basename
-
     def _call_downloader(self, tmpfilename, info_dict):
         url = info_dict['url']
         ffpp = FFmpegPostProcessor(downloader=self)
@@ -201,6 +197,10 @@ class FFmpegFD(ExternalFD):
             raise
         return retval
 
+
+class AVconvFD(FFmpegFD):
+    pass
+
 _BY_NAME = dict(
     (klass.get_basename(), klass)
     for name, klass in globals().items()
```

**Comment by remitamine** [comment]
the commit message is wrong it should be [downloader/external] not [extractor/external] i will create another PR with the right commit message.
if @dstftw can confirm if the creating a seperate class for avconv fixes so i can integrate it when i create a new PR.

**Comment by dstftw** [comment]
It does not fail with this patch.

**Pull request closed without merging**
