### PR TITLE
Added support for mpv if mplayer is not available (new version)

### PR DESCRIPTION
**Pull request by mrkrossxdx**

### CODE REVIEW

**Comment by dstftw** [comment]
Download is not interruptible by `Ctrl+C` when using mpv.

**Comment by mrkrossxdx** [comment]
What OS? ctrl+c works fine here on Arch Linux (tested on both mpv 0.8.3 and 0.9.0), maybe is a bug that affect only some platforms.

**Comment by dstftw** [comment]
Windows-2003Server-5.2.3790-SP2 and Windows-7-6.1.7601-SP1 with [these binaries](http://mpv.srsfckn.biz/).

**Comment by dstftw** [comment]
Works fine under ubuntu. Turns out to be a windows/these particular binaries issue.

**Comment by dstftw** [comment]
Thanks.

**Pull request merged**
