### PR TITLE
[wat] extract m3u8 formats instead of f4m formats(fixes #6678)

### LINKED ISSUE #6678: TF1 broken again
The following URL on TF1 replay does not work:
http://www.tf1.fr/tf1/mentalist/videos/replay-mentalist-episode-1-saison-07-de-nuages-a-l-horizon.html

With the following quick-and-dirty patch:

```
diff --git a/youtube_dl/extractor/tf1.py b/youtube_dl/extractor/tf1.py
index 3a68eaa..35899dc 100644
--- a/youtube_dl/extractor/tf1.py
+++ b/youtube_dl/extractor/tf1.py
@@ -6,7 +6,7 @@ from .common import InfoExtractor
 
 class TF1IE(InfoExtractor):
     """TF1 uses the wat.tv player."""
-    _VALID_URL = r'http://(?:(?:videos|www|lci)\.tf1|www\.tfou)\.fr/.*?-(?P<id>\d+)(?:-\d+)?\.html'
+    _VALID_URL = r'http://(?:(?:videos|www|lci)\.tf1|www\.tfou)\.fr/.*?(?:-(?P<id>\d+)(?:-\d+)?)?\.html'
     _TESTS = [{
         'url': 'http://videos.tf1.fr/auto-moto/citroen-grand-c4-picasso-2013-presentation-officielle-8062060.html',
         'info_dict': {
diff --git a/youtube_dl/extractor/wat.py b/youtube_dl/extractor/wat.py
index affcc52..cf4003b 100644
--- a/youtube_dl/extractor/wat.py
+++ b/youtube_dl/extractor/wat.py
@@ -12,7 +12,7 @@ from ..utils import (
 
 
 class WatIE(InfoExtractor):
-    _VALID_URL = r'http://www\.wat\.tv/video/(?P<display_id>.*)-(?P<short_id>.*?)_.*?\.html'
+    _VALID_URL = r'http://(?:www\.wat\.tv|wat\.replay\.tf1\.fr)/video/(?P<display_id>.*)-(?P<short_id>.*?)_.*?\.html'
     IE_NAME = 'wat.tv'
     _TESTS = [
         {
```

… I can get further, but it stops with:

```
[TF1] None: Downloading webpage
[TF1] Downloading embed player page
[TF1] Downloading JSON metadata
[wat.tv] replay-mentalist-episode-saison: Downloading webpage
[wat.tv] 12724203: Downloading JSON metadata
[wat.tv] 12724203: Downloading server time
[wat.tv] 12724203: Downloading SD video URL
[wat.tv] 12724203: Downloading server time
[wat.tv] 12724203: Downloading HD video URL
[f4m] Downloading f4m manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

Regards,

-- 
  Nicolas George

### PR DESCRIPTION
**Pull request by remitamine**
- sometimes f4m fragments are protected with Akamai Player Verification Token
https://github.com/rg3/youtube-dl/issues/6678#issuecomment-170147085
- sometimes they fail with 403 while the m3u8 formats works
- m3u8 manifest contain more formats

some of hls manifest are encrypted with AES-128(http://www.tf1.fr/tmc/gotham/videos/secrets-de-tournage-de-gotham.html) so the extractor will use ffmpeg for downloading but while the video is downloading ffmpeg generate a lot warning about the timestamp:
```
[mpegts @ 0x55e4522a1da0] Invalid timestamps stream=1, pts=10587600, dts=10591200, size=5922
[mpegts @ 0x55e4522a1da0] Invalid timestamps stream=1, pts=10591200, dts=10594800, size=2449
[hls,applehttp @ 0x55e45229ab80] Invalid timestamps stream=1, pts=10587600, dts=10591200, size=5922
[mp4 @ 0x55e452691d00] Invalid DTS: 10501200 PTS: 10497600 in output stream 0:0, replacing by guess
[hls,applehttp @ 0x55e45229ab80] Invalid timestamps stream=1, pts=10591200, dts=10594800, size=2449
[mp4 @ 0x55e452691d00] Invalid DTS: 10504800 PTS: 10501200 in output stream 0:0, replacing by guess
[mpegts @ 0x55e4522a1da0] Invalid timestamps stream=1, pts=10598400, dts=10602000, size=3903
```
i don't know if they affect the result file or not?

### CODE REVIEW

**Comment by yan12125** [comment]
> - sometimes f4m fragments are protected with Akamai Player Verification Token
- sometimes they fail with 403 while the m3u8 formats works

Not looking into details as provided examples are either 404 or geo-restricted. I guess such problems can be detected via ```_check_formats()``` or in ```_extract_f4m_formats()```?

**Comment by remitamine** [comment]
> Not looking into details as provided examples are either 404 or geo-restricted. I guess such problems can be detected via _check_formats() or in _extract_f4m_formats()?

`_extract_f4m_formats()` can't detect the Akamai Player Verification Token.
i already proposed to skip f4m manifest with Akamai Player Verification Token in #6408.

**Comment by remitamine** [comment]
forget to say, 720p format is only available using m3u8 manifest(the HD format is 540p).

**Comment by remitamine** [comment]
there is way to extract all the qualities in http, f4m, m3u8, i will work on extracting them later.

**Pull request closed without merging**
