### PR TITLE
[UniversalMusicService] Added new Extractor

### PR DESCRIPTION
**Pull request by flatt3rn**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Regarding this Issue https://github.com/rg3/youtube-dl/issues/11582 i added an extractor for this page.
I tried a lot of videos and they all work fine. 
Here are some 
http://www.universal-music.de/kerstin-ott/videos/detail/video:407891/scheissmelodie
http://www.universal-music.de/lady-gaga/videos/detail/video:422932/million-reasons
If the player open in the bottom of the window. You have to close it with the x else the url is not the right one.
But there is a problem with the test download. Using the --test option does not work. It downloads the full video. So i cutted the 10241 bytes with a python script and the md5 hash should be right as well.

### CODE REVIEW

**Comment by dstftw** [comment]
See another PRs' reviews and fix all similar issues mentioned.

**Comment by kamenn0** [comment]
hi dstftw. i see you added the extractor for universal-music.de. though it was not yet implemented into the build, could you please let me know what were your results? are there any available formats other than 640x360 and 1024x576 we already know. specifically, i'm intersted in hd.
thanks.

**Comment by flatt3rn** [comment]
Sry i was a little busy the last days. If i remember correctly your videos is not there in a better quality. But there is an option for some other videos.
There are numbers what are related to a specific quality
686: 640x360
836: 1024x576
940: 1920x1080
867: 483x272
I got them by testing all numbers from 600 to 1000 but its different from video to video
I have to look if i implement an auto selection to the best video, but i dont know what issues i should fix. Just an error prevention if the webpage is not avaible?

**Comment by kamenn0** [comment]
thanks flatt3rn. again mixed up the author of extractor.
so sad there is no hd for my video.

**Pull request closed without merging**
