### PR TITLE
Update pluralsight.py

### PR DESCRIPTION
**Pull request by CollinChaffin**
Fixed regex line

### CODE REVIEW

**Comment by CollinChaffin** [comment]
Missed the order issue should be fixed now

**Comment by CollinChaffin** [comment]
Re-tested on pythex to verify matching my open courses but I do not know how with a windows system to apply this patch to test it

**Comment by dstftw** [comment]
As already mentioned you rely on arguments order. Fixed properly in 71bd93b89c667b7ca852b3a536dd771da7b67f67.

**Comment by CollinChaffin** [comment]
Ok thanks how can I test run now with patch  71bd93b to see it work?  I'm not a Python programmer so the regex was my focus.  I see the change you made and it makes sense now looking at it again.  Thanks!

**Comment by dstftw** [comment]
Just follow the [developer instructions](https://github.com/rg3/youtube-dl#developer-instructions).

**Comment by CollinChaffin** [comment]
Ok thanks.  I have not used the compat_urlparse but seeing it now you're right definitely makes perfect sense!

**Comment by CollinChaffin** [comment]
Unfortunately the developer instructions don't help with running python.py on windows.  I have always gotten this error when following the directions to simply grab the entire dist and run "python youtube-dl.py":

C:\>python YoutubeDL.py
Traceback (most recent call last):
  File "YoutubeDL.py", line 30, in <module>
    from .compat import (
SystemError: Parent module '' not loaded, cannot perform relative import

I would love to be able to pull it down and test but can never seem to get this to work on windows and haven't had time to spin up a linux box just to test it.  Any ideas why python.exe on windows won't run it?

**Comment by dstftw** [comment]
Did you read it at all? Quote:
>To run youtube-dl as a developer, you don't need to build anything either. Simply execute
>python -m youtube_dl

**Comment by CollinChaffin** [comment]
Yes I did, when I add the -m I get:

C:\>python -m YoutubeDL
Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\You
tubeDL.py", line 30, in <module>
    from .compat import (
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by dstftw** [comment]
>python -m **youtube_dl**

**youtube_dl**, not YoutubeDL or YoutubeDL.py.

**Comment by CollinChaffin** [comment]
Ok so there is an install then for the module to be recognized above pulling down the git distribution and unzipping it?  

C:\Data\Downloads\youtube-dl-71bd93b89c667b7ca852b3a536dd771da7b67f67\youtube_dl>python -m youtube_dl
C:\Program Files\Python 3.5\python.exe: No module named youtube_dl

What am I missing?  Thanks for the help!

**Comment by CollinChaffin** [comment]
Ahh strike that lol I'm braindead tonight.....had to back out into the root dir :)

**Comment by CollinChaffin** [comment]
Interesting though, it parses correctly but now gives me the following were you able to get a video successfully after your code fix?

C:\Data\Downloads\youtube-dl-71bd93b89c667b7ca852b3a536dd771da7b67f67>python -m youtube_dl "
http://app.pluralsight.com/training/player?course=administrating-office-365-identities-70-34
6&author=jeff-adkin&name=administrating-office-365-identities-70-346-m4&clip=0&mode=live" --
username XX --password XX --verbose
[debug] System config: []
[debug] User config: ['--continue', '--ignore-errors', '--no-overwrites', '-f', 'best', '--o
utput', '%(upload_date)s_%(height)sP_%(title)s.%(ext)s']
[debug] Command-line args: ['http://app.pluralsight.com/training/player?course=administratin
g-office-365-identities-70-346&author=jeff-adkin&name=administrating-office-365-identities-7
0-346-m4&clip=0&mode=live', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.19
[debug] Python version 3.5.0 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f
[debug] Proxy map: {}
[pluralsight] Downloading login page
[pluralsight] Logging in as XX
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading webpage
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading webm-high URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-low URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-medium URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-high URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure
 you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Data\Downloads\youtube-dl-71bd93b89c667b7ca852b3a536dd771da7b67f67\youtube_dl\You
tubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "C:\Data\Downloads\youtube-dl-71bd93b89c667b7ca852b3a536dd771da7b67f67\youtube_dl\ext
ractor\common.py", line 290, in extract
    return self._real_extract(url)
  File "C:\Data\Downloads\youtube-dl-71bd93b89c667b7ca852b3a536dd771da7b67f67\youtube_dl\ext
ractor\pluralsight.py", line 155, in _real_extract
    self._sort_formats(formats)
  File "C:\Data\Downloads\youtube-dl-71bd93b89c667b7ca852b3a536dd771da7b67f67\youtube_dl\ext
ractor\common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update
on how to update. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

**Comment by dstftw** [comment]
There are more commits since 71bd93b.

**Comment by CollinChaffin** [comment]
Ahh you're quick didn't see you committed more changes to this extractor!  Nice :)

**Comment by CollinChaffin** [comment]
Hmm pulled master then even went to  a5cd0eb which looks like latest you committed and same bad request error.  Other extractors working great via same python.exe calling method seems to only be the Pluralsight URL I have open playing.  Let me try some other PS urls.

**Comment by dstftw** [comment]
Well, can you watch it in browser in the first place?

**Comment by CollinChaffin** [comment]
Yep have 2 courses open playing in both Chrome and IE.  Here's one URL:

http://app.pluralsight.com/training/player?course=windows-server-2012-70-414-identity-access&author=greg-shields&name=windows-server-2012-70-414-identity-access-m005&clip=0&mode=live

That's 2nd I've tried also logs in with creds fine, but when parsing videos returns the 400 bad requests.

[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading webpage
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading webm-high URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-low URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-medium URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-high URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure
 you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Data\Downloads\youtube-dl-a5cd0eb8a4f2661cfe4863e958172d8f8f42d0f1\youtube_dl\You
tubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "C:\Data\Downloads\youtube-dl-a5cd0eb8a4f2661cfe4863e958172d8f8f42d0f1\youtube_dl\ext
ractor\common.py", line 290, in extract
    return self._real_extract(url)
  File "C:\Data\Downloads\youtube-dl-a5cd0eb8a4f2661cfe4863e958172d8f8f42d0f1\youtube_dl\ext
ractor\pluralsight.py", line 159, in _real_extract
    self._sort_formats(formats)
  File "C:\Data\Downloads\youtube-dl-a5cd0eb8a4f2661cfe4863e958172d8f8f42d0f1\youtube_dl\ext
ractor\common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update
on how to update. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

**Comment by dstftw** [comment]
I only have a free account that works fine with this free course https://www.pluralsight.com/courses/angularjs-get-started.

**Comment by CollinChaffin** [comment]
Crap is there a way I can better debug why it's failing?  I've tried 4 now it accepts my login (or appears to does not throw any login error) but then the 400 only for the video formats after saying retrieving page so it seems to be getting a response just perhaps not parsing it correctly would not be surprise if PS changed the return page given their other changes.  Let me know how I can help!

**Comment by dstftw** [comment]
Ideally, one should provide account credentials to one of the developers to reverse engineer browsers behavior. Or reverse engineer oneself and submit PR.

**Comment by CollinChaffin** [comment]
Sorry I finally fell asleep last night have 2 babies so have to catch it when I can.  So should I try to set up some technet free login for you or is that what you already are using to test?

**Comment by dstftw** [comment]
I've a technet account registered according to https://github.com/rg3/youtube-dl/issues/6090#issuecomment-120706624, but I'm unable to view any of the courses claimed available for me.

**Comment by CollinChaffin** [comment]
Hey after some sleep I just did something obvious for a test - provided an incorrect user/pass and you know what, the output is exactly the same!  Also, I see you added the option to run without logging in to PS now so I tried that as well with the exact same verbose output of 400 bad request......so now I wonder if it does boil down to this being a paid video and not logging in properly.  Does the username/pass have to be surrounded in quotes?  I wonder with a ! in my pwd if that is also maybe not being escaped properly I'll try to look at that code quick too but wanted you to know I would expect diff result with a bad password or no login when one is required and that those produce the same output.

**Comment by CollinChaffin** [comment]
One thing I notice is that in the code the _LOGIN_URL = 'https://www.pluralsight.com/id/' but they also redirect now to 'https://app.pluralsight.com/id/'.

**Comment by CollinChaffin** [comment]
So I think that redirect when YDL attempts to post the login may be failing hence the 400 because the request is then not via a logged in user.  Let me try to update it locally and test it now with the _LOGIN_URL updated.

**Comment by CollinChaffin** [comment]
Yep that's definitely an issue when I try it locally with the update it now immediately returns bad username/password so I am troubleshooting that and I think I'll change my pwd and remove the exclamation mark to see even though I see it is being utf-8 encoded.

**Comment by CollinChaffin** [comment]
Nevermind looks like I changed the pwd already late last night.  It's working!  You just need to change that _LOGIN_URL to the new URL and commit and we are golden!

**Comment by CollinChaffin** [comment]
One last question even though it now successfully downloads the webm file and logs in successfully, I do see the following for the other formats and looking with the browser it actually does appear these other formats are available.  I guess given the download success I glossed over as siimply unvailable formats but now see it's throwing a HTTP 429 (too many tries).  Just wanted your opinion since they obviously are taking these actions to break YDL if this looks like there may still be an issue or if this is normal? 

[pluralsight] Downloading login page
[pluralsight] Logging in as cchaffin@my.wctc.edu
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading webpage
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading webm-high URL
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-low URL
WARNING: Unable to download webpage: HTTP Error 429:
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-medium URL
WARNING: Unable to download webpage: HTTP Error 429:
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-high URL
WARNING: Unable to download webpage: HTTP Error 429:
[info] Available formats for windows-server-2012-70-414-identity-access-m005-001:
format code  extension  resolution note
webm-high    webm       1024x768

**Comment by dstftw** [comment]
`--sleep-interval` may help.

**Comment by CollinChaffin** [comment]
Wanted your opinion on this it is throwing these warnings on the other formats it downloads only the webm file but I hadn't noticed the HTTP 429 (too many retries) before.  Do we need to be worried the browser does list a low/med/high that seem to be MP4 so just thought I'd ask before we totally close this since PS is obviously taking steps to prevent YDL from downloading.  This is when I just run with -F to get formats - Thoughts?

[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading webpage
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading webm-high URL
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-low URL
WARNING: Unable to download webpage: HTTP Error 429:
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-medium URL
WARNING: Unable to download webpage: HTTP Error 429:
[pluralsight] windows-server-2012-70-414-identity-access-m005-0: Downloading mp4-high URL
WARNING: Unable to download webpage: HTTP Error 429:
[info] Available formats for windows-server-2012-70-414-identity-access-m005-001:
format code  extension  resolution note
webm-high    webm       1024x768

**Comment by CollinChaffin** [comment]
Ahh ok do you have a recommendation on what to set it to?

**Comment by dstftw** [comment]
There is already a PR (#6989) implementing forced sleep interval in order to avoid throttling and banned accounts. However I can't check whether it has any impact since mine is apparently banned. You can try it to see if it prevents 429's for you.

**Comment by CollinChaffin** [comment]
Yea reading that I'm confused it looks like the sleep interval is between downloads - this needs a sleep between each request just for the formats, right?  When I look at the output, that's a single run and sleep would sleep <between> multiple runs, right?

I don't want to get banned so does it boil down to if you run this as a paid user every time will generate 429's for each video just to determine the formats and it only takes a few runs to get permanently banned?   I really hope not.  Are you in the works for trying to add a sleep for each actual http get for retrieving formats and is that a different open issue # I can track and help troubleshoot or is it just #6989?

**Comment by CollinChaffin** [comment]
I do see someone forked and added the following is this what you're referring to:

 # #6989: sleep 3 seconds to avoid 429 errors.
+                # should help with #6842.
+                self._sleep(3, display_id)

Doesn't look like that got accepted back in though.

**Comment by dstftw** [comment]
There is no way to tell where sleep is required it's just a heuristic. I don't think they'll ban paid accounts, but looks like they do ban free ones. There is no such a thing as *sleep-before-each-http-request* and not likely to be implemented.

**Comment by dstftw** [comment]
It was not accepted since nobody has not banned account to test whether this patch has actually any positive impact or not.

**Comment by CollinChaffin** [comment]
Ok let me test it then I'll let you know!

**Comment by CollinChaffin** [comment]
I can confirm it works!

[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading webpage
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading webm-high URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-low URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-medium URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-high URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[info] Available formats for administrating-office-365-identities-70-346-m4-01:
format code  extension  resolution note
mp4-low      mp4        640x480
mp4-medium   mp4        848x640
webm-high    webm       1024x768
mp4-high     mp4        1024x768   (best)

**Comment by CollinChaffin** [comment]
That was with a -F to list formats now I'll download the MP4 high to test:

[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading webpage
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading webm-high URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-low URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-medium URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[pluralsight] administrating-office-365-identities-70-346-m4-0: Downloading mp4-high URL
[pluralsight] administrating-office-365-identities-70-346-m4-0: Waiting for 3 seconds
[download] Destination: NA_768P_Managing Identities Using DirSync - Introduction.mp4
[download] 100% of 5.19MiB in 00:00

Success!

**Comment by CollinChaffin** [comment]
I added the above back to the actual open issue to help track it

**Comment by CollinChaffin** [comment]
So i'm not sure are there any other reasons you wouldn't want to add that 3 second delay in between each request specific to Pluralsight and commit it?

I've run a bunch more videos and can't make it fail so I think it's good!

**Comment by CollinChaffin** [comment]
Currently pulling down entire courses with many vids and with the 3sec delay it's been perfect!

**Comment by dstftw** [comment]
Can you also check whether `--sleep-interval` set to some value without 3sec delay between each HTTP request leads to 429's or not?

**Comment by CollinChaffin** [comment]
Yes it does.  The --sleep-interval doesn't prevent the 429's because they are generated PER request, and the sleep interval is <between> each full video request.  The banning appears to be intra-request, not inter-request which the normal sleep-interval could prevent.

I do wonder if considering PS is taking action to prevent this to perhaps randomize maybe between a 3-5 sec intra-request HTTP request, rather than the current fix of a static 3 seconds?  Thoughts?  I only mention because random is obviosly harder for them to catch in logs, and I personally don't see a significant different in waiting a total of up to 20 seconds to pull/verify the 4 possible formats vs current 12 seconds added with our 3 second fix.

**Comment by CollinChaffin** [comment]
It's funny they are spending so much effort to kill members downloading what they legitimately have access to considering their buffering has always been SO bad that the courses are almost unwatchable most of the time, hence the darn need for YTD to download them to cache them and make them watchable to begin with.

**Comment by CollinChaffin** [comment]
Unbelievable so looks like even though everything is working properly they must simply be flagging any sequential file access that the sleep-interval would apparently need to be HUGE to allow for watching each video who knows what they flagged it as.  Looks like my account is now banned I'll contact them and see what they say total BS.

**Comment by CollinChaffin** [comment]
Scratch last comment I just deleted I wonder if they are either doing maintenance, or have a timer set.  I continually was getting server access denied after logging in hitting the courses in any way, now it suddenly is working again.  I'm going to keep testing and let you know like I said no errors everything looks good but I do recommend we consider randomizing the intra per video http hard-coded delay, then suggest to folks they do add the --sleep-interval for inter-requests and experiment with that delay (which I'm doing right now myself).

**Comment by CollinChaffin** [comment]
Well maybe I am banned I can get to the TOC now but not the actual videos.  I'll give it a bit to verify whether they are doing something or it's a ban.  I'd be surprised since I didn't get that many 429's last night and after the fix today all downloads were error free.

**Comment by dstftw** [comment]
I've cherry-picked #6989 and randomized sleep interval in 38eb2968abce9078f28904046b8e26b0d87ada61. Thanks for testing.

**Comment by CollinChaffin** [comment]
Got an email from them definitely based on IP ADDRESS so we need to STRONGLY encourage in any docs that for this extractor folks force a big delay (between videos) but refers to "in the realm of a request every 10-30 seconds for a prolonged period of time".

So I'm hoping that was maybe my prior 429's that caught up with me, and that our 3-5 sec delay simply to get possible video types can't be the issue.  Do you agree?  Doesn't a legit browser pull for each video have to get all the possible video sizes too?  If not, jesus if it's the top of that # at 30 seconds you'd almost have to slow down the per-vid requests to be mult minutes each to simply get the 4 possible video sizes which would be absurd.

**Comment by CollinChaffin** [comment]
And no prob I miss the dev stuff I need to learn Python I started over 25 yrs ago with C++ and then VB now do a lot of Powershell and some C# but more on infrastructure side but really want to ramp back up on the development side.  You've done so much with this app and I've been using it so long that this is least I can do to help!

**Comment by dstftw** [comment]
I've made a little optimization in 4c57b4853d8c1b41d729314e316cc1b83129ea18. Now until explicitly listing formats with `-F` only single format (i.e. ViewClip call) will be requested per video. So there will be no sequential calls to ViewClip at all making it harder to track down youtube-dl. I guess this approach should not lead to any problems since one can easily reproduce this by hand just clicking each video sequentially, so banning for this would be insane.

**Comment by CollinChaffin** [comment]
Nice!

**Pull request closed without merging**
