### PR TITLE
Voissa new extractor

### PR DESCRIPTION
**Pull request by tiburce**
Add support  for this site with needed corrections
I learn git ... sorry for my fist commit and pull request erased by error.

Voissa site lag sometimes , but the script work well

### CODE REVIEW

**Comment by tiburce** [comment]
I have testing again the script and there is no problem, i don't understand why travis test fail

**Comment by TomGijselinck** [comment]
@tiburce To view the cause of the travis build failure, view the details of the Travis CI build. There you can check whether or not your test caused the build failure. As a side note, all builds are failing because some tests do not pass. So it's possible that your tests pass, but the build fails.

**Comment by tiburce** [comment]
I've see that , but my test run and the travis test for this extractor fail.

**Comment by yan12125** [comment]
Since #8497 landed, please move changes in ```youtube_dl/extractors/__init__.py``` to ```youtube_dl/extractors/extractors.py```. Check step 5 of the new [developer instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#adding-support-for-a-new-site) for more information.

**Pull request closed without merging**
