### PR TITLE
[extractor/generic] Support relative URIs in _parse_xspf

### PR DESCRIPTION
**Pull request by wiiaboo**
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [X] Improvement

---

XSPF playlists can have relative URIs in `<location>` as well as absolute URIs.

### CODE REVIEW

**Comment by dstftw** [comment]
Add a [test](https://github.com/rg3/youtube-dl/blob/master/test/test_InfoExtractor.py#L180).

**Comment by wiiaboo** [comment]
Like this?

**Comment by dstftw** [comment]
Is there a concrete example URL?

**Comment by wiiaboo** [comment]
No, I've never seen xspf on the wild. I just use it a lot with foobar2000's foo_xspf export and it's painful to have to keep replacing relative paths with absolute URLs, even though it's perfectly valid spec-wise.

**Comment by wiiaboo** [comment]
There's a lot of them in http://dir.xiph.org/, but they're all single track and use absolute URL.

**Comment by wiiaboo** [comment]
@dstftw anything else?

**Pull request closed without merging**
