### PR TITLE
Add lecture number to Udemy template output example

### PR DESCRIPTION
**Pull request by oldo**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Add `%(playlist_index)s` to the Udemy output template example in README.md so that all the downloaded lectures will be listed in correct order rather than alphabetical order

### CODE REVIEW

**Comment by dstftw** [comment]
I don't see much sense since one may not want lecture index in filename. It's impossible to cover all variants with examples. Who need something specific should read documentation.

**Comment by oldo** [comment]
Anybody who is downloading an entire Udemy course would want their lectures to be in order. I could not find anything in the documentation about Udemy specific output template tags aside from the example given in README.md - perhaps I didn't look hard enough?

**Comment by dstftw** [comment]
There are no per extractor specific placeholders, all of them are generic. `playlist_index` is documented. Obviously you didn't look hard or didn't at all.

**Comment by vesper8** [comment]
@oldo you are absolutely correct! anyone downloading an entire course.. with dozens of lectures and hundreds of videos, would want their lessons labeled and ordered! thank you for posting this, I had just begun downloading a course I just bought and saw the need to add this format and found it quickly thanks to your issue

**Pull request closed without merging**
