### PR TITLE
Update iqiyi.py

### PR DESCRIPTION
**Pull request by gam2046**
Fix part of the address can not be resolved.
eg:
http://www.iqiyi.com/w_19rt6o8t9p.html
http://www.iqiyi.com/a_19rrhbc6kt.html

### CODE REVIEW

**Comment by yan12125** [comment]
Please add test cases with ```'only_matching': True``` to ```_TESTS```.

**Comment by yan12125** [comment]
Also it's better to use:
```
r'http://(?:www\.)iqiyi\.com/(?:v|w|a)_[^.]+\.html'
```
Sorry I didn't correct the regex in [the earlier commit](https://github.com/rg3/youtube-dl/commit/865ab62f43eb94a9f4f757a464df147e983cb439).

**Comment by gam2046** [comment]
`r'http://(?:www\.)iqiyi\.com/(?:v|w|a)_[^.]+\.html'` is correct, but I'm not sure if there are other forms of URL.And now iqiyi.com was changed.

**Comment by yan12125** [comment]
Did you mean #7896? I've updated ```iqiyi.py``` with the latest key.

**Comment by gam2046** [comment]
Yes, on the one hand is the key has failed, on the other hand, I think [the earlier commit][link1] will be better. Like `http://(?:www\.)iqiyi.com/.+?\.html`

Even the URL may be like this `http://yule.iqiyi.com/pcb.html`, so if you only need to check the URL of the host name?

Regular expressions may be like this `http://[^.]+?\.iqiyi.com/.+?\.html`

[link1]:https://github.com/rg3/youtube-dl/commit/865ab62f43eb94a9f4f757a464df147e983cb439

**Comment by yan12125** [comment]
Good example, so it should be
```
http://(?:[^.]+\.)iqiyi\.com/.+\.html
```
The following URLs are matched:

http://www.iqiyi.com/v_19rrojlavg.html
http://www.iqiyi.com/a_19rrhbc6kt.html
http://iqiyi.com/a_19rrhbc6kt.html
http://yule.iqiyi.com/pcb.html

But not matching:
http://www.notiqiyi.com/123.html
http://iqiyi-com/123.html

**Comment by gam2046** [comment]
`http://(?:[^.]+\.)iqiyi\.com/.+\.html` is not matched `http://iqiyi.com/a_19rrhbc6kt.html`, may be like this `http:/(?:.*?)(/|\.)iqiyi\.com/.+\.html`. 

I don't understand what you mean. Why do you want to match those addresses?(like `http://www.notiqiyi.com/123.html`) Those are not legal addresses.

**Comment by gam2046** [comment]
I'm not python, I don't know about Python support for regular expressions, may not support `. *?`, can be replaced by `.{0,999}`

**Comment by yan12125** [comment]
Sorry there's a typo:
```
http://(?:[^.]+\.)?iqiyi\.com/.+\.html
```

**Comment by yan12125** [comment]
Thanks for the contribution, cherry-picked at 82e02ea5fce6bbc595dbfefc8eafce21e2bb53cc and bee83e84f64248a47f2f0b79e8c2698bc89abf55 and add some tests. Github does not send notifications when there are new commits in a pull request, so please leave a comment the next time. And by the way, it's usually not recommended to include merge commits in pull requests.

Would you like to be listed in [AUTHORS](https://github.com/rg3/youtube-dl/blob/master/AUTHORS)? If so, under what name?

**Comment by gam2046** [comment]
No thanks. I believe that if it is someone else, it will do so. The spirit of open source should be like this, I am very grateful to you to write such a useful program.

Thanks again.

**Pull request closed without merging**
