### PR TITLE
[Newgrounds] Change test urls to https.

### PR DESCRIPTION
**Pull request by stepshal**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] New extractor
- [ ] New feature

### CODE REVIEW

**Comment by yan12125** [comment]
Hmm any concrete reason for this change? Or just because HTTPS is better than HTTP?

**Comment by stepshal** [comment]
@yan12125 Yes, just because HTTPS is better than HTTP.

**Comment by yan12125** [comment]
OK. #10584 needs to be fixed first. I guess changing to HTTPS is OK, while it's always better to do some verification.

**Comment by yan12125** [comment]
I've just pushed it to 6c3affc; thanks for this proposal!

**Pull request closed without merging**
