### PR TITLE
[NRKTV] Added support for downloading series in their entirety.

### PR DESCRIPTION
**Pull request by oddstr13**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Improvement
- [x] New extractor

---

### Description of your *pull request* and other information

Added support for downloading series in their entirety (playlist download of series).
Added season_number and episode_number metadata extraction.

See #11571

If there are any issues preventing merging, please tell me what I did wrong, as this is my first time contributing to the project.

### CODE REVIEW

**Comment by dstftw** [comment]
Squash commits.

**Comment by oddstr13** [comment]
Got some quick instructions for doing so handy?

On January 28, 2017 1:52:17 PM GMT+01:00, "Sergey M." <notifications@github.com> wrote:
>Squash commits.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rg3/youtube-dl/pull/11711#issuecomment-275846613

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oddstr13** [comment]
@dstftw like so?
For later reference; git rebase aka squash - http://stackoverflow.com/a/6934882/1035647

**Comment by dstftw** [comment]
>For later reference; git rebase aka squash

I'm well aware of that. Squashing is your responsibility.

**Comment by oddstr13** [comment]
@dstftw I am not familiar with the nuances of git, nor the desire to delete commit history just for the sake of compressing it. I clearly stated that this was my first time contributing to the project, and "squashing" of commits was not referred to anywhere in the guidelines provided. First time I heard of the term was your "Squash commits." - two weeks after contributing code to the project. A more friendly "Could you squash the commits?" would've been far preferable. I do realize that you likely have much work to do elsewhere, but if compressing into a single commit was the only blocker, I would've appreciated to know about this within a few days of my contribution - which was made to the project guidelines on best efforts and intentions, because this was functionality I desired, and thought others would find it useful also.

Your comments don't come off as particularly friendly, and does not really inspire to further contributions to the project. I have other improvements in mind, but might not bother submitting pull-requests if this is what I'll be meet with. Having this project being well maintained is in everyone's best interest, and having new and potential future contributors turned off the idea of contributing is a receipt for a slow project death. Please, just have a think about it.

The SO link was provided for later reference for myself or anyone else who might stumble upon this issue with the same question. It is clear that you knew what it was, as you where telling me to do it.

It is however _not_ my responsibility to "squash" commits. I didn't have to do any of this. I did it for the love of a great tool, which I wanted to make better. I did however not have to provide those improvements back to the public or this project, I did so because I deeply believe in the concept of open-source, and in sharing with others.

As I understand source control, it is best practice to commit changes right after you've made them and have gotten it working. Not putting off the commits indefinitely, as that promotes commit messages as "I did stuff half a year ago, no idea what..", "asdf" (relevant XKCD; https://xkcd.com/1296/).

If "squashing" of commits is desirable, and required for accepting pull-requests, it should be noted in [CONTRIBUTING.md](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#developer-instructions), somewhere before `"10. Finally, create a pull request. ..."`

I hope that the above makes sense, and doesn't come off as too offensive.

Best Regards
Odd Stråbø / Oddstr13

**Comment by dstftw** [comment]
Squashing is the basics of git and easily googleable. I assume anyone who file a PR to be able to use google. It's not possible to document just everything so you'll have to google something anyway.
Sorry about the unfriendly text if that hurt you so much. I'm minimizing my time spent on issues and reviewing so my messages are brief and concise (apart from some common phrases I have macros setup for).

>I do realize that you likely have much work to do elsewhere, but if compressing into a single commit was the only blocker, I would've appreciated to know about this within a few days of my contribution

I did not look into it until 2 days ago. Sorry but I technically can't handle all the issues and reviews on time since this project is voluntary developed in spare time.

>Your comments don't come off as particularly friendly, and does not really inspire to further contributions to the project. I have other improvements in mind, but might not bother submitting pull-requests if this is what I'll be meet with.

Well, you are not doing me a favor, nobody is forcing you to contribute. But as for me such statement sounds more like you do not care about open source. If I want to contribute, I just contribute regardless of how I'm met or some other nonsense.

>It is however _not_ my responsibility to "squash" commits.

No, it's exactly your responsibility. Once you're contributing to the something, it's you responsibility to follow the coding conventions and guidelines and it's you responsibility to provide PR in a form that fits better for merge.

>I didn't have to do any of this. I did it for the love of a great tool, which I wanted to make better. I did however not have to provide those improvements back to the public or this project, I did so because I deeply believe in the concept of open-source, and in sharing with others.

Well, you didn't have to publish it, yes. But once you decided to do so in a form of a PR you have to accept the rules and follow them.

>If "squashing" of commits is desirable, and required for accepting pull-requests, it should be noted in [CONTRIBUTING.md](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#developer-instructions), somewhere before `"10. Finally, create a pull request. ..."`

It's not exactly that. It's desirable to have a commit per a feature or some ready functionality. On the other hand it's not desirable to have a mess of commits when one is fixing code according to review. Even in the latter case squashing is only desired in the end after everything or almost everything is fixed. There is no need to squash every time, otherwise it's impossible to track changes made during PR.

**Comment by oddstr13** [comment]
I would like to apologize for being a little grumpy.
I do see the need for being time efficient when it comes to issues on such a large project as this.

Is there any more work that needs to be done before this can be merged, or is everything good as it is right now?

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -3.5 .\test\test_all_urls.py
...F.............
======================================================================
FAIL: test_no_duplicates (__main__.TestAllURLsMatching)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test\test_all_urls.py", line 98, in test_no_duplicates
    '%s should not match URL %r . That URL belongs to %s.' % (type(ie).__name__, url, tc['name']))
AssertionError: True is not false : NRKTVSeriesIE should not match URL 'https://tv.nrk.no/serie/20-spoersmaal-tv/MUHH48000314/23-05-2014' . That URL belongs to NRKTV.

----------------------------------------------------------------------
Ran 17 tests in 13.054s

FAILED (failures=1)
```

**Pull request closed without merging**
