### PR TITLE
[gogoanime] Add new extractor

### PR DESCRIPTION
**Pull request by michaelbukachi**
### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description

added gogoanime extractor

### CODE REVIEW

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by CHJ85** [comment]
Do you think you could update this extractor, @michaelbukachi

**Comment by michaelbukachi** [comment]
@CHJ85 I don't think I can. Because it violates copyright infringement

**Comment by CHJ85** [comment]
@michaelbukachi True. Using this code would violate copyright infringement because GoGoAnime is a pirate site. Hence why they haven't added the extractor to youtube-dl.
But you can still update the code.
If you don't wanna do that, can you at least tell me what changes I have to make in order to get the extractor working again?

**Comment by michaelbukachi** [comment]
> @michaelbukachi True. Using this code would violate copyright infringement because GoGoAnime is a pirate site. Hence why they haven't added the extractor to youtube-dl.
> But you can still update the code.
> If you don't wanna do that, can you at least tell me what changes I have to make in order to get the extractor working again?

When I worked on this PR initially, I wasn't aware of the copyright infringement policies. If I knew it beforehand,  I wouldn't create the PR in the first place. Now that I'm aware, I'm not willing to do any updates to the code. You can use the code as a reference and make changes accordingly.

**Comment by CHJ85** [comment]
@michaelbukachi You didn't know that a website where people can watch anime illegally would be a violation? I sure buy that story (not). 
What's the real reason? So why are you now (only a few years later) all of a sudden morally against updating the code?

**Comment by michaelbukachi** [comment]
> @michaelbukachi You didn't know that a website where people can watch anime illegally would be a violation? I sure buy that story (not).
> What's the real reason? Why are you now (only a few years later) all of a sudden morally against updating the code?
> Can you at the very least tell me in the comments here what changes I have to make in the code? Because I've been looking at this code and trying different things with no luck. Completely stuck.
> For instance, I have no idea how/where to find the md5.

Feel free to believe what you want. My decision is still the same. Have a good day.

**Comment by CHJ85** [comment]
Could you please update this one?

**Pull request closed without merging**
