### PR TITLE
New parameter --playlist-random to randomize playlist download order. Fixes #11889

### LINKED ISSUE #11889: randomize playlist order, i.e.  --playlist-random
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.29**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

Please add support for **randomizing the playlist** download order via  `--playlist-random` (or whatever other switch name).

Since there is already an option for `--reverse-playlist`, I don't think this should be too hard? (I'd contribute it myself if I was more confident in my python skills.)

The motivation for this feature is that it could be used in conjunction with `--max-downloads` (i.e. set to a low value) to randomly "sample" a variety of videos from across a channel with lots of videos, as opposed to just being able to get the first few (or last few, using `--reverse-playlist`).

### PR DESCRIPTION
**Pull request by ThomasChr**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks!

**Comment by ThomasChr** [comment]
You're welcome. I'm glad that you have not spot any error in my code :-)

**Comment by glenn-slayden** [comment]
Thanks, Thomas. I might have been brave enough to write it in Python myself. But the other problem is that I'm not familiar with the 'Git push/pull (?)' process... For collaborating, so far I've only used SVN before  :-/

**Comment by ThomasChr** [comment]
I was not very familiar with it myself, but it's really simple, so nothing to fear there.
If you want a short tutorial I can write one on Monday...

**Pull request merged**
