### PR TITLE
[vimeo] Fix error parsing

### PR DESCRIPTION
**Pull request by lalinsky**
Example video that fails - https://vimeo.com/109815029

### CODE REVIEW

**Comment by dstftw** [comment]
Can you add a test?

**Comment by lalinsky** [comment]
Is there some way to add a test that checks for the expected error message? I wanted to add a test from the beginning, but I couldn't find anything. I could add a test with `only_matching`, which would be only mostly useful for manual testing, but not actually test the behavior.

Or do I add something like `expected_errors` (similar to `expected_warnings`) to `test_download.py`?

**Comment by dstftw** [comment]
only_matching is enough for now. It's just for reference.

**Comment by lalinsky** [comment]
Done.

**Comment by dstftw** [comment]
Thanks.

**Pull request merged**
