### PR TITLE
[Veyqo] Added Extractor

### PR DESCRIPTION
**Pull request by flatt3rn**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

I added an extractor for the page veyqo because of the issue https://github.com/rg3/youtube-dl/issues/11536
Its the first thing i add to this repo and the first time i use github this way, but i hope i could help you.
It was not that hard because the page relies on openload. I just had to extract the openload link and process it like in the openload extractor.

I used the example link from the issue http://www.veyqo.net/rkprime-aidra-fox-get-closet-24-12-2016/
but testet other examples too. 
PS: I got the test_download part working, so dismiss the part in the comment

### CODE REVIEW

**Comment by dstftw** [comment]
Read
>[adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections

and fix all the issues.

**Comment by flatt3rn** [comment]
Sorry that i ask but i read them and i dont know which issue i should fix.
Can you tell me so i know it for the future?

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by flatt3rn** [comment]
Ok i See. I thought if in the issue is the lable request this extractor is wanted, but if thats not so i will close the pull request.

**Pull request closed without merging**
