### PR TITLE
[Pornhub] Fix for Issue #12007

### PR DESCRIPTION
**Pull request by ThomasChr**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

Fixes the pronhub extractor. Uses exec() which is not the smartest solution... suggestions are welcomed!
UPDATE: Does not use exec() anymore.

### CODE REVIEW

**Comment by ThomasChr** [comment]
Fix for issue #12007 - I'm not comfortable with using exec() but it worked fine...

**Comment by yan12125** [comment]
You should not use exec. Random codes may be executed.

**Comment by ThomasChr** [comment]
@yan12125 I'm aware of that. Any suggestions how to solve the problem we're facing?

Pornhub does first define variables:
`a = 'http://www'`
`b = 'pornhub.com/video.mp4'`

And than the video url gets merged from the variables:
`url = a + b`

So I need to find some kind of way to execute this Javascript-Code - I don't think that writing a parser myself would be the solution. I hoped that youtube-dl had some "execute this javascript code"-Function.

**Comment by yan12125** [comment]
There's a jsinterp module. See youtube.py for an example usage

**Comment by ThomasChr** [comment]
@yan12125 Fixed it, it's kind of simple parsing, so no need to use JSInterpreter.

**Comment by MikeRich88** [comment]
All you need to do is request the video with a cookie "platform=tv" then you get an unobfuscated video URL.

**Pull request closed without merging**
