### PR TITLE
[baidu] improve info extraction

### PR DESCRIPTION
**Pull request by remitamine**

### CODE REVIEW

**Comment by yan12125** [comment]
What's the purpose of this PR? The current approach works just fine, and it matches what browsers do.

**Comment by remitamine** [comment]
- extract info directly from the api is better than downloading the webpage and using regex for extraction.
- extract direct links instead of making head requests for every url in the playlist.

**Comment by yan12125** [comment]
> extract info directly from the api is better than downloading the webpage and using regex for extraction.

It's not the case in youtube-dl. youtube-dl tries to mimic browsers as much as possible so that videos available on browsers are always downloadable. If these API calls are seen in actual browsing (from different IPs, embedded pages, or mobile devices etc.), then it's acceptable. Where did you find ```xqinfo``` API calls?

> extract direct links instead of making head requests for every url in the playlist.

It's indeed a problem. However, there's no need to handle redirections in individual info extractors. [GenericIE](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/generic.py#L1820) works fine. It's my bad that I didn't notice that at the first time.

**Comment by remitamine** [comment]
> Where did you find xqinfo API calls?
in mobile devices.

**Comment by yan12125** [comment]
Thanks merged with some modifications.

**Pull request merged**
