### PR TITLE
[extractor/common] improve m3u8 info extraction

### PR DESCRIPTION
**Pull request by remitamine**
parts from the documention that explain some of the changes.
> If an EXT-X-STREAM-INF tag contains a RESOLUTION attribute and a
VIDEO attribute, then every alternative video Rendition MUST have
an optimal display resolution matching the value of the RESOLUTION
attribute.

```python
                group = stream_info.get('VIDEO')
                if group:
                    groups[group] = r
...
                group = groups.get(media_info['GROUP-ID'])
                if group:
                    v.update(group)
```
> If the media TYPE is AUDIO and the URI attribute is
missing, clients MUST assume that the audio data for this Rendition
is present in every video Rendition specified by the EXT-X-STREAM-INF
tag.

```python
lang = media_info.get('LANGUAGE')
...
'language': lang,
```

### CODE REVIEW

**Comment by yan12125** [comment]
Any sample M3U8 breaks current codes?

**Comment by remitamine** [comment]
- it extract some extra metadata about formats.
before:
```
youtube-dl -F http://www.crackle.com/the-art-of-more/2496419
[Crackle] 2496419: Downloading XML
[Crackle] 2496419: Downloading m3u8 information
[info] Available formats for 2496419:
format code      extension  resolution note
hls-meta         mp4        multiple   Quality selection URL 
hls-127          mp4        192x108     127k , mp4a.40.5, avc1.42000b
hls-253          mp4        256x144     253k , mp4a.40.5, avc1.42000c
hls-475          mp4        416x234     475k , mp4a.40.5, avc1.42000d
http-c544        flv        544x306    
http-360p        mp4        640x360    
hls-935          mp4        704x396     935k , mp4a.40.5, avc1.4d001e
http-480p        mp4        852x478    
http-480p_1mbps  mp4        852x478    
hls-1827         mp4        896x504    1827k , mp4a.40.5, avc1.4d001f
hls-3837         mp4        1280x720   3837k , mp4a.40.5, avc1.4d001f (best)
```
after:
```
youtube-dl -F http://www.crackle.com/the-art-of-more/2496419
[Crackle] 2496419: Downloading XML
[Crackle] 2496419: Downloading m3u8 information
[info] Available formats for 2496419:
format code      extension  resolution note
hls-meta         mp4        multiple   Quality selection URL 
hls-119          mp4        192x108    [en] 119k , mp4a.40.5, 15.0fps, avc1.42000b
hls-230          mp4        256x144    [en] 230k , mp4a.40.5, 30.0fps, avc1.42000c
hls-414          mp4        416x234    [en] 414k , mp4a.40.5, 30.0fps, avc1.42000d
http-c544        flv        544x306    
http-360p        mp4        640x360    
hls-709          mp4        704x396    [en] 709k , mp4a.40.5, 30.0fps, avc1.4d001e
http-480p        mp4        852x478    
http-480p_1mbps  mp4        852x478    
hls-1230         mp4        896x504    [en]1230k , mp4a.40.5, 30.0fps, avc1.4d001f
hls-2092         mp4        1280x720   [en]2092k , mp4a.40.5, 30.0fps, avc1.4d001f (best)
```
- also from the previous example `AVERAGE-BANDWIDTH` should be more accurate than `BANDWIDTH`.
BANDWIDTH

> The value is a decimal-integer of bits per second.
It represents the peak segment bit rate of the Variant Stream.
If all the Media Segments in a Variant Stream have already been
created, the BANDWIDTH value MUST be the largest sum of peak
segment bit rates that is produced by any playable combination of
Renditions.

AVERAGE-BANDWIDTH
>  The value is a decimal-integer of bits per second. It represents
the average segment bit rate of the Variant Stream.
If all the Media Segments in a Variant Stream have already been
created, the AVERAGE-BANDWIDTH value MUST be the largest sum of
average segment bit rates that is produced by any playable
combination of Renditions.

- as a first step add some code to extract the subtiltes availibility simular to the one from _extrac_smil_*.
- extract multiple audio formats if they are available in the manifest(multiple `EXT-X-MEDIA` with `URI`).
- `EXT-X-MEDIA` as a fourth value that's not checked before(`CLOSED-CAPTIONS`).
even if some of this cases are not widely used i think it's good to implement them in case they appear.

**Comment by Kagami** [comment]
Any ETA on this? This code should be useful for vlive extractor.

Sample playlists if you need some real examples:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Vietnamese",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_lvie.m3u8",LANGUAGE="vie"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_leng.m3u8",LANGUAGE="eng"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="zcn",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_lzcn.m3u8",LANGUAGE="zcn"
#EXT-X-STREAM-INF:BANDWIDTH=1464974,CODECS="avc1.66.22,mp4a.40.2",RESOLUTION=640x368,SUBTITLES="subs"
chunklist.m3u8?__agda__=1461853927_d2d91835e251112f931019235adf7e99
```

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_leng.m3u8",LANGUAGE="eng"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="zcn",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_lzcn.m3u8",LANGUAGE="zcn"
#EXT-X-STREAM-INF:BANDWIDTH=1552079,CODECS="avc1.66.41,mp4a.40.2",RESOLUTION=640x368,SUBTITLES="subs"
chunklist.m3u8?__agda__=1461870184_78a9da91e282182e47a811c0dd3c2c98
```

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=540832,CODECS="avc1.66.22,mp4a.40.2",RESOLUTION=640x368
chunklist.m3u8?__agda__=1461875868_c243897d8537d171a6ae968612588b42
```

**Comment by yan12125** [comment]
@remitamine Any reason not using the old key, value loop?

**Comment by remitamine** [comment]
> @remitamine Any reason not using the old key, value loop?

there are some parts that depend on other information so i select only the part i need parse it completly then i pass to other parts(it should not depend on the order of tags).

**Pull request closed without merging**
