### PR TITLE
[UDNEmbed] enhance UDN support and modify the name

### PR DESCRIPTION
**Pull request by RPing**
hi all,
I add more support to UDN site(which is called "UDNEmbed" by @yan12125 ), besides "embed" video.
like https://video.udn.com/news/398685
pls check it, thx.

### CODE REVIEW

**Comment by yan12125** [comment]
Originally generic UDN pages are handled by ```GenericIE```, while it's not working now. I'll check what happens.

**Comment by RPing** [comment]
Thx!

**Comment by RPing** [comment]
i think _VALID_URL in udn.py should be modified to 
r'(?:https?:)?//video\.udn\.com/(?:embed|play)/news/(?P<id>\d+)'

because <iframe>in the web page information "src" attribute is like
//video.udn.com/play/news/398685   
which doesn't have scheme name.
and it works.

**Comment by yan12125** [comment]
Your final patch cause the following error:
```
$ youtube-dl -vs "//video.udn.com/embed/news/300040"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vs', '//video.udn.com/embed/news/300040']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.18
[debug] Git HEAD: 82beaab
[debug] Python version 3.5.0 - Linux-4.3.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[UDNEmbed] 300040: Downloading webpage
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/udn.py", line 37, in _real_extract
    page = self._download_webpage(url, video_id)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 441, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 348, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1873, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 450, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 268, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 294, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '//video.udn.com/embed/news/300040'
```

The protocol-relative URL should be eventually handled by ```UDNEmbedIE```, too.

**Comment by RPing** [comment]
got it, thx!
i've just begun this project, there's still some details i haven't concerned yet.
thx for the information.

**Pull request closed without merging**
