### PR TITLE
fix problem with umlauts in title

### PR DESCRIPTION
**Pull request by mmue**
Fix a problem with German umlauts in the title.

Example:
http://www.prosieben.de/tv/germanys-next-topmodel/video/playlist/ganze-folge-episode-2-das-casting-in-muenchen

### CODE REVIEW

**Comment by phihag** [comment]
This removes all non-ascii characters from RTMP downloads. That cannot be correct. Can you give me the issue number of the issue this PR should fix? Note the download works perfectly fine for me, I get all the umlauts.

**Comment by mmue** [comment]
user@host$ env -i ./youtube-dl "http://www.prosieben.de/tv/germanys-next-topmodel/video/playlist/ganze-folge-episode-2-das-casting-in-muenchen"
[prosiebensat1] tv/germanys-next-topmodel/video/playlist/ganze-folge-episode-2-das-casting-in-muenchen: Downloading webpage
[download] Downloading playlist: Ganze Folge: Episode 2 - Das Casting in Mnchen
[prosiebensat1] playlist Ganze Folge: Episode 2 - Das Casting in Mnchen: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[prosiebensat1] tv/germanys-next-topmodel/video/102-episode-2-casting-in-muenchen-teil-1-ganze-folge: Downloading webpage
[prosiebensat1] 3685549: Downloading videos JSON
[prosiebensat1] 3685549: Downloading sources JSON
[prosiebensat1] 3685549: Downloading urls JSON
[download] Destination: Episode 2 - Casting in Mnchen (Teil 1)-3685549.mp4
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 389, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 379, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1441, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 813, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 700, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1143, in process_video_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1374, in process_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1349, in dl
  File "./youtube-dl/youtube_dl/downloader/common.py", line 339, in download
  File "./youtube-dl/youtube_dl/downloader/rtmp.py", line 171, in real_download
  File "./youtube-dl/youtube_dl/downloader/rtmp.py", line 29, in run_rtmpdump
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings


user@host$ ./youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.02.26
[debug] Python version 2.7.6 - Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by phihag** [comment]
Thanks, fixed properly in 2015.02.26.1 and newer.

**Comment by phihag** [comment]
Note that in future cases, you may want to set the `LC_ALL` environment variable to something like `en_US.UTF-8` or `de_DE.UTF-8`.

**Pull request closed without merging**
