### PR TITLE
[biobiotv] Add new extractor

### PR DESCRIPTION
**Pull request by jjatria**
Adds a new extractor for BioBioTV.

### CODE REVIEW

**Comment by jjatria** [comment]
@GiedriusS Thanks for the suggestion!

I've made the changes that you suggest and the tests are passing. It's been some time, though, and now there seems to be a conflict in `__init__.py`. I can rebase and submit a new pull request if that helps.

**Comment by jjatria** [comment]
Is there any other reason this has not / will not be merged?

I see that this branch now has conflicts. Should I rebase and issue a new PR?

**Comment by dstftw** [comment]
Does not work with http://tv.biobiochile.cl/notas/2016/03/18/natalia-valdebenito-repasa-a-diputado-hasbun-paso-a-la-categoria-de-hablar-brutalidades.shtml.

**Comment by jjatria** [comment]
Oh, I actually just pushed my own changes to fix this, but it's good to see it merged.

Thanks!

**Comment by dstftw** [comment]
Cherry-picked in e36f4aa72b01b3f6a322edc094cdf1c20b071367, thanks.

**Pull request closed without merging**
