### PR TITLE
[youku] Fix list extraction.(close #15065)

### LINKED ISSUE #15065: Can not download playlist on Youku
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

`YoukuShowIE` class can extract playlist whose episode count is over than `50`. Here is an video with episode count 26 `youtube-dl` can not download.

```bash
youtube-dl http://list.youku.com/show/id_zefbfbd61237fefbfbdef.html\?spm\=a2h0j.8191423.module_basic_title.5\~A\!2 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://list.youku.com/show/id_zefbfbd61237fefbfbdef.html?spm=a2h0j.8191423.module_basic_title.5~A!2', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.13 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youku:show] zefbfbd61237fefbfbdef: Downloading webpage
[youku:show] zefbfbd61237fefbfbdef: Downloading initial playlist data page
[download] Downloading playlist: 虎啸龙吟
[youku:show] playlist 虎啸龙吟: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 虎啸龙吟
```
As you see `[youku:show] playlist 虎啸龙吟: Collected 0 video ids (downloading 0 of them)`, so there is a bug. I will fix it and create a PR.

### PR DESCRIPTION
**Pull request by CoXier**
### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### CODE REVIEW

**Comment by CoXier** [comment]
@yan12125 

I am confused about the test case.

```bash
python test/test_download.py TestDownload.test_YoukuShow

[youku:show] zc7c670be07ff11e48b3f: Downloading webpage
[youku:show] zc7c670be07ff11e48b3f: Downloading initial playlist data page
[youku:show] zc7c670be07ff11e48b3f: Downloading playlist data page 2
[download] Downloading playlist: 花千骨 DVD版
[youku:show] playlist 花千骨 DVD版: Collected 50 video ids (downloading 50 of them)
[download] Downloading video 1 of 50
[download] Downloading video 2 of 50
[download] Downloading video 3 of 50
[download] Downloading video 4 of 50
[download] Downloading video 5 of 50
[download] Downloading video 6 of 50
[download] Downloading video 7 of 50
[download] Downloading video 8 of 50
[download] Downloading video 9 of 50
[download] Downloading video 10 of 50
[download] Downloading video 11 of 50
[download] Downloading video 12 of 50
[download] Downloading video 13 of 50
[download] Downloading video 14 of 50
[download] Downloading video 15 of 50
[download] Downloading video 16 of 50
[download] Downloading video 17 of 50
[download] Downloading video 18 of 50
[download] Downloading video 19 of 50
[download] Downloading video 20 of 50
[download] Downloading video 21 of 50
[download] Downloading video 22 of 50
[download] Downloading video 23 of 50
[download] Downloading video 24 of 50
[download] Downloading video 25 of 50
[download] Downloading video 26 of 50
[download] Downloading video 27 of 50
[download] Downloading video 28 of 50
[download] Downloading video 29 of 50
[download] Downloading video 30 of 50
[download] Downloading video 31 of 50
[download] Downloading video 32 of 50
[download] Downloading video 33 of 50
[download] Downloading video 34 of 50
[download] Downloading video 35 of 50
[download] Downloading video 36 of 50
[download] Downloading video 37 of 50
[download] Downloading video 38 of 50
[download] Downloading video 39 of 50
[download] Downloading video 40 of 50
[download] Downloading video 41 of 50
[download] Downloading video 42 of 50
[download] Downloading video 43 of 50
[download] Downloading video 44 of 50
[download] Downloading video 45 of 50
[download] Downloading video 46 of 50
[download] Downloading video 47 of 50
[download] Downloading video 48 of 50
[download] Downloading video 49 of 50
[download] Downloading video 50 of 50
[download] Finished downloading playlist: 花千骨 DVD版
.
----------------------------------------------------------------------
Ran 1 test in 1.541s

OK

```
To test YoukuShowIE, I execute above command and it unexpectedly passed before I create this PR.  
I find only first test case is checked. When I delete the first one, the test failed.

```bash
python test/test_download.py TestDownload.test_YoukuShow
[youku:show] zefbfbd70efbfbd780bef: Downloading webpage
[youku:show] zefbfbd70efbfbd780bef: Downloading initial playlist data page
[youku:show] zefbfbd70efbfbd780bef: Downloading playlist data page 2
[youku:show] zefbfbd70efbfbd780bef: Downloading playlist data page 3
[download] Downloading playlist: 超级飞侠3
[youku:show] playlist 超级飞侠3: Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
[download] Downloading video 2 of 26
[download] Downloading video 3 of 26
[download] Downloading video 4 of 26
[download] Downloading video 5 of 26
[download] Downloading video 6 of 26
[download] Downloading video 7 of 26
[download] Downloading video 8 of 26
[download] Downloading video 9 of 26
[download] Downloading video 10 of 26
[download] Downloading video 11 of 26
[download] Downloading video 12 of 26
[download] Downloading video 13 of 26
[download] Downloading video 14 of 26
[download] Downloading video 15 of 26
[download] Downloading video 16 of 26
[download] Downloading video 17 of 26
[download] Downloading video 18 of 26
[download] Downloading video 19 of 26
[download] Downloading video 20 of 26
[download] Downloading video 21 of 26
[download] Downloading video 22 of 26
[download] Downloading video 23 of 26
[download] Downloading video 24 of 26
[download] Downloading video 25 of 26
[download] Downloading video 26 of 26
[download] Finished downloading playlist: 超级飞侠3
F
======================================================================
FAIL: test_YoukuShow (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_download.py", line 195, in test_template
    len(res_dict['entries']),
AssertionError: Expected 24 entries in playlist http://list.youku.com/show/id_zefbfbd70efbfbd780bef.html, but got 26.

----------------------------------------------------------------------
Ran 1 test in 1.616s
```
Actually its playlist count is 26 so it failed. **I want to know why not test all case ?**

**Comment by yan12125** [comment]
I remember when I added the 超级飞侠3 test case, there are only 24 videos. I plan to fix that after this PR is merged.

**Comment by CoXier** [comment]
Why is only first test case checked?

**Comment by yan12125** [comment]
Sorry I didn't read your description carefully.

> Why is only first test case checked?

That's how things are working. To check the second test case, use test_YoukuShow_1. See also #10897.

**Comment by CoXier** [comment]
So why `Travis` not test all case ?

**Comment by yan12125** [comment]
Not sure what you mean. On Travis CI all test cases except those marked as 'only_matching' are tested:
```
test_YoukuShow (test.test_download.TestDownload): ... ok
test_YoukuShow_1 (test.test_download.TestDownload): ... FAIL

```

**Comment by CoXier** [comment]
Thanks, I got it. But as you see from `Travis`

> All checkes have passed.

**Comment by yan12125** [comment]
As it's almost impossible to make all download tests pass, it's decided to focus on core tests only (9a9de2d7b2462c9a16bac0ead3f415ef64179833), so that regressions in basic functionality are visible.

**Comment by CoXier** [comment]
@yan12125 Please check added test case.

**Comment by yan12125** [comment]
Thanks for the fix!

**Pull request merged**
