### PR TITLE
Updated extractor for Vier to support Kijk Online.

### PR DESCRIPTION
**Pull request by wernerkarlheisenberg**
Updated extractor for Vier to support Kijk Online. Change includes a general extractor for Incognito IDP by AWS. boto3 and warrant packages are required.

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Updated extractor for Vier to support Kijk Online. Change includes a general extractor for Incognito IDP by AWS. boto3 and warrant packages are required.

### CODE REVIEW

**Comment by dstftw** [comment]
1. Any dependency **must** be a soft dependency so it **must not** crash the whole program if it's not installed.
2. Read coding conventions and fix your code.
3. Run tests. Core is broken after these changes.

**Comment by wernerkarlheisenberg** [comment]
Apologizes. I hope that new implementation is better.

**Comment by wernerkarlheisenberg** [comment]
Test no longer result in error and comply with coding guidelines. Anythings else that needs to be done?

**Comment by wernerkarlheisenberg** [comment]
What is it that I need to do to make sure that these changes are merged?

**Comment by brechtm** [comment]
Nice work, @wernerkarlheisenberg! What's the status of this PR? Why did you close it?

**Comment by wernerkarlheisenberg** [comment]
Simply because i did not receive any feedback. I can easily create a new pull request. I'm activly using the changes at this moment.

**Comment by brechtm** [comment]
BTW. Did you look at adding support for zestv.be? I assume this website is largely identical to vier.be and vijf.be?

**Comment by wernerkarlheisenberg** [comment]
I fixed the 'Ex-Gangster' issues by using ' - ' instead if '-'. This change will be in the new pull request. I also looked at Zes as well. The difference with Vier and Vijf is that you can only view fragments (no authentication needed), not full episodes.

**Comment by wernerkarlheisenberg** [comment]
I could not reopen this Pull Request, so create a new one, #15636. I will be more patient this time ;-).

**Comment by haveneersrobin** [comment]
Is this still not merged? vier.be does not seem to work yet

**Comment by michaelarnauts** [comment]
These changes work fine, but I only get a file in low resolution. (I've tried with The Day episode 1).

**Comment by Kobe-git** [comment]
I still get an "ERROR: Unable to extract filename" when I type "youtube-dl https://www.vier.be/video/de-dag/de-dag/de-dag-aflevering-1"

**Comment by wivaku** [comment]
When not providing username+password I get the `unable to extract filename`.
But when I add username+password then I get: `Unable to log in: HTTP Error 403: Forbidden (caused by HTTPError())`:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.vier.be/video/de-mol/de-mol-2019/gfw379cm', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Python version 2.7.16 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vier] Logging in
ERROR: Unable to log in: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

Using that username + password and then viewing the video does work in the browser.

**Comment by wivaku** [comment]
still the same issue / behavior. Using version 2020.03.06.
E.g. for `https://www.vier.be/video/de-mol/de-mol-s8/de-mol-s8-aflevering-1`

**Pull request closed without merging**
