### PR TITLE
Add dhm extractor

### PR DESCRIPTION
**Pull request by ossi96**
Add a new extractor for the video collection of the German historical museum

### CODE REVIEW

**Comment by dstftw** [comment]
Thanks, merged.

**Comment by ossi96** [comment]
There is a problem with the changes you've done in _VALID_URL. When you try to download a video from the "Mapping the wall" collection it doesn't work because it has a different root URL.

**Comment by dstftw** [comment]
@ossi96 post an URL.

**Comment by ossi96** [comment]
http://www.dhm.de/filmarchiv/02-mapping-the-wall/peter-g/rolle-1/

**Comment by dstftw** [comment]
Fixed in 5a3b315b5fcc1b1e153baeaed669e64d137d4047.

**Comment by ossi96** [comment]
And now my name appears 2 times in the credits. :D

**Comment by dstftw** [comment]
Oops.

**Pull request merged**
