### PR TITLE
Add safaribooksonline extractor

### PR DESCRIPTION
**Pull request by zx8**
Following on from https://github.com/rg3/youtube-dl/issues/5253, I decided to give implementing this a go myself.

### CODE REVIEW

**Comment by dstftw** [comment]
Thanks, merged.
Do you want to be credited as one of the authors of youtube-dl? If so, under what name?

**Comment by zx8** [comment]
No problem. Keep up the good work.

It's ok, it was only a small change, maybe if I contribute something more substantial in future. :-)

**Comment by evliu** [comment]
Do you know if there is a difference between www.safaribooksonline.com and techbus.safaribooksonline.com? I have an enterprise account and I found this is not able to download via my account. Thx

**Comment by zx8** [comment]
@evliu Not sure I'm afraid, I don't have an Enterprise account so can't test/fix it myself.

**Comment by evliu** [comment]
Ahh okay. I think it used to work before the change on their site. I’ll see if I can figure something out

**Comment by evliu** [comment]
I think the mobile site might be the same, do you know how I could implement for something like http://m.safaribooksonline.com/hd/video?isbn=9781771371179&linkid=1-2013-09-19 ?

**Comment by jcdauchy** [comment]
I have the same type of problem with this type of URL : https://my.safaribooksonline.com/video/databases/hadoop/9781771372374

Don't understand the difference with the default www.safaribooksonline.com.

Anyone with the same issue ?
Thanks

**Pull request merged**
