### PR TITLE
[bilibili] fix info extraction

### LINKED ISSUE #7182: The download for Bilibili.com is not working
```
youtube-dl http://www.bilibili.com/video/av3044559/
[BiliBili] 3044559: Downloading webpage
[BiliBili] 3044559: Downloading LQ video info
ERROR: BiliBili said: API调用失败.APP_NOT_FOUND
```

I tried on 2 videos and they give me the same error message.
`API调用失败` means API implementation failed.

### PR DESCRIPTION
**Pull request by remitamine**
fixes #7182.

### CODE REVIEW

**Comment by starkshaw** [comment]
Hi, I saw you mentioned my issue #7182 then I tried the newest youtube-dl, it is still not working.

**Comment by remitamine** [comment]
it's not merged yet.
this is the output using the changes in this branch.
```
python2 __main__.py -v http://www.bilibili.com/video/av3044559/
[debug] System config: []
[debug] User config: [u'--external-downloader', u'aria2c', u'--external-downloader-args', u'-x 16', u'-f', u'[height<=?720]', u'--sub-lang', u'ar,arME,en', u'--write-sub', u'--no-check-certificate']
[debug] Command-line args: [u'-v', u'http://www.bilibili.com/video/av3044559/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Git HEAD: 520e753
[debug] Python version 2.7.10 - Linux-4.2.3-1-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[BiliBili] 3044559: Downloading JSON metadata
[BiliBili] 4777948: Downloading page 1/1
[debug] Invoking downloader on 'http://ws.acgvideo.com/f/8b/4777948-1.flv?wsTime=1445301455&wsSecret2=922e94702d4b2a040e256c3c9d93c8aa&oi=3312805269&appkey=8e9fc618fbd41e28&or=1743343923'
[download] Destination: 哆啦A梦(2015.10.09)最强!大雄殿下&秋之虫虫音乐会【钉铛】-4777948.flv
[debug] aria2c command line: aria2c -c -x 16 --out '哆啦A梦(2015.10.09)最强!大雄殿下&秋之虫虫音乐会【钉铛】-4777948.flv.part' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept-Language: en-us,en;q=0.5' --header 'Accept-Encoding: gzip, deflate' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)' --check-certificate=false -- 'http://ws.acgvideo.com/f/8b/4777948-1.flv?wsTime=1445301455&wsSecret2=922e94702d4b2a040e256c3c9d93c8aa&oi=3312805269&appkey=8e9fc618fbd41e28&or=1743343923'
[#3a0b15 256KiB/178MiB(0%) CN:16 DL:36KiB ETA:1h23m52s]
```

**Comment by starkshaw** [comment]
Thanks @remitamine 
However, I noticed that Travis Cl build failed. Could you please check if that is relevant?

**Comment by remitamine** [comment]
the Travis Cl build run tests for all sites supported by youtube-dl so it failed because of other sites not bilibili tests.this is the part in the build related to bilibili:
```
...
test_BiliBili (test.test_download.TestDownload) ... ok
test_BiliBili_1 (test.test_download.TestDownload) ... ok
test_Blinkx (test.test_download.TestDownload) ... ok
test_BlipTV (test.test_download.TestDownload) ... ERROR
...
```

**Pull request merged**
