### PR TITLE
Fix https://github.com/rg3/youtube-dl/issues/11890

### PR DESCRIPTION
**Pull request by Khang-NT**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

### CODE REVIEW

**Comment by Khang-NT** [comment]
https://github.com/rg3/youtube-dl/issues/11890

**Comment by RooTooZ** [comment]
Please approve this commit!!!! Thank you @Khang-NT!!!

**Comment by newtroy2010** [comment]
I just integrated youtube-dl into my system , I love the program, hoping this error is resolved soon, please keep me in the loop,  newtroy@live.com  is my email

**Comment by jakecoble** [comment]
To get @Khang-NT's fix while you're waiting for the pull request to be approved, you can install it with pip. `pip install git+https://github.com/Khang-NT/youtube-dl.git`

**Comment by AsunaXXII** [comment]
when i try to install with pip i get this error:
 Error [WinError 2] The system cannot find the file specified while executing command git clone -q git://github.com/Khang-NT/youtube-dl C:\Users\100623~1\AppData\Local\Temp\pip-build-f3f27dna\youtube-dl
Cannot find command 'git'

**Comment by FranklinL** [comment]
@AsunaXXII Install Git.

**Comment by ThomasChr** [comment]
Fix worked for me.
This pull now closes 7 issues:
#11902, #11900, #11897, #11895, #11894, #11891, #11890.

**Comment by shantanuthatte** [comment]
ETA on release?

**Comment by Oliy1492** [comment]
Can someone build this into exe form otherwise I will have to wait for release and that could be several hours :/

**Comment by user890104** [comment]
I have published an UNOFFICIAL Windows build that includes this fix here: https://github.com/user890104/youtube-dl/releases/tag/2017.01.31-user890104

**Comment by yasinalm** [comment]
This is just a temporary solution. It just works for the videos that do not require a signature. This does not work for all videos.

**Comment by user890104** [comment]
@yasinalm Please provide a YouTube URL, which is not working.

**Comment by doublex** [comment]
@user890104 
https://www.youtube.com/watch?v=BLIjRIpLJVE

**Comment by ThomasChr** [comment]
@doublex: I can download your provided video without any problems (after applying the commit from the pull request).
I also tried some other without (I think some with signature) and all worked well.
What error do you get?
`[youtube] BLIjRIpLJVE: Downloading webpage
[youtube] BLIjRIpLJVE: Downloading video info webpage
[youtube] BLIjRIpLJVE: Extracting video information
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Κωνσταντίνος Αργυρός - Όσα Νιώθω - Official Video Clip-BLIjRIpLJVE.f137.mp4
[download] 100% of 65.37MiB in 00:01
[download] Destination: Κωνσταντίνος Αργυρός - Όσα Νιώθω - Official Video Clip-BLIjRIpLJVE.f251.webm
[download] 100% of 4.30MiB in 00:00
[ffmpeg] Merging formats into "Κωνσταντίνος Αργυρός - Όσα Νιώθω - Official Video Clip-BLIjRIpLJVE.mkv"
Deleting original file Κωνσταντίνος Αργυρός - Όσα Νιώθω - Official Video Clip-BLIjRIpLJVE.f137.mp4 (pass -k to keep)
Deleting original file Κωνσταντίνος Αργυρός - Όσα Νιώθω - Official Video Clip-BLIjRIpLJVE.f251.webm (pass -k to keep)
`

**Comment by Hrxn** [comment]
So, is this still a temporary solution or is it fixed completely now?

**Comment by ThomasChr** [comment]
Works fine for me and the pull request has been officially commited!

**Comment by ztackett11** [comment]
I am still unable to get this fixed on my local system? Do I need to do a reboot or something? I pulled the request mentioned above and it downloaded but says it's the 2016.08.31 version?

**Comment by ThomasChr** [comment]
@ztackett11 You're still using Youtube-DL '2016.08.31'. So your update didn't work at all. How do you update? Changes are that your Repository is not up to date (if using Linux).

**Comment by ztackett11** [comment]
@ThomasChr I figured out the problem late last night. I had two installations of youtube-dl, one inside my directory from which the program I use youtube-dl, and another in my main User directory.

Going into my Python site-packages directory and deleting the youtube-dl folder and files, then reinstalling youtube-dl is what fixed it for me.

Everything is working great for me now.

**Pull request closed without merging**
