### PR TITLE
[extractor/common] Not all video_data have "title"

### PR DESCRIPTION
**Pull request by mozbugbox**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by dstftw** [comment]
This is intentional. `require_title` must be passed if there is no title.

**Comment by mozbugbox** [comment]
* The logic of that line was wrong to begin with. It passed title no matter if the `require_title` was true or false.
* this line of code will raise exception when "title" field not in the video_data as can be seen in issue #12410 .
* The fix passed back title if `require_title` was True. If not "title" field in `video_data`, an empty string was passed.

**Comment by mozbugbox** [comment]
Actually, the ambiguity was when `require_title == False`, should something passed back for `title`? If a `title` should be passed, as the current code stands, then that line should be changed to 
 ```
               'title': video_data.get('title', ''),
```
i.e. always try to pass the "title" field back.

**Comment by dstftw** [comment]
1. Current logic is perfectly fine.
2. `require_title=False` should be passed if title may not be present. I've already pointed this out.
3. This is wrong. `require_title` only determines whether extraction should fail if title is not available or not.

**Pull request closed without merging**
