### PR TITLE
Add --playlist-index-offset [number] command line parameter

### PR DESCRIPTION
**Pull request by loganintech**
### Before submitting a _pull request_ make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
### What is the purpose of your _pull request_?
- [ ] Bug fix
- [ ] New extractor
- [x] New feature

---
### Description of your _pull request_ and other information

This is just a small change to the formatting of `%(playlist_index)s` that adds the ability to give it an offset. This way you could combine multiple playlists by downloading 10 videos from one playlist and 10 from another but name from 1 to 20. For example:

> youtube-dl --yes-playlist -o "/location/%(title)s_S0E%(playlist_index).%(ext)s" "http://yourlink.com/playlistone"

Would produce episodes S0E (1 through 10)

And then you can continue from another playlist with one addition

> youtube-dl --yes-playlist **--playlist_index_offset 10** -o "/location/%(title)s_S0E%(playlist_index).%(ext)s" "http://yourlink.com/playlisttwo"

which would produce S0E (11-20)

### CODE REVIEW

**Comment by yan12125** [comment]
The meaning of ```%(playlist_index)s``` should never be touched with any option. It's exactly the position of a video in a playlist. On the other hand, ```--autonumber-start``` is a good idea.

**Comment by JewsOfHazard** [comment]
Yeah but it's so much more complicated :(. I'll see about writing it Monday.

**Comment by JewsOfHazard** [comment]
The problem I could foresee with changing the auto number starting location is the size variable. It could be a nonissue but admittedly I haven't spent *that* much time going through the code. Couldn't there be a behavior problem if I were to start the autonumber at say 99 and it tried to put 100 in a slot of two? I may be overthinking this.

**Comment by yan12125** [comment]
> Couldn't there be a behavior problem if I were to start the autonumber at say 99 and it tried to put 100 in a slot of two? I may be overthinking this.

Did you mean use ```%(autonumber)s``` with ```--autonumber-size```? There's already a case:
```
$ youtube-dl -v --get-filename "https://www.youtube.com/playlist?list=PLwP_SiAcdui0KVebT0mU9Apz359a4ubsC" -o '%(autonumber)s.%(ext)s' -f best
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--get-filename', 'https://www.youtube.com/playlist?list=PLwP_SiAcdui0KVebT0mU9Apz359a4ubsC', '-o', '%(autonumber)s.%(ext)s', '-f', 'best']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.28
[debug] Git HEAD: 04b32c8
[debug] Python version 3.5.2 - Linux-4.7.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
00001.mp4
00002.mp4
00003.mp4
00004.mp4
00005.mp4
00006.mp4
00007.mp4
00008.mp4
00009.mp4
00010.mp4
00011.mp4
00012.mp4
00013.mp4
00014.mp4
00015.mp4
^C
ERROR: Interrupted by user

$ youtube-dl -v --get-filename "https://www.youtube.com/playlist?list=PLwP_SiAcdui0KVebT0mU9Apz359a4ubsC" -o '%(autonumber)s.%(ext)s' -f best --autonumber-size 1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--get-filename', 'https://www.youtube.com/playlist?list=PLwP_SiAcdui0KVebT0mU9Apz359a4ubsC', '-o', '%(autonumber)s.%(ext)s', '-f', 'best', '--autonumber-size', '1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.28
[debug] Git HEAD: 04b32c8
[debug] Python version 3.5.2 - Linux-4.7.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
1.mp4
2.mp4
3.mp4
4.mp4
5.mp4
6.mp4
7.mp4
8.mp4
9.mp4
10.mp4
11.mp4
12.mp4
13.mp4
14.mp4
15.mp4
^C
ERROR: Interrupted by user
```
Some people may argue that it's a "bug" that ```%(autonumber)s``` does not always yield fixed-width filenames. For me it's just OK.

**Comment by JewsOfHazard** [comment]
Yeah but like you said indexes shouldn't be touched with another option. I have some time on my hands to write the --autonumber-start parameter so I am going to go ahead and do that now.

**Pull request closed without merging**
