### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by habi**
As part of http://24pullrequests.com

### CODE REVIEW

**Comment by dstftw** [comment]
I don't see any point emphasizing **youtube-dl** all over the places. Only important parts of text should be emphasized for catching attention.

**Comment by habi** [comment]
The first time it’s mentioned unemphasised, the next two times it’s emphasised, then again not.
I thought it would be good to harmonise that.

**Comment by phihag** [comment]
No, it should basically be never emphasized, except maybe once or twice at the very beginning, or if following other conventions. 67 times is at least sixty times too many.

**Comment by habi** [comment]
OK, the emphasis is back to what it was before.
Only Markdown changes and added links remain.

**Comment by phihag** [comment]
Thank you very much for your contribution! Merged.

**Comment by habi** [comment]
Very welcome!

**Pull request merged**
