### PR TITLE
[downloader/f4m] Tolerate truncate segments when testing

### LINKED ISSUE #9214: error in a test of f4m manifest
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
python test_download.py TestDownload.test_Vice
[Vice] cowboy-capitalists-part-1: Downloading webpage
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading JSON metadata
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading mp4 JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading m3u8 JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading m3u8 information
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading hds JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading f4m manifest
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading rtmp JSON
[info] Writing video description metadata as JSON to: 43cW1mYzpia9IlestBjVpd23Yu3afAfp.info.json
[debug] Invoking downloader on 'http://cf.c.ooyala.com/43cW1mYzpia9IlestBjVpd23Yu3afAfp/43cW1mYzpia9IlestBjVpd23Yu3afAfp_4.f4m?hdcore=3.7.0'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 1
[download] Destination: 43cW1mYzpia9IlestBjVpd23Yu3afAfp.flv
[download] 100.0% of ~10.00KiB at Unknown speed ETA Unknown ETAE
======================================================================
ERROR: test_Vice (__main__.TestDownload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_download.py", line 141, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 734, in process_ie_result
    extra_info=extra_info)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 727, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1376, in process_video_result
    self.process_info(new_info)
  File "test_download.py", line 56, in process_info
    return super(YoutubeDL, self).process_info(info_dict)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1638, in process_info
    success = dl(filename, info_dict)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1580, in dl
    return fd.download(name, info)
  File "/home/amine/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/home/amine/youtube-dl/youtube_dl/downloader/f4m.py", line 377, in real_download
    _, box_type, box_data = reader.read_box_info()
  File "/home/amine/youtube-dl/youtube_dl/downloader/f4m.py", line 55, in read_box_info
    real_size = size = self.read_unsigned_int()
  File "/home/amine/youtube-dl/youtube_dl/downloader/f4m.py", line 37, in read_unsigned_int
    return struct_unpack('!I', self.read(4))[0]
struct.error: unpack requires a bytes object of length 4

----------------------------------------------------------------------
Ran 1 test in 49.840s

FAILED (errors=1)
```
---
the test fail with an error related to f4m downloader(after changing the ext from mp4 to flv).

### PR DESCRIPTION
**Pull request by yan12125**
Replaces #9216

Fixes #9214 and test_Bloomberg partially

@dstftw How about this "fix"?

### CODE REVIEW

**Comment by yan12125** [comment]
@remitamine test_Vice works for me. Please tell me if there are still problems.

BTW, the commit message should be truncated instead of truncate.

**Comment by dstftw** [comment]
I was considering this approach but there are couple of reasons I end up not to so:
1. Parse error may not be caused by truncation but by malformed data also (exotic situation though).
2. On parse when error segment is written as is we end up checking not a bare media payload but wrapped in envelope that may change thus producing different md5 (I did not test it).

**Comment by remitamine** [comment]
the test pass with the change in this PR.
without the change:
```
python test_download.py TestDownload.test_Vice
[Vice] cowboy-capitalists-part-1: Downloading webpage
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading JSON metadata
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading mp4 JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading m3u8 JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading m3u8 information
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading hds JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading f4m manifest
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading rtmp JSON
[info] Writing video description metadata as JSON to: 43cW1mYzpia9IlestBjVpd23Yu3afAfp.info.json
[debug] Invoking downloader on 'http://cf.c.ooyala.com/43cW1mYzpia9IlestBjVpd23Yu3afAfp/43cW1mYzpia9IlestBjVpd23Yu3afAfp_4.f4m?hdcore=3.7.0'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 1
[download] Destination: 43cW1mYzpia9IlestBjVpd23Yu3afAfp.flv
[download] 100.0% of ~10.00KiB at 254.64KiB/s ETA 00:00E
======================================================================
ERROR: test_Vice (__main__.TestDownload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_download.py", line 141, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 684, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 736, in process_ie_result
    extra_info=extra_info)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 684, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 729, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1378, in process_video_result
    self.process_info(new_info)
  File "test_download.py", line 56, in process_info
    return super(YoutubeDL, self).process_info(info_dict)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1640, in process_info
    success = dl(filename, info_dict)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1582, in dl
    return fd.download(name, info)
  File "/home/amine/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/home/amine/youtube-dl/youtube_dl/downloader/f4m.py", line 377, in real_download
    _, box_type, box_data = reader.read_box_info()
  File "/home/amine/youtube-dl/youtube_dl/downloader/f4m.py", line 55, in read_box_info
    real_size = size = self.read_unsigned_int()
  File "/home/amine/youtube-dl/youtube_dl/downloader/f4m.py", line 37, in read_unsigned_int
    return struct_unpack('!I', self.read(4))[0]
struct.error: unpack requires a bytes object of length 4

----------------------------------------------------------------------
Ran 1 test in 21.987s

FAILED (errors=1)
```
with the change(checked multiple times):
```
python test_download.py TestDownload.test_Vice
[Vice] cowboy-capitalists-part-1: Downloading webpage
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading JSON metadata
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading mp4 JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading m3u8 JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading m3u8 information
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading hds JSON
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading f4m manifest
[Ooyala] 43cW1mYzpia9IlestBjVpd23Yu3afAfp: Downloading rtmp JSON
[info] Writing video description metadata as JSON to: 43cW1mYzpia9IlestBjVpd23Yu3afAfp.info.json
[debug] Invoking downloader on 'http://cf.c.ooyala.com/43cW1mYzpia9IlestBjVpd23Yu3afAfp/43cW1mYzpia9IlestBjVpd23Yu3afAfp_4.f4m?hdcore=3.7.0'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 1
[download] Destination: 43cW1mYzpia9IlestBjVpd23Yu3afAfp.flv
[download] 100% of 10.38KiB in 00:00
.
----------------------------------------------------------------------
Ran 1 test in 13.553s

OK
```

**Comment by yan12125** [comment]
> Parse error may not be caused by truncation but by malformed data also (exotic situation though).

Should be resolved by introducing ```read_bytes()```

> On parse when error segment is written as is we end up checking not a bare media payload but one wrapped in envelope that may change thus producing different md5

Before this PR, some f4m manifests already contains unstable MD5 checksums. (6bdc2d5358c2843e3be4d073b2005e5196519664, 2beff95da5fb28440d26a3dee5de575c792d133c, etc.). I guess Adobe HDS protocol does not guarantee deterministic outputs, so it's OK to just comment out unstable checksums.

**Comment by yan12125** [comment]
A question: should I reuse ```ContentTooShortError```? Seems the semantic is somewhat different.

**Comment by dstftw** [comment]
I guess it's fine to use different exception but `FileTruncated` sounds strange for me when it's all about arbitrary portion of data.

**Comment by yan12125** [comment]
> ```FileTruncated``` sounds strange for me when it's all about arbitrary portion of data.

How about ```DataTruncatedError```?

**Comment by dstftw** [comment]
Sounds better.

**Comment by yan12125** [comment]
Renamed.

**Comment by dstftw** [comment]
Feel free to merge this.

**Comment by yan12125** [comment]
Landed as 1b405bb47d91119cc612a90d26f27f2b93f7c7b4.

**Pull request closed without merging**
