### PR TITLE
Added a "filename_hook" parameter to Python interface

### PR DESCRIPTION
**Pull request by CRImier**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Hello! I need the to sanitize the filenames myself since the existing functions do not satisfy me. Thus, I've added a way to add a hook that receives the filename generated by YoutubeDL and returns a filename that'll be used further down the line.

**Reasons:** with "restricted filenames", filenames are sanitized too much to the point of making the filename very ugly, and without "restricted filenames" I get characters that aren't compatible with the software I use. Also I plan to further integrate YoutubeDL with my music collection organizing scripts and such a feature would help. I already use it in my local version but I figure others could benefit from this as well.

**Sidenotes:** The hook is very likely to get called 2 or more times (since  ``process_filename`` is called quite often), but I can't see this causing any problems if we assume the processing function to always return same x for same y (which is the case for any reasonable sanitization function).

Example usage:

```
def filename_hook(filename):
    #An example hook - manual editing
    return raw_input('Edit this: "{}" : '.format(filename)).strip()

opts = {
"filename_hook":filename_hook,
"match_filter":print_info,
"outtmpl":"%(title)s",
"postprocessors":[{"key":'FFmpegExtractAudio', "preferredcodec":"mp3"}]
}
```

### CODE REVIEW

**Comment by dstftw** [comment]
Use `outtmpl` instead.

**Comment by CRImier** [comment]
No! You didn't even understand the purpose of this. Check this out:
```
def filename_hook(filename):
    filename = filename.replace(u'\u3010', u'[').replace(u'\u3011', u']')
    return filename
```
Can you show me a way to make this with ``outtmpl``?

**Comment by dstftw** [comment]
Easy:
```
def build_filename(info_dict):
    return 'whatever_filename_based_on_info_dict.%(ext)s'

ydl = youtube_dl.YoutubeDL()
info = ydl.extract_info('BaW_jenozKc', download=False)
for entry_info in info.get('entries', [info]):
    ydl.params['outtmpl'] = build_filename(entry_info)
    ydl.process_ie_result(entry_info)
```

Or just derive from `YoutubeDL` and override `prepare_filename`.

**Comment by CRImier** [comment]
Thank you very much, the "derive from YoutubeDL and override" way worked!

**Pull request closed without merging**
