### PR TITLE
Add instructions for using docker container

### PR DESCRIPTION
**Pull request by manishahluwalia**
I've created a docker container with dependencies. This change adds a pointer to the container with a template example for how to use it.

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by yan12125** [comment]
https://www.google.com/search?q=docker+youtube-dl is sufficient. I see no points to include it in README, unless you can point out how your image is a better choice.

**Comment by manishahluwalia** [comment]
My image has dependencies built in (e.g. ffmpeg, if you'd like to extract
audio; aria etc. if you'd like to try different downloaders; etc.).

Thanks

**Comment by manishahluwalia** [comment]
Wow, I didn't know you can do that! I'll look into automating that

Thanks for the suggestion!

**Comment by manishahluwalia** [comment]
Hi,

Looks like docker will let me set automatic build triggers for GitHub
projects, but I can only do it for my GitHub project youtube-dl-docker, or
for my fork of youtube-dl. Perhaps if I was a contributor to your
youtube-dl, it would let me set that up?

Alternatively, I will be happy to contribute my Dockerfile to your project
if you want all of these things to stay together?

Please let me know if either option works for you.

Thanks.

On Sat, Jan 7, 2017 at 2:00 PM, Manish Ahluwalia <manish.ahluwalia@gmail.com

**Comment by yan12125** [comment]
An option is trying the hooks in your fork and see whether it's possible to merge that.

**Comment by manishahluwalia** [comment]
Hi,

So the docker-githhub automated build process does not require any files to be checked into GitHub. So there is nothing for me to check-in and make a pull request. I basically create a [build from the docker hub web UI](https://docs.docker.com/docker-hub/builds/). I can only do this if I have some sort of administrative access to the GitHub repo, or if you have access to the docker hub.

Hence, we have 2 options:
1. You give me access to the youtube-dl GitHub repo. I will setup the automated build on docker.
2. I can give you (or anyone you designate) administrative access to my docker hub repo. This person can then setup the automated build. (I think this can be done, haven't tried it)
3. I can submit pull request submitting my dockerfile (and supporting assets) to your GitHub repo. Your GitHub project can then own everything, including the docker hub.

Please let me know what you'd prefer. If you'd rather not deal with this, then I'll stop bothering you. However, I think a user-friendly, easily-downloaded, dependency-complete docker container that just work out-of-the-box can be a great asset.

Thanks

**Comment by yan12125** [comment]
There are two primary principles:

1. Dockerfile should be publicly available
2. Docker images are automatically rebuilt when a new tag is created.

I prefer to put Dockerfile in this repository. If write access to this repository is necessary for automatic rebuild, I may ask rg3 to add you to collaborators. But first I'd like to have a look at the Dockerfile. There are more dependencies than aria2 and ffmpeg. For example, rtmpdump, atomicparsley, axel may be used too. And I've heard python in docker does not work well with non-ASCII characters. (http://bugs.python.org/issue28180) Does your version work fine?

**Pull request closed without merging**
