### PR TITLE
[streamango] Fix streamango extraction

### PR DESCRIPTION
**Pull request by gfabiano**
Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

I fixed Streamango extraction, now sources are encrypted

### CODE REVIEW

**Comment by hbiyik** [comment]
i can confirm that fix works

**Comment by nick-traeger** [comment]
I can confirm this too

**Comment by gfabiano** [comment]
@dstftw Here is needed a review.

**Comment by dungvaph03374** [comment]
I'm using latest version 2017.12.02 but seem streamango doesn't work, how can i apply this fix?

**Comment by nick-traeger** [comment]
https://streamango.com/embed/foqebrpftarclpob/asdf_asd_2_mp4 says "We are unable to find the video you're looking for.". So maybe we need a new link for the test.

**Pull request closed without merging**
