### PR TITLE
[kika] Add new extractor

### PR DESCRIPTION
**Pull request by Hakuba**

### CODE REVIEW

**Comment by dstftw** [comment]
I'm working on this atm, it's identical to mdr extractor.

**Comment by jaimeMF** [comment]
Thanks cherry picked in 892015b088fa21915270b0a05937fcc7063ccdd2 and 47f2d01a5ac074f6959aa12e8bc00310f18a54e8. I replaced some tests in 8c1aa28c27af204c4996260cdc70359e83c2c3d6 and cleanup a bit in c3040bd00a43e111dab0d1ab903df03ac7d19a00.

**Comment by jaimeMF** [comment]
> I'm working on this atm, it's identical to mdr extractor.

Sorry, I didn't notice.

**Comment by dstftw** [comment]
Merged with mdr in 2b1b2d83cacfdce19cae5eea2f9bbfd142efc7f1.

**Comment by Hrxn** [comment]
Makes sense, the KiKA channel is run by the MDR

**Pull request closed without merging**
