### PR TITLE
[bilibili] use xpath_text and catch errors in xml document

### PR DESCRIPTION
**Pull request by remitamine**

### CODE REVIEW

**Comment by dstftw** [comment]
You can commit right in master.

**Comment by remitamine** [comment]
when i try to commit directly i get this:
```
git push upstream master 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/rg3/youtube-dl.git/'
```

**Comment by dstftw** [comment]
What's your `git remote -v`?

**Comment by remitamine** [comment]
git remote -v
origin	git@github.com:remitamine/youtube-dl (fetch)
origin	git@github.com:remitamine/youtube-dl (push)
upstream	https://github.com/rg3/youtube-dl.git (fetch)
upstream	https://github.com/rg3/youtube-dl.git (push)

**Comment by dstftw** [comment]
Re-add upstream with `git@github.com:rg3/youtube-dl.git` address.

**Pull request merged**
