### PR TITLE
Added WEBVTT subtitle support for TV4.

### PR DESCRIPTION
**Pull request by johan-westin-private**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ x] Bug fix
- [ x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by johan-westin-private** [comment]
Hi, please point me to the PR that shall take care of this. The TV4 subs has been boken for more than 40 days. Regards, Johan Westin

**Comment by Sopor** [comment]
@johan-westin-private Do subtitles work for TV4 now? I did not manage to download any :(

**Comment by johan-westin-work** [comment]
Hi, I have a working fork. It was not accepted for merge though.

**Comment by johan-westin-private** [comment]
Hi, I have a working fork. It was not accepted for merge though.

**Comment by Sopor** [comment]
@johan-westin-private I see, but if it still not working why call this a dupe? I didn't manage to get audio either but i probably doing something wrong :(

**Pull request closed without merging**
