### PR TITLE
[mediaset] Add new extractor

### PR DESCRIPTION
**Pull request by timendum**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] New extractor

---

New extractor for www.video.mediaset.it

### CODE REVIEW

**Comment by dstftw** [comment]
Do you want to be credited as one of the authors of youtube-dl? If so under what name?

**Comment by timendum** [comment]
Thanks for the question; the answer is yes, if possible, timendum is ok.


Timendum

On May 22, 2017 19:12, "Sergey M." <notifications@github.com> wrote:

Do you want to be credited as one of the authors of youtube-dl? If so under
what name?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rg3/youtube-dl/pull/12964#issuecomment-303162517>, or mute
the thread

**Comment by dstftw** [comment]
`Timendum` or `timendum`?

**Comment by timendum** [comment]
Timendum

Thank you

**Pull request closed without merging**
