### PR TITLE
add build status,i was having it to build extractors

### PR DESCRIPTION
**Pull request by siddht1**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ x] Improvement
- [ ] New extractor
- [ ] New feature

---
please add build status,I am using to test my own fork

### CODE REVIEW

**Comment by dstftw** [comment]
It's pointless since it's always failing due to extractors.

**Comment by siddht1** [comment]
still I am using it in my fork,
what are all the travis ci build you implement?

**Comment by dstftw** [comment]
Express your questions in understandable form.

**Comment by siddht1** [comment]
the travis ci docker implementation through which you are testing the builds automatically,has python enviroments i.e 2.6 to 3.6,so my question is what is the purpose of env:- YTDL_TEST_SET=core,- YTDL_TEST_SET=download  for,they literally are running from 30 mins for my commit.

I am using the build identifier to check it realtime in my own fork.

**Comment by dstftw** [comment]
`core` is youtube-dl core that must never fail, `download` is extractors part that may fail.

**Comment by siddht1** [comment]
can i become a contributor in youtube-dl in any other form

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues?q=is%3Aopen+is%3Aissue

**Pull request closed without merging**
