### PR TITLE
[youtube] Added argument --write-tags, that ads the list of tags to t…

### PR DESCRIPTION
**Pull request by purdeaandrei**
…he end of the description file. Implies --write-description.

### CODE REVIEW

**Comment by dstftw** [comment]
Why not just use `--write-info-json`?

**Comment by purdeaandrei** [comment]
well, indeed, only the changes in youtube.py are necessary in that case.

I like having the option of including the keyword in the description too, but of course whoever merges it will decide if they want to merge it. I will make another pull-request with just the youtube.py changes that adds the tags to the json.

**Comment by dstftw** [comment]
I see little sense adding `--write-*` option for an arbitrary field until there is a clear rationale and purpose (e.g. some well defined format consumed by a 3rd party software).

**Comment by purdeaandrei** [comment]
Well, one could argue that it better matches what you see when you click "Show More" on youtube. But really to argue that, one would also have to add the other fields that are showed there, not just Keywords, so I see your point :)

**Pull request closed without merging**
