### PR TITLE
Introduce chapter and series fields

### PR DESCRIPTION
**Pull request by dstftw**
This PR proposes some new optional fields to video info dictionary in order to cover the gap for videos organized to logical chapters and video episodes belonging to season of a series or a programme.

Field | Usage | Description
------------ | ------------- | -------------
`chapter` | chapter-only | Name or title of the chapter the video belongs to.
`chapter_number` | chapter-only | Number of the chapter the video belongs to, as an integer.
`chapter_id` | chapter-only | Id of the chapter the video belongs to, as a unicode string.
`series` | series-only | Title of the series or programme the video episode belongs to.
`season` | series-only | Title of the season the video episode belongs to.
`season_number` | series-only | Number of the season the video episode belongs to, as an integer.
`season_id` | series-only | Id of the season the video episode belongs to, as a unicode string.
`episode` | series-only | Title of the video episode. Unlike mandatory video `title` field, this field should denote the exact title of the video episode without any kind of decoration.
`episode_number` | series-only | Number of the video episode within a season, as an integer.
`episode_id` | series-only | Id of the video episode, as a unicode string.

Notes:
* `*_id` fields are not `*_index` (i.e. numeric) in order to tolerate some potential exotic naming schemas apart from autoincremented numbering.
* `episode` is supposed to be potentially different from `title` and should denote the exact name of the video episode while `title` is allowed to be decorated and imposes less strictness (e.g. can contain the title displayed on a website that is not necessarily should match episode name).

Pros:
* Collecting and providing this potentially useful information.
* An elegant way to solve issues like #4793 with help of output templates.

Cons:
* Duplicated fields for videos.

### CODE REVIEW

**Comment by dstftw** [comment]
I'm going to merge this if no objections or field naming suggesstions.

**Comment by jaimeMF** [comment]
Why do `*_id` fields accept integers? Wouldn't it be more consistent to just use unicode strings? This could be problematic if we allow in the future to specify the number of digits for numeric fields in the output template, it would cause `TypeError`s  if it's a string.

**Comment by dstftw** [comment]
Accepting only unicode strings would involve boilerplate `compat_str` wrapping in extractors. As for output template, one obviously should not use numeric formatters for fields that can potentially be non-numeric, at the same time `%s` forks just fine for numeric fields.

**Comment by dstftw** [comment]
Alternatively `*_index` fields may also be introduced with numeric semantics.

**Comment by jaimeMF** [comment]
> Accepting only unicode strings would involve boilerplate compat_str wrapping in extractors since most of the time these fields are originally integers.

It's not that common but it also happens with the `id` field: sometimes we have to convert from an integer (usually coming from a JSON file). Since we can't guarantee that every site uses numeric episode ids I think it's more reasonable to just use a single type.

> As for output template, one obviously should not use numeric formatters for fields that can potentially be non-numeric, at the same time %s forks just fine for numeric fields.

You are right, but some people like to use 0 for padding numbers in filenames and they will eventually ask it. So your suggestion of using `*_index` sound good.

By the way: are you aware of any supported site that use non-numeric ids?

**Comment by dstftw** [comment]
I remember some used string identifiers for seasons but it's more like unique identifiers rather that an indexes.

**Comment by dstftw** [comment]
Added `*_number` fields.

**Comment by dstftw** [comment]
I'm merging this. Further suggestions and improvements to be committed right in master.

**Pull request merged**
