### PR TITLE
Expose information to --exec (anything to fix?)

### PR DESCRIPTION
**Pull request by joncody**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

================================================================================

I wanted to be able to download playlists and set the correct track number, title, album, artist, and year automatically so this simple, minor addition exposes the info object to the `--exec` argument.  The `info` object is a copy of the `information` object with its string values formatted via `compat.compat_shlex_quote` - this way we can now leverage `cmd % info` as opposed to `cmd.replace` and access `info`'s properties like so `--exec "id3v2 -T %(playlist_index)s -t %(title)s -a 'artist' -A 'album' -y year %(filepath)s"`.

Example:
```bash
mkdir -p ~/Music/Orjan\ Nilsen/No\ Saint\ Out\ Of\ Me/ && cd ~/Music/Orjan\ Nilsen/No\ Saint\ Out\ Of\ Me/
youtube-dl -v --continue --no-part --xattrs -x --audio-format mp3 --audio-quality 0 --add-metadata --xattrs -o "%(playlist_index)s - %(title)s.%(ext)s" --exec "id3v2 -T %(playlist_index)s -t %(title)s -a 'Orjan Nilsen' -A 'No Saint Out Of Me' -y 2015 %(filepath)s" PL6l8d10atvR6hym1YRQtUfVgw53yg50CR
```

### CODE REVIEW

**Comment by dstftw** [comment]
1. Old syntax must work as before.
2. `YoutubeDL.prepare_filename`.

**Comment by joncody** [comment]
Old syntax does work as before.  It's the same object passed to prepare_filename; except the string values are replaced with the their result when passed to compat.compat_shlex_quote; then we just call cmd % info.

**Comment by joncody** [comment]
@dstftw .

**Comment by dstftw** [comment]
Old syntax is `--exec 'blah {} blah'`. It does not matter whether new is more appropriate or not. **You break backward compatibility with this**. Old syntax must keep working.

**Comment by joncody** [comment]
Uhhhh, I updated it dude.

**Comment by joncody** [comment]
youtube-dl --verbose --continue --no-part --extract-audio --audio-format mp3 --audio-quality 0 --add-metadata --xattrs --output "%(playlist_index)s - %(title)s.%(ext)s" --exec "id3v2 -T %(playlist_index)s -t %(title)s -a 'Orjan Nilsen' -A 'In My Opinion' -y 2011 {}" PLfaD6LVBKOy7dizbyKpRvfGrc_V9BNPcU

Tested on Python 2.7.12 and Python 3.5.2

**Comment by joncody** [comment]
@dstftw https://github.com/rg3/youtube-dl/pull/16126/commits/1416f2e7bc97d7844dcfdf1ef62a5dfca5815cea

**Comment by dstftw** [comment]
You must use substitution code from `YoutubeDL.prepare_filename`. Extract it in separate routine and share the implementation.

**Comment by joncody** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L1701-L1970

prepare_filename is always called before post_process, and its result is stored in info_dict which is then passed to post_process.  I think you need to reread the source code and understand what's going on if you want to be a maintainer, or at least spend a little more time giving me the benefit of the doubt.

**Comment by joncody** [comment]
Keep in mind, I've only changed one file.

https://github.com/joncody/youtube-dl/blob/master/youtube_dl/postprocessor/execafterdownload.py

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/execafterdownload.py

**Comment by joncody** [comment]
https://github.com/rg3/youtube-dl/pull/16126/files#diff-016380f00f5a19c39b33986eee7e5840

**Comment by dstftw** [comment]
Do you read my posts at all? I'll repeat for the special one:
You must **extract substitution code** from **`YoutubeDL.prepare_filename`** into **separate routine** that you must use in **`YoutubeDL.prepare_filename`** as well as in **your code** because you substitution implementation  is completely broken (breaks on missing keys (`%(missingkeyhere)s`), does not have additional calculated keys (epoch, etc), and many more).

**Comment by joncody** [comment]
First of all use the right keys.  Second of all, I'm not going to do something redundant.

**Comment by joncody** [comment]
Additional keys?  There was only one key prior to my implementation, and it was information['filepath'].  All I've done is made the entire information object accessible - WITHOUT BREAKING THE OLD IMPLEMENTATION.  If you want additional keys, make another pull request.

**Comment by joncody** [comment]
And uh, prepare_filename only returns one string, the filename.

**Comment by dstftw** [comment]
There are no such thing as **right key**. **Any key** may be **missing** breaking your code completely since every key apart from title is **optional**. That's not redundant, that how it must work. I don't need semi broken functionality. If you want this feature to get merged you'll have to implement it properly.

>Additional keys? There was only one key prior to my implementation, and it was information['filepath']

There were **no keys** prior to this PR. At all. This is what you are **adding right now**. And since you're adding it bother to add **all keys** mentioned in output template section. Again as said I don't need semi working options.

**Comment by joncody** [comment]
It's not a filename.

**Comment by joncody** [comment]
I know what you are looking for and I will implement the change and then make the commit.

**Comment by joncody** [comment]
@dstftw anything to fix?

**Comment by joncody** [comment]
??

**Comment by joncody** [comment]
I was still encountering errors when downloading tracks containing single quotes (apostrophes -_-).  I'm going to close this for now, as I don't see it being ready to merge nor do I see it gaining any interest.  In the future, before opening a Pull Request, I will ensure I have working 'youtube-dl' quality code.  Thanks.

**Pull request closed without merging**
