### PR TITLE
crooksandliars.com extractor

### PR DESCRIPTION
**Pull request by fstirlitz**
And by the way, I wish the generic extractor would simply download the webpage and match all extractors against all the iframe and embed tags in the webpage. Could have saved me a bit of trouble.

### CODE REVIEW

**Comment by yan12125** [comment]
All tests failed due to missing 'ext' attribute in 'info_dict'. Please fill in the field.

**Comment by fstirlitz** [comment]
What is it supposed to be set to? This particular video is available as both WebM and mp4. I don't see the point in specifying 'ext' in the test at all.

**Comment by yan12125** [comment]
It should be the extension of the best quality video file.

**Comment by dstftw** [comment]
Thanks.

**Pull request merged**
