### PR TITLE
Provide MPD url and segment durations in JSON

### PR DESCRIPTION
**Pull request by wiiaboo**
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] New feature

---

mpv is planning to support segmented dash support that would need potentially both these commits.

### CODE REVIEW

**Comment by yan12125** [comment]
Hi, could you split the two changes into two pull requests? The idea of ```dash_mpds``` is not so good. I suggest adding a new field, maybe ```manifest_url```, to ```formats```, so that f4m and hls can use it as well. Also, don't forget to [document it](https://github.com/rg3/youtube-dl/blob/0def758/youtube_dl/extractor/common.py#L85-L145).

**Comment by remitamine** [comment]
i already proposed to return the mpd_url in #8848 and #9109 the will return the url according to the standard and without in introducing a new field in the info dict.

**Comment by yan12125** [comment]
I see both PRs closed. Are they incomplete yet?

**Comment by remitamine** [comment]
no, #9109 replaces #8848 with more improvments, but maintaining it for a long time was difficult(handle lots of merge conlicts) and also some of the code in the pull request was introduced in the master(handling `$Time` in media_template) branch which make some of duplication in the functionality.

**Comment by wiiaboo** [comment]
I don't see the dash mpd urls or segment duration anywhere on -J from master.

**Comment by yan12125** [comment]
> mpv needs at least one of these to support http_dash_fragments.

Then could you remove the line ```dash_mpds```? Other changes are less controversial.

**Comment by remitamine** [comment]
i don't think that it's a good idea for mpv to depend on the segement urls in the info dict, in my opinion the only information that should be returned about dash formats is the url of the mpd manifest.

**Comment by yan12125** [comment]
@remitamine I guess your concern is that fields like ```segment_urls``` are for youtube-dl internal uses only and may change at any time? Then the way to go is #9109.

**Comment by remitamine** [comment]
> I guess your concern is that fields like segment_urls are for youtube-dl internal uses only and may change at any time?

yes.
> Then the way to go is #9109.

it should be created again as there was a lot of changes since the #9109 was created, for now i think that #9937 is more important to be processed than #9109 , if it's acceptable i can push the code to return the mpd url directly to master branch, than i will try to open another PR for the other changes after #9937 merged.

**Comment by yan12125** [comment]
OK I'll look at #9937 first. By the way, I've opened a milestone at https://github.com/rg3/youtube-dl/milestone/6 to track all relevant pull requests and issues. Hope that reduces some headaches.

**Comment by dstftw** [comment]
Will be available in the next version as:
```json
"formats" : {
  ...
  "manifest_url": "http://manifest/url.mpd",
  "fragments": [
    {
      "url": "http://fragment1/url",
      "duration": 0,
    },
    {
      "url": "http://fragment2/url",
      "duration": 0,
    },
    ...
  ]
  ...
}
```

**Pull request closed without merging**
