### PR TITLE
[adobepass] Add Playstation Vue login

### LINKED ISSUE #11878: Please add support for Playstation Vue logins
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.29**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

If you go to https://www.playstation.com/en-us/network/vue/ you can sign up for a free trial of Playstation Vue if you have a PlayStation Network account, and you just have to remember to cancel it within a week to not get billed for it if you don't want it.  I have read in several places that a Playstation Vue login can be used in place of a cable or satellite provider login on several of the streaming sites, therefore if you could add Playstation Vue to the list of supported MSO's then perhaps youtube-dl would be able to download files from those services without the need for a separate cable or satellite subscription.

### PR DESCRIPTION
**Pull request by gkoelln**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Adding support for Playstation Vue logins and hopefully any MSO that's added to the dict.  Fixes #11878.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.fox.com/watch/911715395559', '--ap-mso', 'sony_auth-gateway_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-o', 'C:\\Users\\Greg\\Videos\\%(title)s.%(ext)s', '--test', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.6.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.3
[debug] Proxy map: {}
[FOX] 911715395559: Downloading webpage
[FOX] 911715395559: Downloading Provider Redirect Page
[FOX] 911715395559: Downloading Provider Login Page
[FOX] 911715395559: Downloading Provider Login Page
[FOX] 911715395559: Downloading Provider Login Page
[FOX] 911715395559: Logging in
[FOX] 911715395559: Logging in
[FOX] 911715395559: Logging in
[FOX] 911715395559: Confirming Login
[FOX] 911715395559: Confirming Login
[FOX] 911715395559: Confirming Login
[FOX] 911715395559: Confirming Login
[FOX] 911715395559: Retrieving Session
[FOX] 911715395559: Retrieving Authorization Token
[FOX] 911715395559: Retrieving Media Token
[ThePlatform] G3aA1RN7K8oK: Downloading SMIL data
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Checking video URL
[ThePlatform] G3aA1RN7K8oK: Downloading JSON metadata
[debug] Invoking downloader on 'http://dlv.fox.com/Fox.com/403/395/TheSimpsons_WABF12_911722563561_mp4_video_1280x720_2500000_primary_audio_8.mp4?__gda__=1491313556_7644c0d32de7a1dcefa8a394959f6764'
[download] Destination: C:\Users\Greg\Videos\Caper Chase.mp4
[download] 100% of 10.00KiB in 00:00
```

### CODE REVIEW

**Comment by gkoelln** [comment]
I'm sorry. I can't seem to squash or remove all of the merge requests.

**Comment by fivehorizons** [comment]
@gkoelln does this still work for VUE?   I think the main login page does have a captcha no robot check box

**Comment by gkoelln** [comment]
@fivehorizons - I’ve had mixed results with it, though part of my problem was forgetting that I had changed my PSVue password. I’m just now noticing the branch conflicts here and I may look into them soon.  All I can say is that I make no guarantees, but you can try it, if you like.

**Comment by fivehorizons** [comment]
@gkoelln thanks I will give it a try.  Will this type of auth make the stream or download not time or expire after 3 hours or so?  Seems the hls stream urls expire or the token does

**Comment by gkoelln** [comment]
I haven’t noticed any timeouts.

**Comment by fivehorizons** [comment]
@gkoelln Do you have some examples of the vue urls that you made work?   This is what I have.   

http://tbs-cnn-live-sonytv-i.akamaihd.net/npid=E4761B5F0631DE9234D71C474727B3CEED239EA964C29ED70D80A242FCEF40A9&deviceid=web2-w&e=1514812150&hmac=1458e751c17e09414fc60a1d40ca389f11d89fa9/PROD08/sony/TBS_CNN/live/master_wired_ads.m3u8

http://tbs-cnn-live-sonytv-i.akamaihd.net/npid=E4761B5F0631DE9234D71C474727B3CEED239EA964C29ED70D80A242FCEF40A9&deviceid=web2-w&e=1514812150&hmac=1458e751c17e09414fc60a1d40ca389f11d89fa9/PROD08/sony/TBS_CNN/live/2017/12/19/10426087/4500K/4500_slide_ads.m3u8

**Comment by gkoelln** [comment]
I should clarify that this is intended as a login provider for other sites, such as fox.com, cbs.com, abc and go sites, etc. I’ve not actually tested it for vue.playstation.com pages.

**Comment by fivehorizons** [comment]
@gkoelln I know this isn’t the place but not sure how to communicate with you outside of here.   I’m looking for some help on some side projects and could use your input.   You can contact me if you wish at zmclean at gmail dot com 

We can discuss donation as well :)

**Comment by gkoelln** [comment]
I've decided to close this branch, since I've caused some problems in my own account after Playstation Network blacklisted my IP, thinking there was malicious activity.  I don't want this to happen to anyone else.

**Comment by darkhelmet2016** [comment]
Use getflv for some sites with the log in and have done so for years and they have not said one word about my info as long as am on the same home network use for streaming from the website and use the right zip code. only certain sites would cause an issue like fox as they are tied to your home location.

**Pull request closed without merging**
