### PR TITLE
[bilibili] Fix extractor

### LINKED ISSUE #15430: [bilibili] RegexNotFoundError: Unable to extract player parameters
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
youtube-dl https://www.bilibili.com/video/av16492411/
[BiliBili] 16492411: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

(base) C:\Users\Thomas\temp>youtube-dl -v https://www.bilibili.com/video/av16492411/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av16492411/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[BiliBili] 16492411: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\bilibili.py", line 98, in _real_extract
    webpage, 'player parameters'))['cid'][0]
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player parameters;

```

---

### PR DESCRIPTION
**Pull request by Jicksaw**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Closes  #15430. Also adds some optional fields and fixes episode downloads (test 4).

### CODE REVIEW

**Comment by Jicksaw** [comment]
The URL in #15430 is again serving the original html and I couldn't find any pages currently serving the new type. The test 4 fixes are still necessary.

**Comment by yanpe** [comment]
This is the same issue as #15430.
youtube-dl.exe https://www.bilibili.com/video/av18949871 --verbose

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.bilibili.com/video/av18949871', '--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 18949871: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\extractor\bilibili.py", line 98, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\extractor\common.py", line 794, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by oseansdeep** [comment]
能解决“Unable to extract player parameters” 这个问题吗？我照着修改了代码，还是这个问题。。

**Comment by zhEdward** [comment]
@Jicksaw  Hi   i clone `master` branch and replace `bilibili.py` from your branch to  test url https://www.bilibili.com/bangumi/play/ep172167 seem did't work. use  url `.../ep40062`  you written in Test case will download success. 

```python
(test-bilibili)⚡ [1] % python -m youtube_dl -v https://www.bilibili.com/bangumi/play/ep172167          ~/Desktop/zhidian/youtube-dl
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bilibili.com/bangumi/play/ep172167']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.22
[debug] Git HEAD: b5cbe3d
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[BiliBili] 172167: Downloading webpage
[BiliBili] Downloading episode 172167. To download all videos in anime 11712, re-run youtube-dl with https://bangumi.bilibili.com/anime/11712
[BiliBili] 172167: Downloading JSON metadata
[BiliBili] 172167: Downloading video info page
ERROR: BiliBili said: video is hidden
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/bilibili.py", line 169, in _real_extract
    self._report_error(video_info)
  File "youtube_dl/extractor/bilibili.py", line 114, in _report_error
    raise ExtractorError('%s said: %s' % (self.IE_NAME, result['message']), expected=True)
ExtractorError: BiliBili said: video is hidden

```

is relevant with  `_BILIBILI_KEY` or `_APP_KEY`?

**Pull request closed without merging**
