### PR TITLE
Regex pattern update to match more codecs (fixes #6858)

### LINKED ISSUE #6858: Some formats not filterable because of characters not specified in str_operator_rex regex
Example format:

```
youtube-dl --list-formats "https://www.youtube.com/watch?v=bxnd_gWhWB0"                       
[youtube] bxnd_gWhWB0: Downloading webpage
[youtube] bxnd_gWhWB0: Downloading video info webpage
[youtube] bxnd_gWhWB0: Extracting video information
[youtube] bxnd_gWhWB0: Downloading DASH manifest
[youtube] bxnd_gWhWB0: Downloading DASH manifest
[info] Available formats for bxnd_gWhWB0:
format code  extension  resolution note
249          webm       audio only DASH audio   52k , opus @ 50k, 8.58MiB
250          webm       audio only DASH audio   63k , opus @ 70k, 10.10MiB
171          webm       audio only DASH audio   84k , vorbis@128k (44100Hz), 13.92MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, aac  @128k (44100Hz), 22.42MiB
251          webm       audio only DASH audio  133k , opus @160k, 21.92MiB
141          m4a        audio only DASH audio  256k , m4a_dash container, aac  @256k (44100Hz), 44.53MiB
278          webm       256x144    DASH video   89k , webm container, vp9, 15fps, video only, 12.55MiB
160          mp4        256x144    DASH video  115k , avc1.4d400c, 15fps, video only, 19.05MiB
242          webm       426x240    DASH video  158k , vp9, 30fps, video only, 16.48MiB
133          mp4        426x240    DASH video  250k , avc1.4d4015, 30fps, video only, 42.59MiB
243          webm       640x360    DASH video  265k , vp9, 30fps, video only, 31.04MiB
134          mp4        640x360    DASH video  365k , avc1.4d401e, 30fps, video only, 45.30MiB
244          webm       854x480    DASH video  579k , vp9, 30fps, video only, 60.18MiB
135          mp4        854x480    DASH video  896k , avc1.4d401f, 30fps, video only, 99.03MiB
13           3gp        unknown    small 
17           3gp        176x144    small ,  mp4a.40.2, mp4v.20.3
36           3gp        320x240    small ,  mp4a.40.2, mp4v.20.3
5            flv        400x240    small 
43           webm       640x360    medium ,  vorbis, vp8.0
18           mp4        640x360    medium ,  mp4a.40.2, avc1.42001E (best)
```

Say I wanted to prefer the best possible `avc` format, I'm not sure how I could. I tried: 

```
$ youtube-dl -f "bestvideo[vcodec=avc1.4d401f]+bestaudio" "https://www.youtube.com/watch?v=bxnd_gWhWB0
```

But couldn't because the dot (`.`) is not part of the regex:

```
            str_operator_rex = re.compile(r'''(?x)
                \s*(?P<key>ext|acodec|vcodec|container|protocol)
                \s*(?P<op>%s)(?P<none_inclusive>\s*\?)?
                \s*(?P<value>[a-zA-Z0-9_-]+)
                \s*$
```

Which only seems to allow alphanumeric, dash and underscore for some reason.

What I'm actually looking for is some sort of wildcard:

```
$ youtube-dl -f "bestvideo[vcodec=avc1.*]+bestaudio" "https://www.youtube.com/watch?v=bxnd_gWhWB0
```

Or, better yet, some sort of normalization, since as far as I understand it, [avc1 is h264](http://www.digitalpreservation.gov/formats/fdd/fdd000081.shtml). Can anybody tell me why normalization would be undesirable?

### PR DESCRIPTION
**Pull request by dyn888**
Added dot '.' for regex pattern to match more codecs, as pointed out by @aktau: https://github.com/rg3/youtube-dl/issues/6858

### CODE REVIEW

**Comment by yan12125** [comment]
This fix looks good. Could you add some tests to [test_YoutubeDL.py](https://github.com/rg3/youtube-dl/blob/ed7cd1e859cf97e975a28a5e8c58a1d1aca819fe/test/test_YoutubeDL.py)?

**Comment by dyn888** [comment]
Added for vcodec, it will produce error with current regex, and it will pass after this patch.

**Comment by yan12125** [comment]
Thanks @dyn888! Would you like to be listed in [AUTHORS](https://github.com/rg3/youtube-dl/blob/master/AUTHORS)? If so, under what name?

**Comment by dyn888** [comment]
Yes, that would be great, use this name: `Saso Bezlaj`

Thanks!

**Comment by yan12125** [comment]
Done in 29f46c2bee3641efcf2c06c3d173baf7a41010af.

**Comment by dyn888** [comment]
Thanks a lot! :)

**Pull request merged**
