### PR TITLE
[youtube] itag 272 has 4320 lines

### PR DESCRIPTION
**Pull request by zaps166**

### CODE REVIEW

**Comment by jaimeMF** [comment]
Do you have an example URL? In #3128 it's reported as 2160p.

**Comment by zaps166** [comment]
E.g.: https://www.youtube.com/watch?v=sLprVF6d7Ug - youtube_dl downloads f272, size: 7680x4320

272 format tested also here: https://github.com/zaps166/QMPlay2/commit/71c7a6c6264ceae7bebdd6a6cc2e3e216433c845

**Comment by dstftw** [comment]
This is not always the case: RtoitU2A-3E
```
>youtube-dl RtoitU2A-3E -f 272
...
[download] Destination: 140611  (Trouble Maker) -    -RtoitU2A-3E.webm
[download] 100% of 551.40MiB in 02:55

>ffmpeg.exe -i "140611  (Trouble Maker) -    -RtoitU2A-3E.webm"
...
  Duration: 00:03:27.77, start: 0.000000, bitrate: 22262 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv), 3840x2160, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
```

**Comment by dstftw** [comment]
Moveover hardcoded metadata from `_formats` is only used when DASH manifest lacks this information that is not the case most of the time. So I don't see any problem here.

**Comment by zaps166** [comment]
Ok!

**Pull request closed without merging**
