### PR TITLE
[vidme:user] Fix extraction when username contains dash or underscore

### PR DESCRIPTION
**Pull request by theychx**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Vid.me usernames can contain dashes and underscores. This PR fixes the VALID_URL regex for [vidme:user] and [vidme:user:likes], in order to reflect this.

https://vid.me/unsQuare_netWork
https://vid.me/Kaleidoscope-Ish

### CODE REVIEW

**Comment by dstftw** [comment]
Add tests.

**Comment by theychx** [comment]
I added the requested tests. Unfortunately there is a really weird problem with the new regex, which for some reason only manifests itself with [vidme:user:likes]. On some runs with url's containing usernames with dash/underscore everything is ok, and then on other runs it fails like those characters were not matched. Like so:

```
$ python test/test_download.py TestDownload.test_VidmeUserLikes_1
[vidme:user] Kaleidoscope: Downloading JSON metadata                           
[download] Downloading playlist: Kaleidoscope - Videos                         
[vidme:user] Kaleidoscope: Downloading user list page 1                        
[vidme:user] playlist Kaleidoscope - Videos: Downloading 0 videos              
[download] Finished downloading playlist: Kaleidoscope - Videos                
F                  
======================================================================         
FAIL: test_VidmeUserLikes_1 (__main__.TestDownload):                           
----------------------------------------------------------------------         
Traceback (most recent call last):     
  File "test/test_download.py", line 178, in test_template                     
    expect_info_dict(self, res_dict, test_case.get('info_dict', {}))           
  File "/home/benno/python/ytdl/youtube-dl/test/helper.py", line 177, in expect_info_dict
    expect_dict(self, got_dict, expected_dict)                                 
  File "/home/benno/python/ytdl/youtube-dl/test/helper.py", line 173, in expect_dict
    expect_value(self, got, expected, info_field)                              
  File "/home/benno/python/ytdl/youtube-dl/test/helper.py", line 167, in expect_value
    'Invalid value for field %s, expected %r, got %r' % (field, expected, got))
AssertionError: 'Kaleidoscope-Ish - Likes' != 'Kaleidoscope - Videos'          
- Kaleidoscope-Ish - Likes             
+ Kaleidoscope - Videos                
 : Invalid value for field title, expected 'Kaleidoscope-Ish - Likes', got 'Kaleidoscope - Videos'

----------------------------------------------------------------------         
Ran 1 test in 1.618s                   

FAILED (failures=1)                    
```

**Comment by theychx** [comment]
I also replaced the original test for [vidme:user] as the url was pointing to deleted content.

**Comment by dstftw** [comment]
1. Breaks `test_all_urls.py`.
2. Tests should be `only_matching`.

**Comment by theychx** [comment]
Regex should be fixed now, `test_all_urls.py` now succeeds.

**Pull request closed without merging**
