### PR TITLE
Simplify audioquality option parsing logic.

### PR DESCRIPTION
**Pull request by FooBarQuaxx**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

A **minuscule** code improvement while parsing audioquality option.

### CODE REVIEW

**Comment by dstftw** [comment]
I don't see any point in this change.

**Comment by FooBarQuaxx** [comment]
You don't think that the logic is just a wee clearer this way?

**Comment by dstftw** [comment]
No, it's not cleaner. I just want to strip `k` and `K`. I don't want to lowercase it.

**Comment by yan12125** [comment]
How about: ```.strip('Kk')```. Such a usage is supported [since Python 2.2](https://docs.python.org/2.6/library/stdtypes.html?highlight=strip#str.strip)

**Pull request closed without merging**
