### PR TITLE
[FetLife] Add new extractor

### PR DESCRIPTION
**Pull request by motophil**
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] New extractor

Added extractor for fetlife.com. Videos on fetlife.com only work with a pay-account, a free account is not sufficent, and no, I'm not going to offer mine for testing. 

I am aware that this means this extractor will probably not be added, and it also means that the test fails.
By posting this pull request people will be able to find this extractor and make their own youtube-dl that supports fetlife.

### CODE REVIEW

**Comment by motophil** [comment]
How do i run a test on an extractor that needs to log in? 
python test/test_download.py TestDownload.test_FetLife
doesn't work and doesn't take login parameters.

**Comment by dstftw** [comment]
Cause you did not provide any login parameters in test.

**Comment by yan12125** [comment]
Hello, please remove changes to gaskrank.py from this pull request - there are conflicts

**Comment by motophil** [comment]
Hope this fixed it.

**Comment by yan12125** [comment]
Technically that works, but there are too many gaskrank-related commits. Could you create a new commit with fetlife only?

**Comment by motophil** [comment]
Removed gaskrank.py and the reference to it in extractors.py - is that what you mean?
Sorry, I'm not quite sure if I get what you want.

**Comment by yan12125** [comment]
Oops I might be misleading.

Currently there are 15 commits in this PR. Some are for fetlife and some are for gaskrank. What I want is remove gaskrank commits and leave those starting with [FetLife]. After that there should be 8 FetLife commits (the last one not included)

FYI, ```git rebase -i``` can do that, see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by motophil** [comment]
Sorry, I'm stuck here.

To be sure, I started clean:
git clone git@github.com:motophil/youtube-dl.git
cd youtube-dl/
git checkout -b FetLife origin/FetLife
git rebase -i HEAD~15

Now change the 'pick' to 'fixup' here:
fixup 1679793 [gaskrank] Add new extractor
fixup 5de648f [gaskrank] Add new extractor - fixes as requested
fixup 274f73b [gaskrank] Add new extractor - style fix
fixup 015e4ed [Gaskrank] Add new extractor - requested fixes

...and leaving the editor I get this message:

[detached HEAD e0a693c] [nick] Add support for beta.nick.com (closes #11655)
 Author: Sergey M․ <dstftw@gmail.com>
 Date: Tue Jan 10 22:32:34 2017 +0700
 3 files changed, 55 insertions(+), 1 deletion(-)
 create mode 100644 youtube_dl/extractor/gaskrank.py
error: could not apply a0758df... [filmon] new extractor

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply a0758dfa1afd5b04773ba3b3b17ac71d22054821... [filmon] new extractor

**Comment by motophil** [comment]
Wohoo :(

**Pull request closed without merging**
