### PR TITLE
[hotstar] added playlist support for hotstar

### PR DESCRIPTION
**Pull request by alpeshvalia**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Added support to download playlist for hotstar
Playlist valid url for hotstar : http://www.hotstar.com/tv/pow-bandi-yuddh-ke/10999/episodes/10856/9993

### CODE REVIEW

**Comment by alpeshvalia** [comment]
Any update on this PR?

**Comment by dstftw** [comment]
See your previous PR.

**Comment by alpeshvalia** [comment]
Yes, I fixed the issues you mentioned in my previous PR and also checked the code with flake.
The query param you asked to use, I tried that but if I use that then that is being encodes further and that is not working hence I used the url

**Comment by dstftw** [comment]
>also checked the code with flake

You did not:
```
.\youtube_dl\extractor\hotstar.py:104:1: E302 expected 2 blank lines, found 1
.\youtube_dl\extractor\hotstar.py:120:69: E202 whitespace before ')'
.\youtube_dl\extractor\hotstar.py:122:47: E703 statement ends with a semicolon
.\youtube_dl\extractor\hotstar.py:125:97: E201 whitespace after '('
.\youtube_dl\extractor\hotstar.py:125:140: E202 whitespace before ')'
.\youtube_dl\extractor\hotstar.py:135:24: E203 whitespace before ':'
.\youtube_dl\extractor\hotstar.py:136:18: E203 whitespace before ':'
.\youtube_dl\extractor\hotstar.py:137:20: E203 whitespace before ':'
.\youtube_dl\extractor\hotstar.py:143:18: E221 multiple spaces before operator
.\youtube_dl\extractor\hotstar.py:144:20: E221 multiple spaces before operator
.\youtube_dl\extractor\hotstar.py:154:40: E201 whitespace after '('
.\youtube_dl\extractor\hotstar.py:154:73: E202 whitespace before ')'
```

>The query param you asked to use, I tried that but if I use that then that is being encodes further and that is not working hence I used the url

Show the code.

**Comment by alpeshvalia** [comment]
http://search.hotstar.com/AVS/besc?action=SearchContents&appVersion=5.0.39&channel=PCTV&moreFilters=series:%s;&query=*&searchOrder=last_broadcast_date+desc,year+asc,title+asc&type=EPISODE

Above is the url which I directly used instead of passing its param to query. As I told, I tried that but that was not working but if I use directly use this link then its working. Somewhere inside_download_json, parameters in query param are being encoded. Following I tried by passing query param
               
`
collection = self._download_json( 'http://search.hotstar.com/AVS/besc', playlist_id, query = {
 'action': 'SearchContents',
                'appVersion': '5.0.39',
                'channel': 'PCTV',
                'moreFilters': 'series:123;',
                'query': '*',
                'searchOrder': 'last_broadcast_date+desc,year+asc,title+asc',
                'type': 'EPISODE'
            }
        )`

Symbols like : ; + * . are being encoded, and that is not working hence I have used as follow
`collection = self._download_json(
            "http://search.hotstar.com/AVS/besc?action=SearchContents&appVersion=5.0.39&channel=PCTV&moreFilters=series:%s;&query=*&searchOrder=last_broadcast_date+desc,year+asc,title+asc&type=EPISODE" % playlist_id,
            playlist_id
        )`

**Comment by Abhinav1217** [comment]
Any info on this PR. I was hoping to download complete a season in one go instead of typing every episodes url.

**Comment by alpeshvalia** [comment]
@dstftw any update on this PR?

**Comment by alpeshvalia** [comment]
Hotstar works with --prefer-ffmpeg option only. This is an existing issue with single video download also

**Comment by alpeshvalia** [comment]
Hello, any update on this PR?

**Pull request closed without merging**
